### ISSUE TITLE
Vault Query usability improvements

### ISSUE THREAD

**Issue by josecoll** [corda/corda#1022]
1. The java helper methods (on the interface) should indeed specify `contractStateType` (not `contractType`)
2. The Kotlin inline extension methods annoyingly need to be imported separately (so IntelliJ automatically defaults to attempting to use the Java interface versions - with the additional `contractType` parameter).
3. When selecting a QueryCriteria, the IDE automatically inlines the full name of the selected criteria (eg. `QueryCriteria.VaultQueryCriteria()` or `QueryCriteria.LinearStateQueryCriteria()` or `QueryCriteria.FungibleAssetQueryCriteria` or `QueryCriteria.VaultCustomQueryCriteria`) rather than importing the individual selected criteria. This leads to very lengthy and verbose criteria specifications.

Ref: https://discourse.corda.net/t/the-query-by-can-not-return-once-invoked/1311/6

**Comment by davidrapacchiale** [comment]
@josecoll can this issue be closed?

**Comment by josecoll** [comment]
Sure can!
