### ISSUE TITLE
KProperty is not serialisable and thus vault query interface over RPC can fail.

### ISSUE THREAD

**Issue by mnesbit** [corda/corda#1027]
During some other work I have hit an issue where my rpc vault query exceptioned stating that a synthetic method was not marked as @CordaSerialisable, or on the whitelist. This is a general problem of the vault query interface over RPC, because the KProperty objects inside the query criteria objects are being serialised and they are not suitable for this. We can't manually annotate them either as they are made by the compiler. My example code was:

```kotlin
private fun getBalance(currency: Currency): Amount<Currency> {
        val sum = builder { CashSchemaV1.PersistentCashState::pennies.sum(groupByColumns = listOf(CashSchemaV1.PersistentCashState::currency)) }
        val sumCriteria = QueryCriteria.VaultCustomQueryCriteria(sum)

        val ccyIndex = builder { CashSchemaV1.PersistentCashState::currency.equal(currency.currencyCode) }
        val ccyCriteria = QueryCriteria.VaultCustomQueryCriteria(ccyIndex)

        val results = rpc.vaultQueryByCriteria(sumCriteria.and(ccyCriteria), FungibleAsset::class.java) // THROWS HERE!!!
        if (results.otherResults.isEmpty()) {
            return Amount(0L, currency)
        } else {
            @Suppress("UNCHECKED_CAST")
            val quantity = results.otherResults[0] as Long
            return Amount(quantity, currency)
        }
    }
```

**Comment by mikehearn** [comment]
Can we switch the unit tests that cover the query API to run in the smoke tests and use RPC only, to catch things like this?

**Comment by josecoll** [comment]
Thats a great idea Mike.
Due to extensive coverage my 80+ JUnits test focused primarily on the VaultQueryService interface (with minimal RPC coverage).

**Comment by mnesbit** [comment]
Flows are consumers of vault queries too. They really are not the same and have different serialisers. So we need two sets of tests.

**Comment by mikehearn** [comment]
Right but flows use in-process queries without any serialisation getting in the way (you can't send a vault query result across the p2p network... or at least we should stop you if you try as that'd be a confused thing to do!). The issue here seems to be that serialisation is never entirely transparent, so we don't pick up on glitches like this until we stumble on them in real usage.

**Comment by mnesbit** [comment]
But you need to be able to suspend a flow, possibly with a query criteria on the stack. The KProperty lambda is not serialisable

**Comment by mikehearn** [comment]
That's true ... I don't see where the KProperty's are sneaking in though. Do you have the serialisation trace that went bad? I decompiled QueryCriteria.kt and don't see KProperty anywhere.

**Comment by josecoll** [comment]
See `QueryCriteriaUtils`

**Comment by mnesbit** [comment]
More precisely KProperty1 is a lambda. KProperty is probably OK

**Comment by mikehearn** [comment]
Ah, I see. The query itself embeds reflection objects! Hmm.

Does the API get a lot uglier if we use just the Java reflection stuff? Do we need to define custom serialisers to be able to serialise Field/Property objects?

**Comment by josecoll** [comment]
By default Java Field is not serializable either:
https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Field.html

**Comment by mikehearn** [comment]
Indeed. So we will have to write a Kryo serialiser for the checkpoints. It should not be hard, I think? Fields have a unique name. We can just serialise class#name and then deserialise by looking it up again afresh.
