### ISSUE TITLE
DemoBench hangs when shutting down a node from the CLI

### ISSUE THREAD

**Issue by gendal** [corda/corda#1041]
* This happens in DemoBench M13 but also happened in M12 I think.
* I tested this on a Mac
* Start a node in DemoBench
* Type "bye <return>"
* Watch the UI freeze for a loooooooooooooooong time

**Comment by mikehearn** [comment]
See https://github.com/corda/corda/issues/689

**Comment by mkit** [comment]
Fixed with https://github.com/corda/corda/pull/1319
