### ISSUE TITLE
Can't upgrade past RxJava 1.1.6

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#105]
Upgrading to the latest RxJava fails due to a subscriber to the dbtx close observables not supporting backpressure properly (very likely the wrapper class). See PR #99 for a discussion. A tip from the RxJava devs:

> Enable assembly tracking with RxJavaHooks.enableAssemblyTracking() around a unit test that fails and you'll get more detailed exceptions about what failed (most likely). But first make sure you don't call onNext concurrently on the PublishSubject.

**Comment by rick-r3** [comment]
We had some thread unsafe usage of PublishSubject, specifically the database commit observations (others still remain, but are not used across threads currently).  Adding `toSerialized()` to this resolved the problem, as did moving the processing onto the server thread.

See commit https://github.com/corda/corda/pull/111
