### ISSUE TITLE
trader-demo download very slowly?

### ISSUE THREAD

**Issue by sun-cd** [corda/corda#109]
E:\work_ch\blockchain\corda-master>**gradlew.bat samples:trader-demo:deployNodes**
Download https://repo1.maven.org/maven2/com/google/guava/guava/19.0/guava-19.0.j
ar

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not download guava.jar (com.google.guava:guava:19.0)
   > Could not get resource 'https://repo1.maven.org/maven2/com/google/guava/gua
va/19.0/guava-19.0.jar'.
      > Premature end of Content-Length delimited message body (expected: 230851
7; received: 1387997

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1 hrs 28 mins 5.013 secs

**Comment by Clintonio** [comment]
It looks like an issue with Maven central, or perhaps your connection. Could you try re-running it to see if it happens again? I'd appreciate it if you could report back your findings. It doesn't usually take longer than 10 minutes to download the dependencies for me the first time I install Corda on a fresh machine.

**Comment by mikehearn** [comment]
No response from reporter, cause likely transient connectivity outage -> closing
