### ISSUE TITLE
Spurious build failure in test ScheduledFlowTests

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#113]
Stacktrace from build server at: http://teamcity.corda.r3cev.com:8111/viewLog.html?buildId=893&buildTypeId=Corda_CordaBuild&tab=buildLog

The specific test is: 

[net.corda.node.services.ScheduledFlowTests] create and run scheduled flow then wait for result

It's a spurious one so the repro steps are to run the test until it fails.

**Comment by rick-r3** [comment]
I think I have a fix for the test in this branch https://github.com/corda/corda/tree/parkri-scheduled-test-stability.  I'm running it through CI a few times to see if the test fails.  15% failure rate, so need to run 6+ times at least.

**Comment by Clintonio** [comment]
Looks to be fixed in #140
