### ISSUE TITLE
Issue in node name rules error message

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#1130]
Trying to create a node with the name "NA" throws the following (contradictory) error message: `java.lang.IllegalArgumentException: Illegal input legal name 'NA'. Legal name must have at least two letters`.

**Comment by rnicoll** [comment]
@patrickkuo I'm guessing this is the rules you've introduced, and there's a `<` vs `<=` hiccup. Can you take a look please?

**Comment by patrickkuo** [comment]
this issue is fixed in #1137
