### ISSUE TITLE
Incorrect code in docsite

### ISSUE THREAD

**Issue by jamescarlyle** [corda/corda#1142]
This looks like an issue - the sample code for checking the transactions signatures is the same as for resolving the transaction

<img width="604" alt="screen shot 2017-07-29 at 18 58 43" src="https://user-images.githubusercontent.com/2500678/28747166-89de91ea-7490-11e7-8ee8-3ff3a993c41e.png">

**Comment by mikehearn** [comment]
Patrick is currently changing how flows are meant to send and receive checked transactions. Patrick, is this glitch fixed by your docsite updates? Or do you still need to write the doc changes?

**Comment by patrickkuo** [comment]
I am moving `ResolveTransactionsFlow` to internal in my PR so this Doc is not relevant anymore, I will change the doc as part of my PR fixes.

**Comment by shamsasari** [comment]
Fixed in #964
