### ISSUE TITLE
Notaries documentation implies centralisation and should be updated

### ISSUE THREAD

**Issue by antonylewis** [corda/corda#1143]
https://docs.corda.net/key-concepts-notaries.html

Notary services explanation should be updated with the most current thinking.  Current text implies they are a single centralised function and a single point of failure / control.  Should avoid use of the word "it".

Notary services create a consensus-based ordering and timestamping of state changes, and ensure a continuous lineage of states ensuring no state has multiple successors.  etc.

**Comment by WizardOfAus** [comment]
@antonylewis It sounds rather centralised. How is it not?

**Comment by gendal** [comment]
Hi @WizardOfAus. You're right in one respect:  a single node notary would indeed be centralised (how could it not!) However, that's not how they're deployed... they're either deployed in HA clusters (ie crash fault tolerant but not byzantine fault tolerant), which can be suitable for some scenarios but I know is not acceptable in all cases - or in byzantine fault tolerant clusters, where each node is operated by a separate party... and so you have no dependency on any single party.

**Comment by joeldudleyr3** [comment]
This is being addressed by this PR: https://github.com/corda/corda/pull/3017.
