### ISSUE TITLE
Missing part in the docsite "Hello World-Writing Acceptor Flow" CorDapp tutorial

### ISSUE THREAD

**Issue by StefanMaff** [corda/corda#1148]
Hi everyone,
in the "Hello World" tutorial there is a missing part, I'm referring to the Flow section  [Writing Acceptor Flow](https://docs.corda.net/hello-world-flow.html#writing-the-acceptor-s-flow )
This is a minor thing but it got me stuck for a while, it is mandatory to override checkTransaction(), but it is not done in the tutorial, instead the function body is left blank.
Referring to [my question on stackOverflow](https://stackoverflow.com/questions/45389843/fail-error-in-cordapp-template-flowtest-progresstracker-hasnt-been-started) I think that the section should be updated like [this one](https://github.com/corda/cordapp-tutorial/blob/master/kotlin-source/src/main/kotlin/com/example/flow/ExampleFlow.kt) that joel proposed to me :) [](url)

**Comment by joeldudleyr3** [comment]
@StefanMaff Thanks for opening an issue :)

It's fine from a coding perspective to overwrite `checkTransaction` with an empty function body. However, in practice you'd want to do some checking there (as discussed on SO). I'll update the tutorial accordingly.
