### ISSUE TITLE
runnodes throws up 10s/100s of terminals in Windows

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#128]
On a Windows 10 VM, `runnodes` in the cordapp-template throws up 10s/100s of terminal windows, which eventually close, leaving only the node terminals.

**Comment by mikehearn** [comment]
Sounds like a globbing issue.

**Comment by Clintonio** [comment]
It's definitely a globbing issue. I have a JIRA task on me to fix windows issues here so I'll self assign.

**Comment by Clintonio** [comment]
Fixed in #143
