### ISSUE TITLE
There is a space in the 'WARN' word in logs

### ISSUE THREAD

**Issue by wawrzek** [corda/corda#1346]
Corda default logs format has probably 'log level' field to have the same width. It's annoying, because there is space after WARN and that breaks field counting in standard UNIX tools like awk, e.g.:
```

> awk '/^\[/ {print $1,$2}' node-latest-notary.log:

[ERROR] 2017-08-29T00:42:39,210Z
[WARN ]
[WARN ]
[WARN ]
[WARN ]
```
When it should be a log level and date.

**Comment by mnesbit** [comment]
This is due to the log4j2 pattern for the file appender being [%-5level] which pads. It can be changed to [%level] if this is regarded as a serious problem. Though I think the plan is to be eventually able to have your own log4j files once we move on from capsule.

**Comment by chrisr3** [comment]
As a rule, fixed-width fields are intended to make log files easier to read by _humans_ because it makes similar fields line up nicely in columns.
