### ISSUE TITLE
Neither BFT or Raft can run in network with mapped IPs

### ISSUE THREAD

**Issue by Quiark** [corda/corda#1467]
For example AWS EC2 will by default assign one network interface with an internal IP address (`172.x.x.x`) but the server will be routable using a public IP as well.

BFT has a list of nodes in cluster and expects their addresses to be public. Then it tries to bind to the public IP in this list. This is where it fails because of the condition above.

Raft appears to have the same problem in principle.

**Comment by Quiark** [comment]
If we use only the internal network for the cluster, it should work. But internal network is only available within the same region so that does not cover all use cases.

**Comment by adagys** [comment]
Thanks @Quiark, I've encountered this issue with Copycat (Raft), and it seems like it's only designed to be used in an internal network :( W'll probably have to submit patches to fix it at some point

**Comment by joeldudleyr3** [comment]
Confirmed this is no longer relevant as of Corda 3.
