### ISSUE TITLE
Track origin details of a transaction

### ISSUE THREAD

**Issue by rnicoll** [corda/corda#156]
Currently tracking any details about a transaction are left to individual CorDapps, which both makes it very difficult to understand what has happened without searching CorDapps individually, and requires effectively reinventing the wheel to track what is likely quite common data in each CorDapp.

It would be beneficial if the vault could track:

* CorDapp(s) involved in creating a transaction, ideally down to the state/command level
* User(s) involved in creating a transaction, as identified by the CorDapp

It may be desirable to extend this to a permission system that restricts transactions so they are not generally visible to CorDapps/users who are not involved, however this requires significant further design (some CorDapps/users will have special permissions, for example).

**Comment by mikehearn** [comment]
Let's keep enhancement requests in JIRA for now. I'd prefer it if we don't fragment tracking of upgrades between github and JIRA. 

I've filed CORDA-148 and CORDA-149:

https://r3-cev.atlassian.net/browse/CORDA-148
https://r3-cev.atlassian.net/browse/CORDA-149

I'll close this.
