### ISSUE TITLE
Attachment storage management tools

### ISSUE THREAD

**Issue by rnicoll** [corda/corda#157]
As a user, I want to be able to find attachments I have uploaded previously for use in new transactions.

As an administrator, I want to be able to identify what attachments a node has.

To fulfil this, attachment storage should track metadata about attachments, including:

* Original filename
* Upload date
* Uploader

It may also be useful to track MIME type, and to be able to tag attachments so that they can be searched for in some meaningful way. Tags could potentially include the CorDapp that the attachment was uploaded via, as this is likely to be a common way of filtering.

**Comment by mikehearn** [comment]
https://r3-cev.atlassian.net/browse/CORDA-150
