### ISSUE TITLE
Maven repositories problem

### ISSUE THREAD

**Issue by bellaj** [corda/corda#16]
Hi,
the following maven remote repos are unreachable 
urls : 
-  r3.bintray.com/corda
- dl.bintray.com/kotlin/exposed

**Comment by Clintonio** [comment]
Hi @bellaj,

Are you behind a firewall that blocks these repositories?

**Comment by mikehearn** [comment]
Those URLs contain a typo - is that the issue?

**Comment by bellaj** [comment]
@Clintonio  no I am not, I am thinking that is a Intellij Issue

**Comment by Clintonio** [comment]
Mike is right though, there are definitely typos in those URLs. It should be `bintray` not `bintary`. Does correcting that solve your problem?

**Comment by bellaj** [comment]
no the issue doesn't have any relation with the previous typo (it was just a typing mistake on github).

**Comment by bellaj** [comment]
I ve found similar issue : http://stackoverflow.com/questions/32037082/unindexed-remote-maven-repositories-in-intellij-idea-14
it is related to intellij

**Comment by Clintonio** [comment]
I haven't indexed my maven repositories and it seems to work fine. Have you tried running directly from the command line with `./gradlew build --info --stacktrace`? 

Could you post the log of the error from the command line output if it fails?

**Comment by bellaj** [comment]
the wired thing is the bintray.com (dl or r3) is unpingable... (behind no proxy no firewall)
even [online ](http://ping.eu/ping/)ping doesn't work

**Comment by mikehearn** [comment]
That sounds like a firewall issue. Bintray is a quite widely used site. It's not down for us.

**Comment by bellaj** [comment]
it seems like the service was unavailable yesterday(many friends had the same issue) but today it is back.

**Comment by mikehearn** [comment]
Glad to hear it's working now!
