### ISSUE TITLE
Custom corda services may require lifecycle methods/events

### ISSUE THREAD

**Issue by dazraf** [corda/corda#1777]
Hi,

At present, the Corda Node does not signal any lifecycle events to a `@CordaService`. The only exception being services that implement `NotaryService`.

In general custom Corda services may require notification of when they may start and crucially when they have to tear-down - this is vital if the service has to release resources bound to its lifetime.

Lifecycle events may be introduced either using an interface (e.g. `CordaServiceLifecycle`) or annotations `@OnStartup` `@OnTeardown`.

**Comment by mikehearn** [comment]
The assumption is that you have to write crash-proof code, so there is no use to having a teardown event. You will inevitably get situations where you are terminated without a clean shutdown.

**Comment by dazraf** [comment]
Thanks Mike, you’re absolutely right. This issue turned up because of an interesting problem with vertx going through its shutdown handler whilst the node was shutting down. Resulted in a ClassNotFoundException when fetching a core vertx class. I can configure vertx to not need to do this. I’m now curious why Notary needs such methods. Closing this issue.

**Comment by mikehearn** [comment]
That's a good question. In some limited cases like database systems it can be more efficient to do a clean teardown, e.g. no need to do a log replay on startup, but the notary can't rely on delivery of such events either. @adagys Do our notary implementations actually benefit from shutdown events of any kind or could we remove them?
