### ISSUE TITLE
Unable to implement AbstractStateReplacementFlow.Acceptor in Java

### ISSUE THREAD

**Issue by shamsasari** [corda/corda#179]
The Java compiler gives the following error:
```
/Users/shamsasari/git/corda/finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java:43: error: A is not abstract and does not override abstract method call() in FlowLogic
    public static class A extends AbstractStateReplacementFlow.Acceptor<String> {
                  ^

```

Adding 
```
@Override
public void call() throws StateReplacementException {
    super.call();
}
```
gives:
```
/Users/shamsasari/git/corda/finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java:43: error: A is not abstract and does not override abstract method call() in FlowLogic
    public static class A extends AbstractStateReplacementFlow.Acceptor<String> {
                  ^
/Users/shamsasari/git/corda/finance/src/main/java/net/corda/contracts/JavaCommercialPaper.java:54: error: call() in A cannot override call() in FlowLogic
        public void call() throws StateReplacementException {
                    ^
  return type void is not compatible with Unit
  where T is a type-variable:
    T extends Object declared in class FlowLogic
```

The issue seems to be the Kotlin compiler compiles `AbstractStateReplacementFlow.Acceptor.call()` to return `void` which the Java compiler doesn't like because `FlowLogic.call()` returns `Object`.

Until this is fixed in Kotlin I suggest we have `Acceptor` be of some type other than `Unit` - the type doesn't matter because it's service flow. We will also need to make sure there aren't other `Unit` flows which are designed to be extended.

**Comment by shamsasari** [comment]
Created a ticket on the Kotlin bug tracker: https://youtrack.jetbrains.com/issue/KT-15964

**Comment by shamsasari** [comment]
The suggested workaround is to use `Unit?`

**Comment by mikehearn** [comment]
Perhaps we should convert AbstractStateReplacementFlow.Acceptor to Java from Kotlin to avoid this kind of problem? Would that help?

**Comment by shamsasari** [comment]
That is another option, but I'm inclined to think `Unit?` is an acceptable workaround.

**Comment by mikehearn** [comment]
Roger mentioned that we don't allow nullable types on the flow generics, maybe the type vars should be made nullable the whole way through. I can't think of any reason not to allow nulls to be returned from flows.

**Comment by shamsasari** [comment]
Hmm. The type parameter of `FlowLogic` can be nullable on a subtype:
```
    class TestFlow : FlowLogic<String?>() {
        override fun call(): String? {
            return null
        }
    }
```

**Comment by mikehearn** [comment]
Yeah, but Roger found a case where the IDE was throwing up some obscure type inference error that was due to nullability and generics intersecting badly. @roger3cev - got the screenshot you can share?
