### ISSUE TITLE
Suspend/wake cycle breaks RPC connection

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#184]
Laptop suspend/wake cycles don't trigger rebuilds of the RPC connections. The cause is probably that client reconnection has to be explicitly configured and it's a TODO in CordaRPCClient:

// TODO: Configure session reconnection, confirmation window sizes and other Artemis features.

http://activemq.apache.org/artemis/docs/1.5.1/connection-ttl.html
http://activemq.apache.org/artemis/docs/1.5.1/client-reconnection.html

We should configure RPC to use these features, as having MQ-based RPC was done exactly to allow Artemis to take care of stuff like this for us. We can also consider a demo mode, in which session teardown on the server is configured for a very long time (like days) so people can suspend their laptops and resume without presentations being interrupted.

**Comment by patrickkuo** [comment]
Fixed for this issue merged into master.
