### ISSUE TITLE
Hibernate warning while looking up AbstractParty type

### ISSUE THREAD

**Issue by roger3cev** [corda/corda#1868]
`[WARN ] 14:39:47,764 [Mock node 3 thread] (JavaTypeDescriptorRegistry.java:127) java.JavaTypeDescriptorRegistry.getDescriptor - Could not find matching type descriptor for requested Java class [net.corda.core.identity.AbstractParty]; using fallback`

It occurs every time an identity lookup is done, for example. The Hibernate docs, suggest that this might have a performance impact. Rick and Jose have previously investigated this but the solution isn't obvious.

From Jose:

> this code is invoked by hibernate every time there is a reference to an AbstractParty: `AbstractPartyToX500NameAsStringConverter`
> it initially gets registered every time we build a Hibernate SessionFactory
> `applyAttributeConverter(AbstractPartyToX500NameAsStringConverter(createIdentityService))`

If it determined that there is no performance impact we can put this back into the backlog and change the logging level.

Cheers

**Comment by rnicoll** [comment]
@roger3cev I think this is fixed in `master`, can you take a look and confirm please?

**Comment by rnicoll** [comment]
Resolved in master now
