### ISSUE TITLE
ShutdownHook not releasing jetty port

### ISSUE THREAD

**Issue by ameyjadiye** [corda/corda#188]
For the development purpose we have Driver class which must implement releasing web app port if you are closing application _or_killing application, most of the time i faced the issue after restarting application it throws error **port already in use** . Each time i have to go on cmd and do ```killall java```

However when i use application from Intelij i see frequency is quite low, from command line this issue is most often.

**Comment by mikehearn** [comment]
@Clintonio Clinton is working on changing how the jetty web server is used - we're de-integrating it from the node. The goal is to remove it entirely: web apps are meant to run in a separate dedicated web server that uses RPC to talk to the node.

**Comment by ameyjadiye** [comment]
@mikehearn Thanks, and yes it must be built like we can create .war file and can be deployed in any application server, embedded jetty is is ok for development purpose.

**Comment by cyrsis** [comment]
Open a console 

taskkill /im java.exe /F

**Comment by ameyjadiye** [comment]
@cyrsis  certainly that's not the solution , what you are telling that's work around and I'm already doing it with `killall java`,  well defined shutdownHook is the only clean solution i see, i will appreciate if anyone have better solution other than what @Clintonio implementing. Thank You.

**Comment by joeldudleyr3** [comment]
Fixed :)
