### ISSUE TITLE
Feature / Arch Pluggable VaultService

### ISSUE THREAD

**Issue by benjumanji** [corda/corda#1898]
Currently looking at the callers / users `VaultService` it doesn't seem particularly easy to switch it out. On the other hand the `VaultService` interface doesn't seem to that hard to implement. Is this something that can go onto your roadmap? I am specifically looking at the `AbstractNode`.

**Comment by joeldudleyr3** [comment]
@benjumanji Could you give me some background on why you'd want to implement your own `VaultService`?

**Comment by benjumanji** [comment]
Thanks for getting back to me, but I am no longer going to be using corda for anything in the near-term. To answer your question though: Initially I was looking at how to create a scaled-out node. However it has become very clear to me that extensiblility is not something that this project seems to take seriously, so I've moved on.

**Comment by mikehearn** [comment]
Ah, that's too bad.

The reason we don't make the vault pluggable is that this would be major heart surgery on the node, and it'd force us to commit to an internal vault API - this would in turn restrict future upgrades to the node. Generally we are trying to provide a high level of API stability, and that in turn forces compromises in terms of what binary interfaces we commit to.

That said, if you want to replace the vault, you can do that by forking the code and re-merging with upstream from time to time.

We're working on scale-out features ourselves as part of Corda Enterprise. So those will become available in future.
