### ISSUE TITLE
Expose jdbcSession on CordaRPCOps just like on ServiceHub

### ISSUE THREAD

**Issue by yshprasanth** [corda/corda#1906]
I have created a Cordapp and while working on it have noticed that jdbcSession() can only be acquired from serviceHub which is passed onto a Flow.

I have a web API and would like to execute a custom sql query from with-in the API. However, the CordaRPCOps object that is available to the API does not expose jdbcSession. 

Can you please have a look and expose the jdbcSession() on CordaRPCOps as well.

**Comment by mikehearn** [comment]
Hiya, if you have a third party web server you can just connect to the database via JDBC directly, as normal. Nothing Corda specific is required.

**Comment by yshprasanth** [comment]
Hi, Thanks for the response.

I have created a Cordapp using the Template provided and have written Web API as suggested in the documentation. This API runs with-in the embedded server.

At the minute, I have created a custom JDBC connection to connect to the H2 database from webAPI. However, it will simplify the whole process of DB connection if the Connection is provided via the injected CordOps objects. Mainly because a similar Connection object is already provided from ServiceHub.

Don't worry if it cant be done. Looking at the Code, it isn't much of change to expose JDBC connection object via CordOps.

**Comment by mikehearn** [comment]
Hmm. The RPC stack won't know how to serialise a JDBC connection object, that's the issue. 

Perhaps though, we can teach it. A JDBC Connection or DataSource could be serialised using a substitute object that the RPC stack understands, which wraps the URL and the username/password. Then doing an RPC to the server is basically just a way to query the JDBC URL and get back a set of usable credentials. But maybe the extra trickyness here isn't worth it. Just vending the JDBC URL as a string could be sufficient.

I think a better fix here is to show how to use a proper web framework like Spring Boot to get a JDBC connection to the same database. In the next open source release the IRS demo has been ported to use Spring Boot. Maybe we can show it there.

**Comment by yshprasanth** [comment]
Hi Mike, Thanks for the detailed information.

May I know the tentative date when you are planning to release the next version (integrated with Spring Boot).

Thanks again.

**Comment by joeldudleyr3** [comment]
Here's an example Spring Boot webserver speaking to a Corda node: https://github.com/corda/spring-webserver. For JDBC, you would simply create a standard JDBC connection from the server (e.g. see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html).
