### ISSUE TITLE
If you do asset swap transaction, collect signatures flow fails because the party doesn't have counterparty's states in it's vault

### ISSUE THREAD

**Issue by ivanr3** [corda/corda#1915]

**Comment by mikehearn** [comment]
Can you provide a bit of sample code Ivan? Sounds like there's a missing resolve somewhere.

**Comment by ivanr3** [comment]
@mikehearn this is solved now, I will close this ticket. The problem was that when you do an asset swap transaction, you need to explicitly send all StateAndRefs and anonymous-to-wellknown party mappings, from the responders side, before you can start collecting signatures for the transaction. Otherwise CollectSignatureFlow would fail.
We discovered this with @roger3cev and agreed that in the future might make sense to externalise asset swap logic into a separate flow and ship it with corda.

**Comment by mikehearn** [comment]
Isn't that what TwoPartyTradeFlow does? @roger3cev

**Comment by voddan** [comment]
I have been stuck with the same problem for a couple of days now, fixed it thanks to this thread.
IMO it would be helpful to have a description of this scenario right there next to the `CollectSignaturesFlow` documentation.
