### ISSUE TITLE
Serialisation of large contract attachments causes OOM exception.

### ISSUE THREAD

**Issue by roger3cev** [corda/corda#1935]
If one has a`LedgerTransaction` on the stack when a flow is check-pointed, then the CorDapp JAR is serialised and persisted to disk. This is problematic because the JAR is copied during the serialisation process and if one has a large JAR file, then it's highly likely that the node will throw a OOM Exception. To date, CorDapp developers understand that they only need to produce one JAR and that JAR constitutes their CorDapp. However, with the above process, this cannot be the case going forward. 

Question: Is the intention that only the contract and state definition is ever included in the JAR? If so, then we very clearly need to make developers aware of this. I.e. putting your front-end in the same JAR is not recommended..!

**Comment by mikehearn** [comment]
Do you  have a copy of the serialisation trace? E.g. the flow snapshot API will give one.

**Comment by joeldudleyr3** [comment]
Fixed.
