### ISSUE TITLE
Spurious test failure in NodeMonitorModelTest

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#200]
The test "NodeMonitorModelTest.cash issue and move" test is failing often on CI, but it is not every time. 

An example of a failure on a branch that passed on a later run is [here](http://ci-master.corda.r3cev.com:8111/viewLog.html?buildId=2546&tab=buildResultsDiv&buildTypeId=Corda_PullRequests). This branch is also merged into master which has passed since.

**Comment by joeldudleyr3** [comment]
This is fixed as of Corda 3.1.
