### ISSUE TITLE
Exception from Corda cash transaction takes down Corda Explorer

### ISSUE THREAD

**Issue by afurgal** [corda/corda#202]
Bank of Corda demo code

I think the pattern is that if you attempt a cash payment transaction which takes the value balance below 0 (i.e. insufficient funds) this takes down the explorer.  (i.e. thrown corda transaction error not caught properly)
I think - may need a bit more debugging.

**Comment by patrickkuo** [comment]
Thanks @afurgal!

Just want to confirm, were you using latest master? and, you said "takes down the explorer", do you mean explorer hangs or does it exit with error?

I have identified a bug which causes explorer to hang when RPC call throws exceptions (e.g Insufficient Funds), just want to make sure we are seeing the same issue.

**Comment by afurgal** [comment]
Hey sorry for not being as clear as I could have been.  This is from M08 and the explorer crashes (i.e. Java process dies throwing an exception).

--
adam@furgal.org
+44 (0)74 5500 2419

**Comment by patrickkuo** [comment]
Hi @afurgal, do you still experience problems with the explorer? Please do attach the error message or screenshots when that happen, it will help the investigation.

**Comment by joeldudleyr3** [comment]
This is fixed as of Corda 3.1.
