### ISSUE TITLE
Observable of future updates in subscribe doesn't have Vault.StateMetadata

### ISSUE THREAD

**Issue by trferreira-BR** [corda/corda#2150]
Currently in Corda/2.0 version is not possible to get information in each update on ledger with Vault.StateMetadata object during each subscribe.

It would be interesting If It was possible to have more details about StateMetadata in produced transaction and consumed transaction, such as: consumedTime, recordedTime, etc.

I concluded with Corda Team (Joel Dudley) by Slack - channel General that  rpc.proxy.vaultTrackByWithPagingSpec(...) returns a DataFeed<Vault.Page, Vault.Update> object, but Vault.Update doesn't return Vault.StateMetadata during each subscribe.

I asked to Joel Dudley in Slack Corda and He confirms that It is a issue.

**Comment by mikehearn** [comment]
@sollecitom Sounds like a gap in the API - can you file a story in JIRA and prioritise as appropriate?

**Comment by sollecitom** [comment]
Yes, we'll put it the backlog.

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-1401.
