### ISSUE TITLE
FR: provide a Vault Query methods without forced specification of Contract Types 

### ISSUE THREAD

**Issue by josecoll** [corda/corda#2164]
where these can be specified as part of the `QueryCriteria` itself.

VALID =>   vaultService.queryBy(Cash.State::class.java, QueryCriteria.VaultQueryCriteria(), PageSpecification(1)).totalStatesAvailable
VALID =>   vaultService.queryBy<Cash.State>(QueryCriteria.VaultQueryCriteria(), PageSpecification(1)).totalStatesAvailable
INVALID => vaultService.queryBy(QueryCriteria.VaultQueryCriteria(), PageSpecification(1)).totalStatesAvailable

**Comment by josecoll** [comment]
Following discussion on Slack #design channel with Fuzz 
https://cordaledger.slack.com/archives/C3J04VC3V/p1512132871000306

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-1399.

**Comment by davidrapacchiale** [comment]
This issue is filed in CORDA OS Jira, it can be closed in github
