### ISSUE TITLE
Node fails on a startup attempting to discover it's public IP / hostname from the NetworkMap service

### ISSUE THREAD

**Issue by ivanr3** [corda/corda#2175]
If OS is configured to use IPv6 addresses, then Corda node fails on a startup attempting to discover it's own public IP / hostname from the NetworkMap.

The way a node discovers its own public ip / hostname - is via the Network Map service:
https://github.com/corda/corda/blob/release-V1/node/src/main/kotlin/net/corda/node/internal/Node.kt#L240
 
Under the hood, the Network Map is just getting a remoteAddress from the ArtemisMq:
https://github.com/corda/corda/blob/release-V1/node/src/main/kotlin/net/corda/node/services/messaging/ArtemisMessagingServer.kt#L433
 
If a system is configured to use IPv6 addresses, then due to a bug in Artemis, the address is returned as "0:0:0:0:0:0:0:1:50028", but should be "[0:0:0:0:0:0:0:1]:50028" (with square brackets). Essentially - this is a string representation of a channel remoteAddress from Netty.
 
Due to this, when Corda tries to interpret such IP - it fails here during startup:
https://github.com/corda/corda/blob/release-V1/core/src/main/kotlin/net/corda/core/utilities/NetworkHostAndPort.kt#L33
 
This is because Java expects URIs to be formatted in the following way:
"IPv6 addresses are permitted for the host component. An IPv6 address must be enclosed in square brackets ('[' and ']') as specified by RFC 2732. The IPv6 address itself must parse according to RFC 2373. IPv6 addresses are further constrained to describe no more than sixteen bytes of address information, a constraint implicit in RFC 2373 but not expressible in the grammar.""

**Comment by vkolomeyko** [comment]
Should we not log these sort of problems in Jira?

**Comment by ivanr3** [comment]
@vkolomeyko I was advised to log it here. Happy to move it to Jira if required.

**Comment by mikehearn** [comment]
We should once we schedule it into a backlog. I didn't do it in this case because I want to establish first that this bug is in code we plan to keep around and is not going to be erased by the network map redesign. If the bug is or will soon be obsolete, I'd rather keep this issue around then close it when we've shipped the update.

**Comment by ivanr3** [comment]
A couple of developers faced this issue today on MSFT hackathon. Diabling IPv6 seems to have solved it. Corda v2.0.

**Comment by shamsasari** [comment]
This has been replaced with a REST endpoint in the HTTP network map which uses the X-Forwarded-For header. We'll be confirming soon that it works as expected.

**Comment by joeldudleyr3** [comment]
The new network map hasn't been tested with IPV6, so this issue could still be around.

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-1402.

**Comment by davidrapacchiale** [comment]
Issue can be tracked in Jira. This issue can be closed.
