### ISSUE TITLE
Corda 2.0 is failing in MAC OS with ClassCastException

### ISSUE THREAD

**Issue by yshprasanth** [corda/corda#2196]
I am getting below exception after upgrading Cordapp to use Corda version 2.0 and while running the nodes in Mac OS. However, the same (2.0) works ok in Windows OS.

Corda v 1.0 works ok in both Mac and Windows OS. I am using JDK/JRE 1.8.

java.lang.ClassCastException: kotlin.Unit cannot be cast to java.lang.Integer
	at com.sun.proxy.$Proxy21.getProtocolVersion(Unknown Source)
	at net.corda.client.rpc.internal.RPCClient$start$1.invoke(RPCClient.kt:121)
	at net.corda.client.rpc.internal.RPCClient$start$1.invoke(RPCClient.kt:82)
	at net.corda.core.internal.InternalUtilsKt.logElapsedTime(InternalUtils.kt:168)
	at net.corda.core.internal.InternalUtilsKt.logElapsedTime(InternalUtils.kt:160)
	at net.corda.client.rpc.internal.RPCClient.start(RPCClient.kt:103)
	at net.corda.client.rpc.CordaRPCClient.start(CordaRPCClient.kt:100)

**Comment by mikehearn** [comment]
That looks like a mismatch between the client and server RPC library versions rather than an operating system issue. Can you make sure your RPC client has JARs from Corda 2.0 on its classpath?

**Comment by gendal** [comment]
@mikehearn assuming this does turn out to be the problem, do we have anything in the wire-stability/versioning work planned to detect situations like this?

**Comment by yshprasanth** [comment]
I can confirm, it is not because of mismatch of versions. I have extracted the Jar files and checked what's in it. Below are the versions configured in the build.gradle file:

ext.corda_release_version = '2.0.0'
ext.corda_gradle_plugins_version = '1.0.0'

**Comment by ragmondo** [comment]
Hi @yshprasanth  - I'll take a look at this shortly - is it possible to share the code that is making this error ? If not I can try a few things on my setup but as @mikehearn pointed out it's quite difficult to fix without access to your exact setup.

**Comment by yshprasanth** [comment]
Hi @ragmondo,@mikehearn, I have tried these simple steps:

1) Take the code from Cordapp Kotlin Template v2 - https://github.com/corda/cordapp-template-kotlin
2) Didn't make any chages to the template, just build (./gradlew deployNodes) using two nodes - PartyA, PartyB, Controller
3) Start the nodes by executing script - build/nodes/runnodes

I can see the same error in the webserver nodes. Attaching screenshot for ref.

I am working on macOS Sierra v10.12.6

![corda rpc error](https://user-images.githubusercontent.com/5559017/34490474-edb5cbf8-efd7-11e7-8760-61740232835e.jpeg)

**Comment by joeldudleyr3** [comment]
What Java version are you using?

**Comment by stanly-johnson** [comment]
I am facing the exact same issue. The example project fails to deploy nodes.

**Comment by mikehearn** [comment]
I'm going to close this because I can't repro it. The template app works for me.

*However* the Kotlin example/template sample needs to be updated to use Spring Boot instead of the old deprecated web server. I've filed https://r3-cev.atlassian.net/browse/CORDA-2069 for that.
