### ISSUE TITLE
Inconsistency to get Notary by serviceHub.networkMapCache with cordapp's build.gradle

### ISSUE THREAD

**Issue by trferreira-BR** [corda/corda#2207]
Hello,

In Corda V2.0, I identified a problem during a try to filter a list to remove the Notary. It is inconsistent the return to calls:

`serviceHub.networkMapCache.notaryIdentities.first()`
> It returns above: C=GB,L=London,O=Controller,CN=corda.notary.validating (with CN)

<br>

`serviceHub.networkMapCache.allNodes.map { nodeInfo -> nodeInfo.legalIdentities.get(0) }`
> It returns above: C=GB,L=London,O=Controller. It identifies which exists two identities - position 0: C=GB,L=London,O=Controller / position 1: C=GB,L=London,O=Controller,CN=corda.notary.validating

 <br>

**At cordapp's build.gradle was declared only:**
node {
    name "O=Controller,L=London,C=GB"
    advertisedServices = ["corda.notary.validating"]
    p2pPort 10002
    rpcPort 10003
    cordapps = ["..."]
} 

If I try to get Notary like below (expliciting the notary using CordaX500Name), the notaryParty is fails and It returns null.

`val notaryName: CordaX500Name = CordaX500Name(
                organisation = "Controller",
                locality = "London",
                country = "GB")

val notaryParty: Party = serviceHub.networkMapCache.getNotary(notaryName)!!`

Could you verify this point?
I attached some images from debug with more details about problem.

![image0_4](https://user-images.githubusercontent.com/34104414/33731126-41a841ba-db69-11e7-8978-6ecfc32d7d7d.jpg)
<br>
![image0_1](https://user-images.githubusercontent.com/34104414/33731127-41d3b386-db69-11e7-8a06-4fedf8c2058a.jpg)
<br>
![image0_2](https://user-images.githubusercontent.com/34104414/33731129-42005238-db69-11e7-857f-e8fbf8e75505.jpg)
<br>
![image0_3](https://user-images.githubusercontent.com/34104414/33731130-423e15e6-db69-11e7-8bf1-6e8570ba87dc.jpg)
<br>
Best Regards,
Thiago Rafael Ferreira

**Comment by trferreira-BR** [comment]
Complementing:
If I declare a CN in build.gradle, the node falls.
It is not possible to declare a CN in notary node, such as:

```
networkMap "O=Notary,L=London,C=GB,CN=Notary"
   node {
       name "O=Notary,L=London,C=GB,CN=Notary"
       advertisedServices = ["corda.notary.validating"]
       p2pPort 10002
       rpcPort 10003
       cordapps = ["..."]
   }
```

**Comment by joeldudleyr3** [comment]
@trferreira-BR Hi Thiago!

First thing to note is that the network map is undergoing a major redesign at the moment, so how this works will change in the near future.

In the current design, each notary has two identities:
- A regular identity
- A notary "service" identity

This is why you get two identities when you use `serviceHub.networkMapCache.allNodes.map { nodeInfo -> nodeInfo.legalIdentities.get(0) }`.

If you want to get a notary by name, you have to use the following syntax:

`val notaryName = CordaX500Name(ValidatingNotaryService.type.id, organisation = "Controller", locality = "London", country = "GB")`

i.e. you have to specify the notary type as the first parameter.

Note that you may also need to add a compile-time dependency on the `corda-node` project to make this work (i.e. adding `cordaCompile "net.corda:corda-node:$corda_release_version"` in your `build.gradle` file).

**Comment by trferreira-BR** [comment]
Hi Joel,

I understand your explanation, but currently the network map is confuse. I hope wich the redesign in network map can have a better structure.

Thank so much
Best Regards,
Thiago
