### ISSUE TITLE
FR: provide a Vault Query queryTransactionNotes extension method

### ISSUE THREAD

**Issue by leehanrick** [corda/corda#2224]
to enable query by servicehub.jdbc session to link transaction details from  vault_states/vault_fungible_states and vault_transaction_notes.

Following discussion on: https://stackoverflow.com/questions/47697456/corda-generatespend-pay-coins-add-memo

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-859.

**Comment by aabhish** [comment]
@joeldudleyr3  I am starting contributing to CORDA. Can you please assign this isue to me? I will soon submit patch for this.

**Comment by joeldudleyr3** [comment]
@aabhish Assigned 👍 I look forward to seeing the outcome :)

**Comment by davidrapacchiale** [comment]
This issue can be tracked in Jira. I am closing the github issue
