### ISSUE TITLE
Explorer nodes run out of memory in simulation mode

### ISSUE THREAD

**Issue by adagys** [corda/corda#229]
After running the simulation (`runSimulationNodes`) for a few minutes we get an OutOfMemoryError and nodes crash.
This is most likely caused by event generators just firing off new `startFlow` requests and never waiting for them to finish, which then queue up, eventually using up all memory.
We could just give it more memory, but I think it's better to fix this behaviour instead.

**Comment by exFalso** [comment]
Do you mean the rate of consumption is lower than the rate of event generation? In that case it will blow up no matter how much memory we give it...

We could for example track the "number of requested flows in flight" and throttle events once it's above a threshold. This way it will behave the same as before in the beginning and slow down later.

We can also just wait for each flow to complete before sending the next

**Comment by mikehearn** [comment]
Can we replace this sim code with the load test tool?

**Comment by adagys** [comment]
@exFalso Yeah, both would work. We could also just wait for all generated flows to finish before starting the next main loop iteration

**Comment by exFalso** [comment]
@mikehearn it's using the same generators. For loadtesting we do want a constant rate for stressing, but for demonstration purposes it's not worth it I think.

We could run the explorer on the loadtested nodes btw without much hustle as they're tunneled to localhost anyway

**Comment by davidrapacchiale** [comment]
Please re-open it if still an issue
