### ISSUE TITLE
Can't name a node with the words "server" or "node" in the name!

### ISSUE THREAD

**Issue by roger3cev** [corda/corda#2326]
Whilst the motivation for this makes complete sense, the rules for determining whether a name should be allowed or not, should be more complicated than:

`require(!legalName.contains(it, true)) { "Character not allowed in legal names: $it" }`

:)

https://beta.companieshouse.gov.uk/search?q=node
https://beta.companieshouse.gov.uk/search?q=server

**Comment by mikehearn** [comment]
Good point. That rule should be enforced in the doorman rather than as a "consensus rule" in every node.

**Comment by shamsasari** [comment]
So that means removing the check
```
LegalNameValidator.validateOrganization(organisation, LegalNameValidator.Validation.MINIMAL)
```
from `CordaX500Name`.

**Comment by shamsasari** [comment]
While we at it the checks
```
        require(country.length == LENGTH_COUNTRY) { "Invalid country '$country' Country code must be $LENGTH_COUNTRY letters ISO code " }
        require(country.toUpperCase() == country) { "Country code should be in upper case." }
```
can probably be removed since we doing a lookup in `Locale.getISOCountries()` anyway.

**Comment by mikehearn** [comment]
Removed as long as they are still present in our doorman ID checking flow, yes.

**Comment by patrickkuo** [comment]
this check is removed in corda v3, closing this issue.
