### ISSUE TITLE
refresh Gradle Project error:public-utils:3.0.3 is not exist by branch:master 

### ISSUE THREAD

**Issue by WallaceVan** [corda/corda#2348]
Thank you for choosing to report an issue with Corda. 

When reporting an issue please make sure it contains;

* A clear description of the issue
* Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)
* Steps to reproduce the issue
* The version/tag/release or commit hash it occured on

**Comment by mikehearn** [comment]
I'm afraid this bug report is not clear enough for us to act on. Perhaps you can provide a more detailed error message.
