### ISSUE TITLE
CommodityContract: generateSpend and Commands.Issue bugs

### ISSUE THREAD

**Issue by ivanr3** [corda/corda#2373]
Couple of bugs in CommodityContract:

1. Issuing Commodities to the ledger always fails the contrac heret: https://github.com/corda/corda/blob/master/finance/src/main/kotlin/net/corda/finance/contracts/asset/CommodityContract.kt#L144 because CommodityContract.Commands.Issue doesn't implement CommodityContract.Commands interface: https://github.com/corda/corda/blob/master/finance/src/main/kotlin/net/corda/finance/contracts/asset/CommodityContract.kt#L74

2. I think CommodityContract.generateIssue were supposed to be static methods rather than instance methods: https://github.com/corda/corda/blob/master/finance/src/main/kotlin/net/corda/finance/contracts/asset/CommodityContract.kt#L154, https://github.com/corda/corda/blob/master/finance/src/main/kotlin/net/corda/finance/contracts/asset/CommodityContract.kt#L160

**Comment by mikehearn** [comment]
Can you take a look at fixing these? CommodityContract is just a demo really, there's no particular reason to keep it around I think, so we could as well just delete it.

**Comment by joeldudleyr3** [comment]
Tracked here: https://r3-cev.atlassian.net/browse/CORDA-1459.

**Comment by joeldudleyr3** [comment]
Resolved.
