### ISSUE TITLE
Incorrect use of PersistentMap in NodeSchedulerService

### ISSUE THREAD

**Issue by ing-rafbhoedjang** [corda/corda#2454]
Version: Corda 2.0.0
File: `NodeSchedulerService.kt`

Line 271 in file `NodeSchedulerService.kt` contains the following statement in function `getScheduledFlow`:

`                    scheduledStates[scheduledState.ref] = newState`

This results in a call to `PersistentMap.set`, which means that any previous value stored in the map is *not* replaced. The new value is effectively lost. This later results in problems; see the comparison at line 262, which uses the value previously stored in the map:

    val previousState = scheduledStates[scheduledState.ref]
    if (previousState != null && previousState === scheduledState) {

The lost update to `scheduledStates` results in an old value being returned from the map. Consequently, the comparison in the if statement fails. In our use case, this then results in a scheduling loop where an old `ScheduledStateRef` keeps on being rescheduled but is never executed.

Proposed solution (**not tested**): use `scheduledStates.put(scheduledState.ref, newState)`

**Comment by mikehearn** [comment]
Thanks for the report. The PersistentMap.set problem has cropped up recently in another context, that just doesn't look like a safe API choice at all. Luckily it's internal so we can tweak it easily.

**Comment by mikehearn** [comment]
https://r3-cev.atlassian.net/browse/CORDA-1002
https://r3-cev.atlassian.net/browse/CORDA-1001
