### ISSUE TITLE
Dependent Cordapps not included by default

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#253]
When specifying a dependent CorDapp in your build.gradle's Cordform task it does not pull the dependent CorDapp into your plugins directory. For example;

Say we have two CorDapp where CorDapp D depends on C in it's dependencies block;

    cordapp project(':cordappC')

Then the below node definition should include this CorDapp C's JAR in the plugin directory of the generated node;

    node {
        name "Controller"
        artemisPort 10002
        cordapps = ['net.corda:cordappD:1.0']
     }

Currently a workaround is to just specify CorDapp C in the cordapps array.

**Comment by davidrapacchiale** [comment]
Please re-open it if still an issue
