### ISSUE TITLE
Build broken on latest master

### ISSUE THREAD

**Issue by James-Sangalli** [corda/corda#254]
Hi,

My build was working perfectly fine until i did a pull from master recently. Now the build fails with unresolved reference errors in NodeVaultSchemaTest.kt

I have invalidated caches and restarted but this doesn't solve the issue.

On my fork you can see a fixed branch which is a working version before the latest pull into master which creates this error, does the build pass on your build management server? 

Thanks

**Comment by josecoll** [comment]
Please perform a complete re-build.
./gradlew clean build
The build now performs annotation processing to generate source files for Vault schemas.
These are the missing references you are referring to.
