### ISSUE TITLE
Provide A Way To Specify Your Terminal Emulator

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#2605]
When using runnodes on Ubuntu it fails because xterm is not installed.
I had to install xterm to make it work, which is annoying as it is a crappy terminal emulator.

There should be a way to specify your terminal emulator as there are [lots available](https://unix.stackexchange.com/a/138006/37237) for linux and people have their own preferences.

Maybe add an env variable in the script.

**Comment by mikehearn** [comment]
https://r3-cev.atlassian.net/browse/CORDA-1387

**Comment by tlil** [comment]
Thanks @richardblocksure - will take a look.

**Comment by opticyclic** [comment]
`/etc/alternatives/x-terminal-emulator` should link to the default terminal

**Comment by davidrapacchiale** [comment]
This issue is tracked in our OS Jira hence closing the issue on GitHub.

**Comment by opticyclic** [comment]
JIRA isn't publicly visible.

How about you only close issues in GitHub when they are fixed instead?

**Comment by opticyclic** [comment]
3 years later and this is still super irritating
