### ISSUE TITLE
cordform plugin does not clean the target deployment directory before deployment.

### ISSUE THREAD

**Issue by abishekktwm** [corda/corda#2629]
When trying to create a deployment, the target directories are not cleaned before a fresh deployment.

This results in multiple node info files and additional-node-infos being present.

Steps to reproduce: `./gradlew deployNodes; ./gradlew deployNodes`

version: `M18-RC01`

**Comment by mikehearn** [comment]
Hm that's deliberate, it makes it faster to develop, but it sounds like we're not detecting that the target directory already has zone files created and doing it again, which is perhaps the real bug.

@shamsasari Does that sound right? Can you file a JIRA ticket if that's the true bug and link to it from here?

**Comment by shamsasari** [comment]
Yep, that's issue. `deployNodes` should delete the `nodes` directory first.

**Comment by shamsasari** [comment]
https://r3-cev.atlassian.net/browse/CORDA-1389

**Comment by shamsasari** [comment]
https://github.com/corda/corda-gradle-plugins/pull/59
