### ISSUE TITLE
No clear error message when RPCClient connects to p2pAddress by mistake

### ISSUE THREAD

**Issue by abishekktwm** [corda/corda#2630]
Connect via clientRPC to the _wrong_ p2pAddress instead of the server RPC address results in an infinite loop of connection retries. This common mistake would be better served by a clear error message.

This is accentuated by the node startup not logging the client RPC addresses anymore. Unclear if this is intentional or an error. The current node startup logs print the p2pAddress and the p2pPort twice.

>

>     ______               __
>   / ____/     _________/ /___ _
>  / /     __  / ___/ __  / __ `/         Computer science and finance together.
> / /___  /_/ / /  / /_/ / /_/ /          You should see our crazy Christmas parties!
> \____/     /_/   \__,_/\__,_/
> 
> --- Corda Open Source corda-3.0-RC01 (4157c25) -----------------------------------------------
> 
> 
> Logs can be found in                    : <redacted>/logs
> Database connection url is              : <redacted>/node
> Incoming connection address             : localhost:20005
> Listening on port                       : 20005

version: `M18-RC01`

**Comment by mikehearn** [comment]
@bpaunescu Can you also fix it so if the port numbers are wrong we don't go into an infinite loop?

@tudor-malene Might this be fixed by your RPC SSL work?

**Comment by tudor-malene** [comment]
@mikehearn, I think this case is a non-ssl connector (the RPC client)  attempting to connect to an ssl acceptor ( P2P ), and some failover logic intercepting the exception and retrying. 
Seems unrelated.

**Comment by joeldudleyr3** [comment]
@bpaunescu Is there a JIRA ticket to track this issue?

**Comment by davidrapacchiale** [comment]
This is affecting an old version of Corda and, I suspect, it's been fixed in subsequent releases. @tudor-malene can you please re-open this if that's not the case? Thanks
