### ISSUE TITLE
Create The META-INF services From The Build

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#2785]
At the moment you have to create files that are in META-INF as part of your source code.
e.g.
    
    # Register here any CorDapp plugins extending from net.corda.node.CordaPluginRegistry.

Almost all files in the META-INF directory are normally created as part of the build process.

It would make sense to create these services files automatically using reflection or annotations instead of people manually updating a text file in their source code.

**Comment by mikehearn** [comment]
Most things don't require that anymore and CordaPluginRegistry was deleted some time ago. Are you using an old version?
