### ISSUE TITLE
Add A Method That Runs A Flow And Returns

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#2788]
I wasted an hour trying to work out why nothing was in the vault here:

        val myFlow = MyFlows.MyFlow(Amount(50000, USD), mainBank.info.chooseIdentity())
        testBank.services.startFlow(myFlow)

        val testStates = mainBank.database.transaction { mainBank.services.vaultService.queryBy<TestState>().states }

It turns out that if I add `.resultFuture.getOrThrow()` to the `startFlow` function the vault will have the state.

The API would be a lot more user friendly if there were convenience methods that wrapped things like this.
Right now writing a client application feels like you are developing the core because so much of the internals are exposed.

See also https://github.com/corda/corda/issues/2787

**Comment by anthonykr3** [comment]
Thanks for the report. We've made a lot of changes to the test api as part of our v3 release, and it now doesn't expose any internals. If you migrate to version 3, the StartedMockNode class (which replaces the StartedNode<MockNode> in the MockNetwork) in the test api has a startFlow function which calls startFlow and then calls .resultFuture.getOrThrow() - hopefully that should help.
