### ISSUE TITLE
Add More Currencies

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#2807]
There are only 6 currencies defined internally
https://github.com/corda/corda/blob/master/finance/src/main/kotlin/net/corda/finance/Currencies.kt

You should expand that to cover at least the top 10 traded currencies and probably cover more like top 25 to make the product more usable for banks to use out of the box.

**Comment by joeldudleyr3** [comment]
@opticyclic Hi, can you open a PR to add the top 10/top 25? See https://docs.corda.net/contributing.html for some guidelines, or reach out on Slack :)

**Comment by joeldudleyr3** [comment]
We are currently reworking the cash app to better reflect the requirements of real-world financial institutions. @roger3cev may be able to shed some light around what we're doing around currencies in the redesign?
