### ISSUE TITLE
Add More Financial Products

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#2809]
There are very few financial products and it is a lot of repetition for every project to recreate the same financial products over and over again.

**Comment by mikehearn** [comment]
We have big dreams for the finance app, but in the end Corda is a platform for writing apps (many of which will handle the details of specific products) and the finance app is partly just a big showcase. We're working on making the cash app much more realistic and deployable, but the others (commercial paper etc) are just toys. 

Making sure Corda users have access to a huge library of really solid, production-quality financial products on ledger is basically our job for the next five years. So I'll close this issue as it's a bit larger than a GitHub issue can encompass. Please do feel free to continue the debate though.
