### ISSUE TITLE
startFlow fails when a big byte array is passed to a flow

### ISSUE THREAD

**Issue by polybioz** [corda/corda#281]
I'm calling `CordaOPS.startFlow` from a web api registered in a Corda plugin registry:
```
val content = ByteArray(102400)
val ret = services.startFlow(::MyFlow, content).returnValue.get()
```
startFlow hangs for byte arrays greater than ~102300 bytes with the following warning:
```
W 15:44:13 56 rpc.run - Received malformed client RPC message: missing _AMQ_VALIDATED_USER property
```

**Comment by kchalkias** [comment]
This is probably the same issue with https://github.com/corda/corda/issues/412

**Comment by mikehearn** [comment]
Yes, it's the same issue, closing this one as a duplicate.
