### ISSUE TITLE
Map classes not registered in Kryo

### ISSUE THREAD

**Issue by polybioz** [corda/corda#284]
`EmptyMap`, `HashMap`, `SingletonMap` , `LinkedHashMap` are not registered in Kryo by default and need to be registered manually in CorDapp.

**Comment by mikehearn** [comment]
Assigning to Rick - I think some of this is already done, right?

**Comment by rnicoll** [comment]
We've seen problems with serialization stability with maps and sets, which can cause some extremely difficult to diagnose issues with transaction IDs changing between initial construction and receipt by remote peers. For these use-cases you would normally store raw key/value pairs in the contract state objects, and convert to a map for processing in the contract logic.

Can you let me know if that answers this problem, or if you have a use-case we've not addressed please?

**Comment by mikehearn** [comment]
Rick has been working on this already. I believe Kasia did some work on this too. The solution was to simply ban HashMap/HashSet and required the use of LinkedHashMap/LinkedHashSet instead. On deserialisation the latter are used.

**Comment by lazyGoose** [comment]
Is anyone still on it? I can work on this issue.

**Comment by gendal** [comment]
Hi @lazyGoose - sorry nobody has replied to you yet. I'll ping the team to take a look and get back to you asap.  Thanks for offering to help!

**Comment by joeldudleyr3** [comment]
This is resolved as of Corda 3.1. `EmptyMap`, `SingletonMap` and `LinkedHashMap` are all whitelisted. `HashMap` is not whitelisted, for the non-determinism reasons listed above.
