### ISSUE TITLE
Why Is The Word "corda-" In The Version?

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#2869]
The version numbering for v3 of corda looks incorrect. (Although the [ plugins ](https://jcenter.bintray.com/net/corda/plugins/cordformation/) look fine)
http://repo1.maven.org/maven2/net/corda/corda-finance/

    0.13.0/                                           2017-06-28 07:09         -      
    0.14.0/                                           2017-08-08 15:36         -      
    1.0.0/                                            2017-10-02 18:21         -      
    2.0.0/                                            2017-11-17 14:16         -      
    corda-3.0/                                        2018-03-12 18:16         -  

You have added the word "corda-" into the version number.

Maven version numbers are supposed to be numbers and not words.

This can also cause future dependency resolution errors as build tools are expecting numbers.
http://www.mojohaus.org/versions-maven-plugin/version-rules.html

http://maven.apache.org/ref/3.5.3/maven-artifact/xref/org/apache/maven/artifact/versioning/DefaultArtifactVersion.html

See this contrived example where I have added a different lower version into the dependencies (in real life this could be as a transitive dependency)

    buildscript {
    
        repositories {
            jcenter()
        }
    
        dependencies {
            classpath "net.corda.plugins:cordformation:3.0.0"
            classpath "net.corda.plugins:quasar-utils:3.0.0"
        }
    }
    
    repositories {
        jcenter()
    }
    
    apply plugin: 'java'
    apply plugin: 'net.corda.plugins.cordapp'
    apply plugin: 'net.corda.plugins.cordformation'
    
    dependencies {
        // Corda integration dependencies
        cordaCompile "net.corda:corda-finance:corda-3.0"
        cordaCompile "net.corda:corda:corda-3.0"
        cordaCompile "net.corda:corda-core:2.0.0"
    }

Now when I run gradle dependencies you will see that gradle has chose v2 instead of v3

    +--- net.corda:corda-finance:corda-3.0
    |    +--- com.typesafe:config:1.3.1
    |    +--- net.corda:corda-core:corda-3.0 -> 2.0.0

If I do the same thing with 1.0.0 and 2.0.0 you will see that gradle chooses the higher number as expected.

    dependencies {
        // Corda integration dependencies
        cordaCompile "net.corda:corda-finance:2.0.0"
        cordaCompile "net.corda:corda:2.0.0"
        cordaCompile "net.corda:corda-core:1.0.0"
    }

    +--- net.corda:corda-finance:2.0.0
    |    +--- net.corda:corda-core:2.0.0
    \--- net.corda:corda-core:1.0.0 -> 2.0.0 (*)

It looks like you should re-release version 3 to match the standard naming conventions.

**Comment by mikehearn** [comment]
This will be fixed with v3.1 which should be out soon, the word will come after the number as is more conventional.

It was/is an attempt to differentiate Corda open source artifacts from the R3 Corda (enterprise edition) artifacts.

**Comment by mikehearn** [comment]
It's fixed in the upcoming 3.1 release.

**Comment by opticyclic** [comment]
It would be better to use the group id or the artifact id to distinguish between open source and enterprise.

**Comment by fenryka** [comment]
3.1 is released with the versioning swapped from corda-3.0 to 3.1-corda which hopefully makes things better whilst retaining the intentional labeling of the version.

https://github.com/corda/corda/releases/tag/release-V3.1

**Comment by opticyclic** [comment]
Surely it would have made more sense to use the version number 3.1 and use com.r3.corda for the group id of the enterprise version.
