### ISSUE TITLE
Deploy version 3 artefacts to maven central

### ISSUE THREAD

**Issue by dazraf** [corda/corda#2878]
Please can you deploy version 3 artifacts to maven central. Thanks.

**Comment by fenryka** [comment]
Looking at https://mvnrepository.com/artifact/net.corda/corda/corda-3.0 it seems to be there, unless this isn't what you're referring to

**Comment by fenryka** [comment]
They are in maven central

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.corda%22%20AND%20a%3A%22corda%22
