### ISSUE TITLE
Triple class is not on whitelist, but should

### ISSUE THREAD

**Issue by janisolekss** [corda/corda#2940]
https://github.com/corda/corda/blob/130b1d9325e23f67de47097cf14a716ae03559f8/node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/DefaultWhitelist.kt#L22

**Comment by mikehearn** [comment]
https://r3-cev.atlassian.net/browse/CORDA-1384

**Comment by joeldudleyr3** [comment]
https://github.com/corda/corda/pull/3018
