### ISSUE TITLE
Unable to change the issued key to a node

### ISSUE THREAD

**Issue by abishekktwm** [corda/corda#2984]
Thank you for choosing to report an issue with Corda. 

When reporting an issue please make sure it contains;

* A clear description of the issue

If I issue a new certificate to a node (say by removing the existing certificate and starting the node to issue a new dev certificate) it corrupts the node database and throws the following exception

* Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)
```

E 13:50:32-0400 [main] internal.Node.run - Exception during node startup {}
 java.lang.IllegalArgumentException: More than one node found with legal name OU=XXX, O=XXX, L=XXX, C=XXX
	at net.corda.node.services.network.PersistentNetworkMapCache.getNodeByLegalName(PersistentNetworkMapCache.kt:161) ~[corda-node-corda-3.0-RC01.jar:?]
	at net.corda.node.services.network.NetworkMapCacheImpl.getNodeByLegalName(PersistentNetworkMapCache.kt) ~[corda-node-corda-3.0-RC01.jar:?]
	at net.corda.node.internal.AbstractNode.initNodeInfo(AbstractNode.kt:322) ~[corda-node-corda-3.0-RC01.jar:?]
	at net.corda.node.internal.AbstractNode.access$initNodeInfo(AbstractNode.kt:103) ~[corda-node-corda-3.0-RC01.jar:?]
	at net.corda.node.internal.AbstractNode$start$4.invoke(AbstractNode.kt:207) ~[corda-node-corda-3.0-RC01.jar:?]
	at net.corda.node.internal.AbstractNode$start$4.invoke(AbstractNode.kt:103) ~[corda-node-corda-3.0-RC01.jar:?]


```
* Steps to reproduce the issue
Build a cordapp using cordformation. Start a node. Stop the node. Delete the certificates/*. Start the node again.
* The version/tag/release or commit hash it occured on
M18-RC01

**Comment by mikehearn** [comment]
Is that M18 of Corda? As in from last year? I'm afraid if so, we don't support that old version anymore! Also the network map and identity handling code changed completely since then.

**Comment by kchalkias** [comment]
This is still possible to happen in current version of Corda. `certificates` directory holds all of the legal identity node keys. It is advisable to one get a backup of this folder in case of accidental deletion.

Among the others, regenerating and re-issuing a new certificate means that if there were assets owned by your previous key(s), you won't be able to consume them. Assuming you can tolerate that, the process of reissuing a new cert for the same identity depends on the network operator policy. In practice, there should be an initial step of revoking the previous certificate (so it's not in the Network Map anymore) then re-issue a new one.

**Comment by joeldudleyr3** [comment]
@kchalkias So is this a bug, or normal behaviour? It looks like we can improve that error message to suggest revoking the certificate at the least?

**Comment by kchalkias** [comment]
@joelsudleyr3 it depends on the Network policy, for instance, the Corda Network demands one NodeCA per node, so you need to revoke before reissuing (but this might not be enforced in other custom networks)

**Comment by joeldudleyr3** [comment]
@abishekktwm Opened a PR to have a clearer error message: https://github.com/corda/corda/pull/3087.

**Comment by arsalankhalid** [comment]
@joeldudleyr3 you guys should leave simple issues like this open, and mark them with a good_first_bug label or something, to allow developers adopting your platform to contribute.

**Comment by kchalkias** [comment]
@abishekktwm take a look at [Network Permissioning](https://docs.corda.net/permissioning.html#network-permissioning), mainly the image depicting our cert hierarchy. Briefly, `Doorman` issues `NodeCA` certs for each node. There is only one valid `NodeCA` per node at any given time (as advertised by the Network Map).
However, **you are not signing transactions with the `NodeCA` key**; this key serves the role of a node-internal certificate authority to generate the transaction signing (Well-known Identity) and TLS keys.
Our current code-base assumes one `Well-Known Identity`, but theoretically, the cert-hierarchy structure does not preventing you from generating as many `Well-known Identity` keys as you wish.

**Comment by kchalkias** [comment]
With regards to certificate revocation, @mkit is already working on supporting and documenting the full process.

**Comment by davidrapacchiale** [comment]
Closed based on this PR https://github.com/corda/corda/pull/3087 comments
