### ISSUE TITLE
Error:(60, 82) Kotlin: Unresolved reference: Models

### ISSUE THREAD

**Issue by amitdubal** [corda/corda#299]
Facing issue when trying to build the project in Intellij Idea. 
Error:(60, 82) Kotlin: Unresolved reference: Models

code:
 val configuration = KotlinConfiguration(dataSource = dataSource, model = Models.VAULT, mapping = setupCustomMapping())
       
Code path as follows:
corda-master\node-schemas\src\test\kotlin\net\corda\node\services\vault\schemas\VaultSchemaTest.kt

**Comment by mikehearn** [comment]
This is due to the new requery stuff. Have you tried doing a gradle refresh, or building from the command line with gradle?

**Comment by mikehearn** [comment]
I think this is fixed now we changed how this stuff works in master / M10.
