### ISSUE TITLE
Missing PageSpecification in NodeVaultService

### ISSUE THREAD

**Issue by Quiark** [corda/corda#3023]
With corda 3.1, don't ask how, but somehow I ended up with a cash transaction that has 201 inputs. This failed when trying to record it in the node vault because the vault query does not include a PageSpecification. 

I don't have the stack trace any more but I think it's in `NodeVaultService.makeUpdates.makeUpdate:139`

**Comment by joeldudleyr3** [comment]
Yes, it looks like it would fail when doing this query if there are too many inputs:

    private fun loadStates(refs: Collection<StateRef>): Collection<StateAndRef<ContractState>> {
        return if (refs.isNotEmpty())
            queryBy<ContractState>(QueryCriteria.VaultQueryCriteria(stateRefs = refs.toList())).states
        else emptySet()
    }

**Comment by joeldudleyr3** [comment]
We cannot simply provide a max-size page specification as that can potentially lead to JVM OOM exceptions.

We need to constrain the maximum number of allowable states in a transaction. This should be tied into the Network Parameters maximum transaction size and the maximum enforced by the notary https://github.com/corda/corda/commit/7ad19af93f405ae186479b176f1ae49a5a17d790#diff-2ec1f5dbe59e94155c77c7457b37c08fR136.

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-1395.

**Comment by joeldudleyr3** [comment]
This has now been fixed.
