### ISSUE TITLE
Already-running detection still deletes process-id file

### ISSUE THREAD

**Issue by Quiark** [corda/corda#3084]
Corda node manages the `process-id` in node directory to prevent running multiple instances. But the file gets deleted on second start of the node, making the 3rd start possible.

1. start corda node. It runs normally and creates `process-id`
2. start corda node. It stops and complains that it's already running and deletes `process-id` (<-- that's where you're wrong, kiddo)
3. start corda node. It does not complain but doesn't start normally because (1) is already running

**Comment by joeldudleyr3** [comment]
Thanks. Raised here: https://r3-cev.atlassian.net/browse/CORDA-1455. Can you confirm this is on Corda 3.1?

**Comment by Quiark** [comment]
yes

**Comment by joeldudleyr3** [comment]
@Quiark Resolved :)
