### ISSUE TITLE
[Docs] Hello World pt2 flow control commands is misguided

### ISSUE THREAD

**Issue by vstoykov** [corda/corda#3120]
I'm following the tutorial and when I'm reading the [code about creating a command](https://docs.corda.net/tut-two-party-flow.html) I see this:
```
val cmd = Command(IOUContract.Create(), listOf(ourIdentity.owningKey, otherParty.owningKey))
```
The important part is `IOUContract.Create()`. Few lines below there is the following text:

> First, we need to update the command. We are now using `IOUContract.Commands.Create`, rather than `TemplateContract.Commands.Action`.

In the code it is `IOUContract.Create()` but in the text it is described as `IOUContract.Commands.Create`. Which one is the correct one?

**Comment by joeldudleyr3** [comment]
@vstoykov The correct one is `IOUContract.Create` - see https://github.com/corda/corda-tut2-solution-kotlin/blob/release-V2/cordapp-contracts-states/src/main/kotlin/com/template/StatesAndContracts.kt.

I'll fix it up by editing the file here: https://github.com/corda/corda/blob/master/docs/source/tut-two-party-flow.rst, unless you want to open a PR to do it?

**Comment by vstoykov** [comment]
I was wondering if instead of adding `class Create` directly to `IOUContract` to tell others to rename `Action` to `Create` and then it will be `IOUContract.Commands.Create` as was originally written in the text. 
I see that this will probably be some extra burden for the first tutorial but as I can see on the next tutorial [Writing a contract](https://docs.corda.net/tutorial-contract.html) the Commands interface is used and probably will be better for newcomers to get used to this best practice. Especially if the cordap template has it.

I know that more things need to be changed but what you think about it?

**Comment by joeldudleyr3** [comment]
@vstoykov This is being looked into by @kid101.

I think either way is fine. This has been fixed here so we'll go with not grouping them for now I think: https://github.com/corda/corda/pull/3133#pullrequestreview-119786113.

@vstoykov Thanks again for raising this :)
