### ISSUE TITLE
Remove duplicated code between `PersistentIdentityService` and `InMemoryIdentityService`

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3148]
**Issue:** There is a **lot** of duplicated code between `PersistentIdentityService` and `InMemoryIdentityService`.

**Proposed fix:** Refactor duplicated code out into `IdentityServiceUtil`.

**Where:** https://github.com/corda/corda/tree/master/node/src/main/kotlin/net/corda/node/services/identity

**Comment by stanly-johnson** [comment]
@joeldudleyr3 I'll work on this 👍

**Comment by lankydan** [comment]
has this been done? If not, I can have a look at it.

**Comment by joeldudleyr3** [comment]
I don't think so - go ahead :) @stanly-johnson - let us know if you're still working on this

**Comment by stanly-johnson** [comment]
No, it's not done. @lankydan go ahead :)
