### ISSUE TITLE
Network bootstrapper should check for duplicate node names

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3149]
**Issue:** The network bootstrapper does not check for duplicate names in the `node.conf` files before bootstrapping the network.

**Proposed fix:** Check for duplicate node names in the `node.conf` files before bootstrapping the network.

**Where:** https://github.com/corda/corda/blob/master/node-api/src/main/kotlin/net/corda/nodeapi/internal/network/NetworkBootstrapper.kt

**Comment by stanly-johnson** [comment]
@joeldudleyr3 Can i work on this? Is this assigned to someone?

**Comment by joeldudleyr3** [comment]
@stanly-johnson Hi Stanly! Nope, please go ahead :)

The contributing instructions are here: https://docs.corda.net/head/contributing.html, and don't forget to add your name here: https://github.com/corda/corda/blob/master/CONTRIBUTORS.md (real names, company names and GitHub usernames are all fine).

Drop me a message here or in slack.corda.net on the #contributing channel if you have any questions. @shamsasari might also be able to help.

**Comment by shamsasari** [comment]
Resolved in this PR https://github.com/corda/corda/pull/3182
