### ISSUE TITLE
In Demobench, Explorer does not show notary node's identity in the Network view

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3165]
**Issue:** You can reproduce this as follows:

- Start Demobench (https://www.corda.net/downloads/)
- Start a notary node
- Start the Explorer on the notary node
- Go to the Network view
- There is nothing in the `My identity` pane, and the map is not centered on the notary node

**Comment by dhingra** [comment]
@joeldudleyr3  Looks like this is not an issue anymore? _My identity_  pane rendering information now.

![image](https://user-images.githubusercontent.com/7157372/43041257-bf51f43c-8d28-11e8-8186-91079cb38613.png)

**Comment by joeldudleyr3** [comment]
@dhingra Thanks for flagging.
