### ISSUE TITLE
In flow tests, misleading result if `transaction` is forgotten

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3181]
See https://github.com/corda/cordapp-example/blob/nitesh-bug-branch/kotlin-source/src/test/kotlin/com/example/flow/IOUFlowTests.kt#L59.

Although Node C is not part of the flow, and should therefore have nothing in the vault, we see the state anyway when printing the contents of his vault.

This is because we forget to open a new transaction before checking Node C's database, so I'm guessing we're effectively checking Node B's database instead.

We should catch this.

**Comment by joeldudleyr3** [comment]
Tracked here: https://r3-cev.atlassian.net/browse/CORDA-1500.

**Comment by davidrapacchiale** [comment]
Closed. It's being tracked on Corda OS Jira.
