### ISSUE TITLE
':node' could not be found exception

### ISSUE THREAD

**Issue by pj-vvs** [corda/corda#32]
I an getting the below exception

A problem occurred evaluating root project 'corda'.
> Project with path ':node' could not be found in root project 'corda'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.892 secs
Project with path ':node' could not be found in root project 'corda'.

**Comment by exFalso** [comment]
What shell command are you running when you get this? What is your working directory?

**Comment by pj-vvs** [comment]
![err1](https://cloud.githubusercontent.com/assets/24291393/20934664/ed46d4c4-bc01-11e6-96f9-b0911732cb0f.jpg)
 I am running in intellij and getting that error.

![error](https://cloud.githubusercontent.com/assets/24291393/20934675/f842d814-bc01-11e6-814b-87d72fa61512.jpg)


Could you please specify the how to set the "use classpath for module" shown in above.

Thanks in advance

**Comment by Clintonio** [comment]
Hello @pj-vvs 

Judging from your project on the left hand side your gradle isn't correctly imported.

To get it working again you'll need to refresh gradle. The steps to do this are;

1. Click "View" in the menu bar
2. Click "Tool Windows"
3. Click "Gradle"
4. Now the "Gradle Projects" window is open on the right hand side
5. Click the little refresh icon in the top left of this window.

This should solve your problems. It would also be worth checking out any changed gradle or intellij files to be sure nothing has changed.

**Comment by pj-vvs** [comment]
Thank you @Clintonio and @exFalso 

I followed those steps and downloaded .

but while running sample demo's, failing in first step mentioned below

**To run from IntelliJ:

1.Open the Corda project in IntelliJ and run the “Install” configuration
2. Open the Corda samples project in IntelliJ and run the “Trader Demo: Run Nodes” configuration
3. Run “Trader Demo: Run Buyer”
4. Run “Trader Demo: Run Seller”**

( Reference : https://docs.corda.net/running-the-demos.html )

and the error page shown below.

![err2](https://cloud.githubusercontent.com/assets/24291393/20980320/1150573a-bcd6-11e6-8139-830bede681d8.jpg)

**Comment by Clintonio** [comment]
It looks like Node exists in your project. Could you post the full build log with the error?

**Comment by shamsasari** [comment]
@pj-vvs are you still having this issue?

**Comment by pj-vvs** [comment]
@shamsasari I am facing that issue still.Could you please tell me how to resolve it.
apologize for late reply.

**Comment by shamsasari** [comment]
Can you try refreshing Gradle from the Gradle window. I wonder if starting all over again might help (i.e. starting from cloning the repo again)

**Comment by Clintonio** [comment]
@pj-vvs are you still having trouble?

**Comment by shamsasari** [comment]
Closing this. The code has change a lot since this was raised. If you are still having issues please raise a new ticket.
