### ISSUE TITLE
Issues with IntelliJ configuration - duplicate content roots 

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#325]
![image](https://cloud.githubusercontent.com/assets/474659/23659894/9749998c-033f-11e7-9d33-70b4ae5c48ff.png)

You can reproduce this error by opening Corda in IntelliJ then "File -> Project Structure" and modifying any value and trying to apply it.

**Comment by GavT** [comment]
Is this now obsolete?

**Comment by mikehearn** [comment]
Fixed
