### ISSUE TITLE
VaultTrack returns undesired states

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3276]
**Issue:** When you use the `vaultTrack<T>` Corda RPC operation, the observable will return all the states from all the transactions that contain a state of type `T`, and not just new states of type `T`. For example, `proxy.vaultTrack(ClaimState.class)` will return all states from all transactions containing one or more `ClaimState`s, even if some of those states are not `ClaimState`s,

Proposed fix: Modify the vault to filter the streamed updates.

Where: https://github.com/corda/corda/blob/0a4d98161afc4f81348b164636b3ae55cf74dc0f/node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt

**Comment by lankydan** [comment]
im looking at this.

**Comment by joeldudleyr3** [comment]
Addressed by https://github.com/corda/corda/pull/3336#issuecomment-396242296.
