### ISSUE TITLE
[doc] Tutorials Writing Flows Progress tracking (flowTracker/progressTracker)

### ISSUE THREAD

**Issue by vstoykov** [corda/corda#3291]
I'm currently following Corda's tutorial and I think that there is a typo. In the [Tutorials -> Writing flows -> Progress tracking](https://docs.corda.net/flow-state-machines.html#progress-tracking) is written:

> The flow framework is somewhat integrated with this API. Each FlowLogic may optionally provide a tracker by overriding the `flowTracker` property (`getFlowTracker` method in Java). 

But in the example code in `TwoPartyTradeFlow.kt` instead of overriding `flowTracker` we can see the following:

    override val progressTracker = ProgressTracker(RECEIVING, VERIFYING, SIGNING, COLLECTING_SIGNATURES, RECORDING)

Should the docs need to be changed to use `progressTracker` and `getProgressTracker`, instead of `flowTracker` and `getFlowTracker` or I'm missing something?

**Comment by joeldudleyr3** [comment]
That's right. Would you like to PR a fix or should we look into it?

**Comment by vstoykov** [comment]
I can make a PR.

**Comment by joeldudleyr3** [comment]
Awesome. Take a look at the guidelines here: https://docs.corda.net/head/contributing.html.
