### ISSUE TITLE
[doc] Make clear distinguish between Corda identities and RPC client users

### ISSUE THREAD

**Issue by Koshub** [corda/corda#3326]
Not sure if this an issue at all. There is a problem I think where docs do not describe clearly that identities in Corda API (described as `Party` etc) are not related to identities of users described here as RPC client users. One should think about it for some time and read different parts of docs to make sure both identities have different domain. Although Corda docs are good I think describing this will be is a major improvement in docs.

**Comment by joeldudleyr3** [comment]
Thanks @Koshub, sorry I didn't get to this earlier. Could you point to the specific places where the docs are confusing?

**Comment by Koshub** [comment]
@joeldudleyr3 Thank you for response. There is no specific place. The idea of issue is the absence of this, not about some definite description in docs. I suggest just append docs with "distinguish" description, for example, at the beggining where identities are described. I think it will give more clearity at the start of docs reading

**Comment by joeldudleyr3** [comment]
@Koshub Let me know if this fixes it: https://github.com/corda/corda/pull/3480.

**Comment by Koshub** [comment]
@joeldudleyr3 Yep, now it is more clear, I think. Thank you.
