### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: A TOP N or FETCH rowcount value may not be negative.

### ISSUE THREAD

**Issue by cxyzhang0** [corda/corda#3364]
Hi @josecoll,
  I got the above exception when connecting to MSSQL and running a simple vault query (such as /api/yo/yos).  That happens to both release-V3.1 and the 4.0-SNAPSHOT.  Looks like hibernate pagination for MSSQL adds a TOP (?) clause which is given a negative value due to 
query.firstResult = (paging.pageNumber - 1) * paging.pageSize in the _queryBy function in NodeVaultService.kt.  The default pageNumber is -1.
If I floor it with maxOf(0, (paging.pageNumber - 1) * paging.pageSize), the query works.
Does that fix have any side effects?

\Sean

**Comment by josecoll** [comment]
@szymonsztuka Please can you take a look at this issue and verify whether it causes a problem in Corda Enterprise.

@cxyzhang0 We do not officially support SQL Server in Open Source but feel free to raise a PR and address your problem above (as long as it doesn't have any side-effects on H2 and PostrgreSQL, which are officially supported in OS).
And thanks for highlighting the issue.

**Comment by cxyzhang0** [comment]
@Quiark That would be a good idea.  The problem is I don't have access to the Enterprise code.  Any help would be greatly appreciated.

**Comment by szymonsztuka** [comment]
@Quiark the fix done by @cxyzhang0  is merged to master https://github.com/corda/corda/commit/d2446be69e71d353679c37115cec7f75c20f599e

**Comment by szymonsztuka** [comment]
Closing, the code is merged and will be release with the next major Corda release.
