### ISSUE TITLE
Node configuration logging exposes secrets

### ISSUE THREAD

**Issue by bret540** [corda/corda#3378]
Currently in ConfigUtilities.kt an info logging statement (line 38 in 3.1) spits out the entire node configuration which can contain secrets.  This is bad for enterprise as logs are routinely scrapped and analyzed for leaks that could expose entry points for hackers (especially if logs are being sent to cloud providers).

A few options that come to mind:

1)  Remove all secrets in node configuration files.  Disadvantage is this does not prevent human error and shifts the responsibility to the end users of Corda.

2)  Remove logging statement.  Disadvantage is that someone could log it again in the future.

3)  Code masking logic into configuration.  Disadvantage is the time it takes to implement such a feature and future proofing so new secrets would also be masked.

Thoughts?

**Comment by mikehearn** [comment]
I think this was changed already. Now it only prints out the config file in devMode (see NodeStartup.kt:90). But this change hasn't been released yet - it's on master.
