### ISSUE TITLE
NetworkMapClient throws a NullPointerException when trying to publish a NodeInfo where party has been registered before with a different public key

### ISSUE THREAD

**Issue by dazraf** [corda/corda#3442]
The `NetworkMap` [specification](https://docs.corda.net/network-map.html) does not state the expected behaviour when a node attempts to publish its `NodeInfo` in the case where its Party name has already been published with a _different_ public key. 

Technically the NM should reject a publication request under these circumstances as it could be an impersonation attack or a misconfigured node.

Currently, if the NM fails the request, the `NetworkMapClient` fails with a `NullPointerException` which is not helpful in debugging the cause of the failure.

Recommendation:
1. Either clarify the semantics of the NM to validate the existing behaviour.
2. Amend the spec and `NetworkMapClient` implementation to provide a more meaningful error.

**Comment by joeldudleyr3** [comment]
Tracked here: https://github.com/corda/corda/issues/3442.

**Comment by davidrapacchiale** [comment]
Closing this issue as it is related to an old version of the software. Either not relevant any longer, or fixed elsewhere. Please do reopen if still relevant
