### ISSUE TITLE
Release M8.2 - Exception in openAttachment

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#347]
Exception in RPC openAttachment:

rpc.dispatch - Failed to respond to inbound RPC openAttachment
 com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: net.corda.node.services.persistence.NodeAttachmentService$HashCheckingStream
Note: To register this class use: kryo.register(net.corda.node.services.persistence.NodeAttachmentService$HashCheckingStream.

**Comment by mikehearn** [comment]
@rick-r3 Is this changed at all by your Kryo changes? HashCheckingStream is an InputStream, but Kryo doesn't what to know. Does it need to be annotated anyway, will it do the right thing or will Kryo fail to match against the proper serialiser?

**Comment by Quiark** [comment]
It seems that custom stream serializer is registered only for `BufferedInputStream`(in `DefaultKryoCustomizer.kt` which `HashCheckingStream` is not.

**Comment by Clintonio** [comment]
@kchalkias Would you have time to look into this one?

**Comment by kchalkias** [comment]
@Clintonio sure, I will deal with it; I had another similar issue as well.

**Comment by kchalkias** [comment]
resolved in [#471](https://github.com/corda/corda/pull/471)
