### ISSUE TITLE
PageSpecification is not taken into account with VaultCustomQueryCriteria

### ISSUE THREAD

**Issue by lankydan** [corda/corda#3520]
version: 3.1 OS

The following code does not take into account the `PageSpecification` that has been included as part of the query. `proxy` is a `CordaRPCOps` instance.
```kotlin
val sum = builder {
  SecuritySchema.PersistentSecurityState::amount.sum(
     groupByColumns = listOf(SecuritySchema.PersistentSecurityState::name),
     orderBy = Sort.Direction.DESC
  )
}
val result = proxy.vaultQueryBy<FungibleAsset<Security>>(
  QueryCriteria.VaultCustomQueryCriteria(sum),
  PageSpecification(pageNumber = 1, pageSize = maxResultCount)
)
```
This is causing it to fail due to the number of result returned, where it then asks for a page spec to be added...

If the following code is written instead
```kotlin
val result = proxy.vaultQueryBy<FungibleAsset<Security>>(
  QueryCriteria.FungibleAssetQueryCriteria(),
  PageSpecification(pageNumber = 1, pageSize = maxResultCount)
)
```
The `PageSpecification` is taken into account and limits the returned records.

**Comment by joeldudleyr3** [comment]
Thanks Dan. Tracked as https://r3-cev.atlassian.net/browse/CORDA-1736.

**Comment by lankydan** [comment]
mmm after playing around with this again, it seems to be working. Not sure if I've subtly changed some of my code or if I my code somehow didnt compile in my changes at the time... No matter what I do I cant replicate it again.
