### ISSUE TITLE
IdentitySyncFlow.Send primary constructor requires a ProgressTracker but the secondary constructor does not

### ISSUE THREAD

**Issue by lankydan** [corda/corda#3522]
version: 3.1 OS

The `IdentitySyncFlow.Send` class consists of `Set<FlowSession>`, `WireTransaction` and a `ProgressTracker`. The main constructor requires all these values be set.

The secondary constructor on the other hand, only requires a single `FlowSession` and a `WireTransaction`. The session is converted to a set and a default `ProgressTracker` is created.

Should the main constructor have a default value for it's `tracker` property as well? Since means the user must create a `ProgressTracker` even if they have no intent to use one.
```kotlin
class Send(val otherSideSessions: Set<FlowSession>,
               val tx: WireTransaction,
               // the user of this flow must define the tracker themselves to pass in multiple sessions
               override val progressTracker: ProgressTracker) : FlowLogic<Unit>() {
        // this constructor creates a ProgressTracker via the tracker() function
        constructor(otherSide: FlowSession, tx: WireTransaction) : this(setOf(otherSide), tx, tracker())
```

**Comment by joeldudleyr3** [comment]
That sounds like a good idea. After adding a default value for the main constructor's `tracker` property, you would also want to add the `@JvmOverloads` annotation so that the constructor with a default value could be used from Java.

Would you be interested in adding this?

**Comment by lankydan** [comment]
can do, or can be marked as good first issue i guess. Very easy change 👍

**Comment by joeldudleyr3** [comment]
Yeah, maybe we can leave it to a first-timer :)

**Comment by lankydan** [comment]
ill pick it up if no1 has done it within the next week or so 😛

**Comment by joeldudleyr3** [comment]
Find a colleague who knows a bit about Corda and make them do it 😄

**Comment by nsubscribe2307** [comment]
I would like to work on this one. This will be my first time contributing to a public repo. How do I get it asssigned to me ?

**Comment by nelaturuk** [comment]
I would like to work on this one. This will be my first time contributing to a public repo. How do I get it asssigned to me ?

**Comment by joeldudleyr3** [comment]
It's assigned to you. Let us know if you need help.

**Comment by nelaturuk** [comment]
Great thanks.
