### ISSUE TITLE
API cleanup: rename StateAndRef.ref.txhash to id to reflect switch to Merkle trees

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#363]
The current name is confusing because it implies it's a hash of the entire tx bits, but it's actually not anymore.

**Comment by allenQBE** [comment]
Hi! I'd like to help contribute to the project and was wondering if this is still something worthwhile to work on. Assuming it wouldn't take anything more than just a refactoring and testing. If not, if there are other low-level issues to tackle instead, that'd be great!

**Comment by mikehearn** [comment]
@kchalkias 

Hi! Thanks for volunteering! Kostas has been doing some work in this space, but I'm not sure if he made this change or not. If not, it'd be a great place to start! You'd want to:

1. Create a feature branch
2. Use IntelliJ to rename the field (perhaps propose a new name here first)
3. Then go back and re-add the old name as a deprecated field, so older code continues to compile with warnings. If you search the codebase for `@Deprecated` you can see how to use the Kotlin `ReplaceWith` feature which assists in automatically upgrading code across simple renames.

**Comment by kchalkias** [comment]
Hi allenQBE,
I personally didn't touch `txhash` in my recent pull requests and thus you are free to refactor this one.
It seems there are currently ~75 usages, so as Mike suggested use Intellij's rename functionality to ensure you don't miss something.

**Comment by allenQBE** [comment]
Would replacing ```txhash``` with ```id```  or ```txstate``` work? ```txid``` seems to be getting heavy usage in other classes, so that also is a possibility if continuity is a priority.

**Comment by kchalkias** [comment]
Thank you allenQBE,
`txstate` may be misleading, but you are right that we should be better stay with `txId` (uppercase I) as it's the most commonly used term for transaction IDs in our code-base. As part of this PR, I suggest we also rename every `txid` (lowecase) to uppercase for consistency.

**Comment by allenQBE** [comment]
@mikehearn 
Would you like the deprecated message to say something along the lines of "txHash is now txId, replacing with old value to compile"?

**Comment by joeldudleyr3** [comment]
This can no longer be changed due to the API stability commitments.
