### ISSUE TITLE
Cannot use TestIdentities with same organization name in net.corda.testing.driver.Driver

### ISSUE THREAD

**Issue by marioschlipf** [corda/corda#3646]
We are using Corda's net.corda.testing.driver.Driver to write integration tests for RPC calls to Corda.

A simple driver setup looks as follows, similar to how it is done in the docs (https://docs.corda.net/tutorial-clientrpc-api.html):

```
class DriverBasedTests {
    private val bankA = TestIdentity(DUMMY_BANK_A_NAME)
    private val bankB = TestIdentity(DUMMY_BANK_B_NAME)
    private val custA = TestIdentity(DUMMY_CUSTODIAN_NAME)
    private val notA = TestIdentity(CordaX500Name(commonName = "Notary", organisation = "R3CEV", locality = "New York", country = "US"))
    private val regA = TestIdentity(CordaX500Name(commonName = "Regulator", organisation = "R3CEV", locality = "London", country = "UK"))

    @Test
    fun `test1`() {
        driver(DriverParameters(
                isDebug = true,
                startNodesInProcess = true,
                notarySpecs = listOf(NotarySpec(notA.name)),
                extraCordappPackagesToScan = listOf("com.my.cordapp"))) {

            val testUser = User("user", "password", permissions = setOf("ALL"))
            startNode(providedName = bankA.name, rpcUsers = listOf(testUser))
            startNode(providedName = bankB.name, rpcUsers = listOf(testUser))
            startNode(providedName = custA.name, rpcUsers = listOf(testUser))
            startNode(providedName = regA.name, rpcUsers = listOf(testUser))
            startNode(providedName = notA.name, rpcUsers = listOf(testUser))
   
            // Test code here...
        }
}
```

This code will throw an exception with the following error (shortened):

> java.nio.file.FileAlreadyExistsException: /home/mario/Projects/test/build/20180718-125046.625/R3CEV/nodeInfo-0A3B9D27E0430997798048D3ED6233A5FEA0A2BD868C1152A608DFE48B491410
> 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88) ~[?:1.8.0_171]
> 	// shortened...
> 	Suppressed: net.corda.node.internal.ConfigurationException: The name 'CN=Regulator, O=R3CEV, L=New York, C=US' for identity doesn't match what's in the key store: CN=Notary, O=R3CEV, L=New York, C=US

We had a hard time debugging this error until we found out that the issue was that the Notary and the Regulator (see above) had the same organization name. Because Corda is putting the nodes into directories that are named after the organization, it puts the notary and regulator node into the same directory which causes errors.

I am not sure if having two nodes with the same organization name is something that **should** be supported in testing environments (why not?), but if it is not supported, an exception should be thrown clearly indicating what is happening.

Thanks in advance,
Mario

**Comment by joeldudleyr3** [comment]
Thanks. Flagged here: https://r3-cev.atlassian.net/browse/CORDA-1837.

**Comment by lankydan** [comment]
im on the case 👮

**Comment by lankydan** [comment]
PR [https://github.com/corda/corda/pull/3740](https://github.com/corda/corda/pull/3740) created
