### ISSUE TITLE
Corda 3.2 missing Jackson deserialisation of SecureHash

### ISSUE THREAD

**Issue by lankydan** [corda/corda#3681]
Corda 3.2 seems to be missing Jackson deserialisation for `SecureHash`. `SecureHash.SHA256` does have serialisation and deserialisation but that does not seem to be the base for `SecureHash`. 

Corda 3.1 did have serialisation / deserialisation for `SecureHash`.

Currently I have resolved my issue by adding the following custom Mixin.
```kotlin
@JsonDeserialize(using = JacksonSupport.SecureHashDeserializer::class)
abstract class SecureHashMixin
```
This is a copy and paste from `CordaModules`'s `SecureHashSHA256Mixin`, minus the to string serialiser.

**Comment by joeldudleyr3** [comment]
Thanks. Tracked as https://r3-cev.atlassian.net/browse/CORDA-1846.

**Comment by lankydan** [comment]
looking at the code in master it looks like this has already been fixed in commit -> CORDA-1383: Cleaned up the JSON format of WireTransaction and SignedTransaction (#3248)

**Comment by joeldudleyr3** [comment]
Thanks :)
