### ISSUE TITLE
Occasional startup failure when the network map node is started in parallel with others.

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#37]
If we start up a local network "network map", "node a", then it works reliably. The other way around sometimes works and sometimes doesn't - node a hangs waiting for the network map registration to complete. It's meant to work, so the runnodes script doesn't impose any ordering on startup and it ends up being a race as all nodes start in parallel.

I suspect something in the network map service is taking messages off the queue and then dropping them on the floor during startup. As the node will try connect/delivery in the background, the moment the network map node starts it will be sent queued messages.

**Comment by patrickkuo** [comment]
Here is a summary of the problem:

**Symptoms:**
Nodes will not startup except the node running the network map service.

**How to reproduce the problem:**
Setup: Node A, Node B, Notary(with Network Map Service)
There are 2 ways to reproduce the problem. 

1. Startup the nodes in this sequence quickly (node A, node B, Notary), sometime Node A and Node B will fail to start.

1. Startup all the node normally (Notary -> NodeA -> Node B) and allow time between each startup.
Nodes should start without any problem. Now shutdown all nodes and start them up again one by one. Node A and Node B will no longer be able to connect to the Notary.

**Workaround:**
Remove artemis folder and persistence.mv.db from the node hosting the network map service and restart the nodes will fix the problem.

**Comment by patrickkuo** [comment]
Found the bug!

In `ArtemisMessagingServer` we add a call back handler to the artemis server to create bridges for the queues. However the handler registration happen after the queues restoration, so all the existing queue won't have a bridge after server restart.

The fixes is in this branch, https://github.com/corda/corda/tree/pat-node-startup-fix

Will raise a PR after written a unit test for this.

**Comment by patrickkuo** [comment]
The fix for this issue has been merged  into master.
