### ISSUE TITLE
Public key interfaces being converted during conversion to wire transaction

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3703]
In Corda 3.2:

1. Create a state includes a public key field of type Sun EC
2. Create an instance of this state and add it to a transaction builder
3. Convert the transaction builder to a wire transaction
4. Public key field in the state is now of type Bouncy Castle EC

See here to repro: https://github.com/fguttridge/corda_publickey_problem_repro/blob/master/cordapp/src/test/kotlin/com/template/ContractTests.kt.

**Comment by joeldudleyr3** [comment]
Thanks Francis. Raised as a bug ticket here: https://r3-cev.atlassian.net/browse/CORDA-1853.

**Comment by davidrapacchiale** [comment]
Closing this issue as it is related to an old version of the software. Either not relevant any longer, or fixed elsewhere. Please do reopen if still relevant
