### ISSUE TITLE
Add custom serialiser for Logger

### ISSUE THREAD

**Issue by rick-r3** [corda/corda#371]
We are capturing the Logger on the stack of checkpointed flows occasionally.  If can be difficult to avoid, and so we should have a custom serialiser for Logger that prevents the actual Logger implementation from being serialised.

This was discovered when using logback, since whilst the log4j Logger is serialisable, the logback one isn't.

**Comment by kchalkias** [comment]
fixed in [#373](https://github.com/corda/corda/pull/373)
