### ISSUE TITLE
Cannot use default ProgressTracker when overriding SignTransactionFlow from Java

### ISSUE THREAD

**Issue by Sphar-io** [corda/corda#3725]
On Corda 3.2, I am writing a Java flow, and overriding both `CollectSignaturesFlow` and `SignTransactionFlow`. 

When I call the `CollectSignaturesFlow` constructor, I do not have to provide a `ProgressTracker` argument - the `@JvmOverloads` annotation means the default parameter value will be used. 

Similarly, `SignTransactionFlow` has a default parameter for a ProgressTracker. However, its constructor is missing the overload annotation, which means that from Java, you **must** provide a progress tracker. 

With the annotation missing, Java flows can't use the default parameter. 
https://github.com/corda/corda/blob/d027b5b8f2bb00ef7f39d6760b658ccc4c165b43/core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt#L64
vs.
https://github.com/corda/corda/blob/d027b5b8f2bb00ef7f39d6760b658ccc4c165b43/core/src/main/kotlin/net/corda/core/flows/CollectSignaturesFlow.kt#L198-L199

## Steps to reproduce:
```
public SignedTransaction call() throws FlowException {
	class SignTxFlow extends SignTransactionFlow{

		private SignTxFlow(FlowSession flowSession){
			super(flowSession);
		}

		@Override
		protected void checkTransaction(SignedTransaction stx){
			requireThat(req -> {
				ContractState output = stx.getTx().getOutputs().get(0).getData();
				req.using("This must be an IOU transaction", output instanceof IOUState);
				return null;
			});
		}
	}
	return subFlow(new SignTxFlow(flowSession));
}
```

**Comment by joeldudleyr3** [comment]
Thanks :) Can you open a PR to add it?
