### ISSUE TITLE
Improve startup exception/log handling

### ISSUE THREAD

**Issue by remmeier** [corda/corda#3772]
Using current master branch (4.0 snapshot)

Various exceptions on startup currently get suppressed, even if DEBUG log level is enabled from the command line. For example:

```
  [ERROR] 08:45:47+0000 [main] internal.Node.validateKeyStore - IO exception while trying to validate keystore
 [ERROR] 08:45:47+0000 [main] internal.Node.run - Exception during node startup 
```
The command line parameters are `--log-to-console` and  `--logging-level=DEBUG`. 
After those two lines, no further lines are provided.

An other example would when setting the H2 address to 0.0.0.0 while omitting to set a password. Or when providing an illegal database configuration and corda is no longer able to connect.

**Comment by joeldudleyr3** [comment]
Thanks. Tracked here: https://r3-cev.atlassian.net/browse/CORDA-1897.
