### ISSUE TITLE
improve attachment download the characters format

### ISSUE THREAD

**Issue by Hart199** [corda/corda#3786]
With utf-8 support for language internationalization, format non-uniform characters by showing to user nation.
User uploads the attachment with nation language to use Corda web-API,  but that has in-correct code format. 

I get 403 error to pull request the code as adding a line code in DataUploadServlet class.  

code:  
upload.headerEncoding = "UTF-8"

**Comment by joeldudleyr3** [comment]
@Hart199 I don't understand what you're proposing. Are you saying you want to modify the Corda Webserver code to have a header to accept UTF-8?

**Comment by Hart199** [comment]
Hi Joe, if you upload a file it content like Chinese or other country characters in zip name, user will didn't get download. so I add that line code can avoid this issue. Encode UTF-8 should be servlet level. only in http header will not work.

**Comment by nargas-ritu** [comment]
Webserver is deprecated. Hence closing the ticket
