### ISSUE TITLE
Inaccuracy in docs for creating nodes with Docker

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3799]
See https://docs.corda.net/head/generating-a-node.html. It refers to a `deployNodes` task of type Dockerform in the IRS Demo. The task is actually called `prepareDockerNodes`.

Tracked in JIRA here: https://r3-cev.atlassian.net/browse/CORDA-1646.

**Comment by arsalankhalid** [comment]
Is this still available, I'm happy to take this on?

**Comment by joeldudleyr3** [comment]
@arsalankhalid I don't think so unfortunately (fortunately?). The master branch of the docs has already been updated to documented the new official Corda Docker image. I'll close this.
