### ISSUE TITLE
Explorer from Demobench on Notary node: no `myIdentity` in `Network` view

### ISSUE THREAD

**Issue by joeldudley** [corda/corda#3801]
1. Start Demobench
2. From DemoBench, run the Explorer from the Notary node
3. Go to the `Network` view
4. There is nothing in `My identity` pane, and the map isn't centered on the node.

Tracked in JIRA here: https://r3-cev.atlassian.net/browse/CORDA-1479.

**Comment by nargas-ritu** [comment]
Demo-bench deprecated. Closing the ticket
