### ISSUE TITLE
FR: Check Java version on node start-up and abort if unsupported

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3803]
Corda only supports Oracle JDK 8 JVM, with a minimum supported version of 8u171 (see https://docs.corda.net/getting-set-up.html#software-requirements).

However, no check is currently performed at start-up, and using the wrong Java version often leads to opaque error messages.

The Java version should be checked when the node starts up.

**Comment by opticyclic** [comment]
The documentation says "JVM implementations other than Oracle JDK 8 are not actively supported. However, if you do choose to use OpenJDK, you will also need to install OpenJFX".

That means that the code should work with OpenJDK if you are happy to not have support.
The Azure templates have Azul Zulu as the runtime and not Oracle.

Checking for the Java version on startup or vendor isn't the right fix here.

**Comment by lankydan** [comment]
fair point, ill revert that commit
