### ISSUE TITLE
FR: Support for case-insensitive vault queries

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3804]
The vault query API does not support comparing strings in a case-insensitive way. For example, the following query will be case-sensitive:

```
searchCriteria = builder { 
    BondContract.BondEntity::customerName.`in`(listOf(name1, name2))
}
```

The vault query API should be extended to allow case-insensitive vault queries.

**Comment by lankydan** [comment]
I got this 👍

**Comment by joeldudleyr3** [comment]
Fixed :)
