### ISSUE TITLE
FR: Extend Dockerform to allow configuration of the SSHD port

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3805]
The [Dockerform task](https://docs.corda.net/head/generating-a-node.html#the-dockerform-task) does not currently support the `sshdPort` configuration option (supported by regular Cordform) that allows the node shell to be enabled on the Dockerised node.

This configuration option should be added.

**Comment by arsalankhalid** [comment]
Is this still available @joeldudleyr3 ? I'm happy to give it a look

**Comment by joeldudleyr3** [comment]
@arsalankhalid Please do - here's the latest version: https://github.com/corda/corda-gradle-plugins/blob/master/cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt.

**Comment by roastario** [comment]
Dockerform is deprecated. Please use the official docker images.
