### ISSUE TITLE
Update docs to match kotlin template

### ISSUE THREAD

**Issue by nicktombeur** [corda/corda#3806]
The Hello World tutorials are not matching the kotlin template anymore.

**Documentation** (templateContract.kt):
`const val TEMPLATE_CONTRACT_ID = "com.template.TemplateContract"`

**Template** (StatesAndContracts.kt):
`
companion object {
    val ID = "com.template.TemplateContract"
}
`

_**Side note:**_
Change ID to a const in the kotlin template?
`
companion object {
    const val ID = "com.template.TemplateContract"
}
`

**Comment by joeldudleyr3** [comment]
Thanks. Addressed by https://github.com/corda/corda/pull/4007.

**Comment by Tondi007** [comment]
Im trying to run Hello World using the Kotlin Template and I get an error: Unresolved reference: TEMPLATE_CONTRACT_ID. It points to this line of code: 
 val txBuilder = TransactionBuilder(notary = notary)
                .addOutputState(outputState, TEMPLATE_CONTRACT_ID)
                .addCommand(cmd)

How do I resolve this? 
Thanks.

**Comment by joeldudleyr3** [comment]
That should be `TemplateContract.ID`, not `TEMPLATE_CONTRACT_ID`. Updating the docs now. Apologies!

**Comment by mjdacs** [comment]
Looks like the enterprise docs still need the update.

https://docs.corda.r3.com/hello-world-flow.html
