### ISSUE TITLE
CordaRPCOps.uploadAttachmentWithMetadata() throws IllegalArgumentException

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3807]
In Corda 3.2, calling `CordaRPCOps.uploadAttachmentWithMetadata()` throws an exception:

`java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.corda.node.internal.SecureCordaRPCOps.uploadAttachmentWithMetadata, parameter uploader`

Even if you pass a string instead of `null` as the `uploader`.

**Comment by joeldudleyr3** [comment]
Tracked here: https://r3-cev.atlassian.net/browse/CORDA-1909.

**Comment by Koshub** [comment]
Confirmed

**Comment by lankydan** [comment]
`SecureCordaRPCOps`doesnt seem to exist in master anymore (I'm not a wizard with git so i cant find where it was deleted). Tested the version in `CordaRPCOpsImpl` and it worked fine.

Can we accept that this has been resolved in a way (by it being removed previously)?

I can also add a test around `uploadAttachmentWithMetadata` to confirm that this is the case as there doesnt seem to be one at the moment.

**Comment by Koshub** [comment]
@lankydan will the master be released to some of 3.2.x version?

**Comment by lankydan** [comment]
I'll pick it up this weekend if I can

**Comment by lankydan** [comment]
totally forgot about this :) added some tests now

**Comment by lankydan** [comment]
@joel this can be closed 👍
