### ISSUE TITLE
Corda 3.2 publishes wrong Maven meta data to the maven central repository preventing maven build

### ISSUE THREAD

**Issue by cfries** [corda/corda#3813]
Corda 3.2 published/publishes wrong Maven meta data to the maven central repository for `corda-webserver-impl`. This prevents projects defining a dependency to corda-webserver-impl from being build by Maven. Gradle ignores the issue, hence the issue is not visible when using Gradle.
The maven build fails with Failure to find org.jolokia:jolokia-war:jar:1.6.0 in https://repo.maven.apache.org/maven2 - simple example to reproduce the issue at can be found at the end.

Note: the current master branch does not have this issue, because the dependency has been removed in a different PR (however, for a different reason). The issue exists on several release-3.x branches.

### Details

The maven pom of corda-webserver-impl in maven central specifies (in the corda-webserver-impl.pom) a depency to
```
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-war</artifactId>
			<version>1.6.0</version>
		</dependency>
Since the type attribute is left out, this is equivalent to
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-war</artifactId>
			<version>1.6.0</version>
			<type>jar</type>
		</dependency>
```
However, `jolokia-war` ist not published as a JAR, it is published as a WAR and the correct dependency reads:
```
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-war</artifactId>
			<version>1.6.0</version>
			<type>war</type>
		</dependency>
```

### Workaround

To get Corda being build by Maven a workaround is given by

1. Explicitly declare a dependency to `corda-webserver-impl`

2. Within the dependency to `corda-webserver-impl`  use `exclude` to exlcude jolokia-war.

3. Explicitly declare a dependency to `jolokia-war` using the correct type.

That is, add the following to you `pom.xml`
```
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-war</artifactId>
			<version>1.6.0</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>net.corda</groupId>
			<artifactId>corda-webserver-impl</artifactId>
			<version>3.2-corda</version>
			<exclusions>
				<exclusion>
					<groupId>org.jolokia</groupId>
					<artifactId>jolokia-war</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

To fix the issue you need one may consider to replace
 `compile "org.jolokia:jolokia-war:$jolokia_version"`
by
  `compile "org.jolokia:jolokia-core:${jolokia_version}"`
in the `gradle.build` file.

I will push a pull request with this.

### Minimal Example reproducing the Issue

To reproduce the issue create an empty directory with the following `pom.xml`, then run man

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.christianfries</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>


	<repositories>
		<repository>
			<id>maven-central</id>
			<name>Maven Central</name>
			<url>https://repo.maven.apache.org/maven2</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>net.corda</groupId>
			<artifactId>corda</artifactId>
			<version>3.2-corda</version>
		</dependency>
		<dependency>
			<groupId>net.corda</groupId>
			<artifactId>corda-core</artifactId>
			<version>3.2-corda</version>
		</dependency>
		<dependency>
			<groupId>net.corda</groupId>
			<artifactId>corda-webserver</artifactId>
			<version>3.2-corda</version>
		</dependency>
		<dependency>
			<groupId>net.corda</groupId>
			<artifactId>corda-webserver-impl</artifactId>
			<version>3.2-corda</version>
		</dependency>
	</dependencies>

	<build>
		<defaultGoal>clean install</defaultGoal>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by joeldudleyr3** [comment]
@cfries Would you be able to PR this fix back into Corda?

**Comment by cfries** [comment]
Hi @joeldudleyr3 - done. Note that the current master branch and the V3 backport branch does not have the issue. But the current V3 release branch and some others have the issue.
I wasn't sure about which branch I should commit too...

**Comment by joeldudleyr3** [comment]
@cfries Ah sorry, I didn't realise. We don't modify release branches once they've been released for stability reasons, so we can't fix this on V3. It looks like this will be fixed in the next minor release.

I'll close this, but please flag up any other issues you encounter.
