### ISSUE TITLE
samples: IRS demo web cannot simulate future dates as expected

### ISSUE THREAD

**Issue by ooharawork** [corda/corda#3851]
[IRS demo](https://github.com/corda/corda/tree/master/samples/irs-demo) sample application is supposed to simulate future dates by increasing year/month/day, starting from the current date.
Actually, it shows always the same date ~~`January 1, 1901`~~ `December 1, 1901` that you cannot move date forward. 

## Steps To Reproduce

Reproduced on `master` branch so far but I believe other branches are affected as well.

1. Click `Create Deal`
2. Submit the deal with the default parameters
3. Click `Recent Deals`
4. Look at `Run fixings`
    * Expected: we should see the current date, e.g. `2018`, `8`, `27` for year, month and day.
    * Actual: we see ~~`1901`, `1`, `1`~~ `1901`, `12`, `1`.
5. Click Plus(`+`) button on on the right of Year
    * Expected: the Year will be increased, e.g. `2018` -> `2019` (or `1901` -> `1902`)
    * Actual: the year doesn't change

## Error Message

On BankA console, the following error is observed:

` Attempt to set demodate to 1902-12-01 but demodate is already 2018-08-27 and can only be updated with a later date {}`

Analysis: this `1902` is `1901+1`. ~~`12` would be off-by-one issue (handling months in either 1-12 or 0-11)~~ 

----
**Update:** Correction: January->December

**Comment by joeldudleyr3** [comment]
Tracked here: https://r3-cev.atlassian.net/browse/CORDA-2213.
