### ISSUE TITLE
Optionally include Corda internal fields on persisted data.

### ISSUE THREAD

**Issue by richardblocksure** [corda/corda#3864]
When using SQL to provide access to ledger data, the rows generated generally relate to a state. However, there is no way to determine (from the generated data) which states are still live. One workaround is to do a join from the target table back to the Corda `VAULT_STATES` table by `OUTPUT_INDEX` and `TRANSACTION_ID` and then filter where `CONSUMED_TIMESTAMP` is null. It would be useful if, when designing the schema, the `CONSUMED_TIMESTAMP` value could be included such that this join is no longer necessary.

**Comment by joeldudleyr3** [comment]
@richardblocksure Hey. Which database table are you referring to?

**Comment by richardblocksure** [comment]
The database table that is created via making a state queryable. It is possible to join back to the `VAULT_STATES` but by optionally having this on the generated table would mean one less join in queries.

**Comment by tudor-malene** [comment]
The VAULT_STATES table is the central point for "the state" of states.
So joining it to get that info is not a workaround. It's the intended usage.

What you're proposing is to denormalize the structure and also store the consumed flag in the queryable state.
In modern databases, joins shouldn't add any significant overhead, if the right indexes are in place.

**Comment by richardblocksure** [comment]
Happy to defer to you @tudor-malene , and yes I agree it is a denormalisation however, sometimes such denormalisations make practical usage more ... er.. practical. I do beg to differ regarding the join though - if it is the case that if "corda takes over the world", one is not going to want to lock the `VAULT_STATES` table (even if via optimised indices, no matter what level ANSI level locking is enabled) if you just need data from the generated table... After all, `VAULT_STATES` is going to contain every state for every application in a business or legal unit; which could be yuge. I also think that this could make integration one or two steps easier. The purist in me agrees with you, but the practicalist (?) does beg to differ.

**Comment by tudor-malene** [comment]
I definitely agree that this could be a good candidate when we'll attempt to optimise that area. But the impact needs to be measured. Otherwise it could just be a premature optimisation.
I'm sure denormalisation is a tool in the performance's team arsenal. 
cc: @rick-r3 

With the regards to practicality, Jpa and our vault query api abstract away the fact that there's a join in the background, so there is no impact on the code using this.

**Comment by mikehearn** [comment]
@tudor-malene This is also a usability issue though, no? The join is a bit annoying to do when writing SQL by hand.

**Comment by nargas-ritu** [comment]
Won't do.
