### ISSUE TITLE
FAQ link is dead in the docs site

### ISSUE THREAD

**Issue by louptheron** [corda/corda#3871]
Hi,

The _Frequently asked questions_ link from https://docs.corda.net/faq.html page is dead, as there is no more discourse forum.

**Comment by joeldudleyr3** [comment]
Thanks Loup. This is fixed on the master version of the docs (https://docs.corda.net/head/). These changes will be bought back with the next major release.

**Comment by florian-f** [comment]
https://docs.corda.net/faq.html still links to the 3.2 version of the docs that have the dead link

**Comment by joeldudleyr3** [comment]
@florian-f But how do you reach that page from the 4.0 docs? I think you can only get there from Google.
