### ISSUE TITLE
Dependency for bft-smart:library:master-v1.1-beta-g6215ec8-87 is failing 

### ISSUE THREAD

**Issue by anshulee** [corda/corda#3884]
On doing gradle sync on Cordapp-Example project ( or template) am getting a org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.bft-smart:library:master-v1.1-beta-g6215ec8-87.

When i hit https://jitpack.io/com/github/bft-smart/library/master-v1.1-beta-g6215ec8-87/library-master-v1.1-beta-g6215ec8-87.jar i get a "Build failed. See the log at jitpack.io" message. 

This dependency is failing since 30th August. Can we please update the dependency to another version?
https://jitpack.io/com/github/bft-smart/library/ ?

Pretty much stuck here so any guidance is appreciated.
Thanks
Anshulee

![buildfailed](https://user-images.githubusercontent.com/4685167/44979237-325b6c00-af8a-11e8-9707-79c525c82636.png)

![buildfail](https://user-images.githubusercontent.com/4685167/44979210-16f06100-af8a-11e8-95b0-28bb5cc77f82.png)

**Comment by lankydan** [comment]
in the meanwhile, if there is a lower version, you might be able to force gradle to use a different version of the library.

**Comment by anshulee** [comment]
Just did that with the following line in .....\cordapp-example\kotlin-source\build.gradle

 compile "com.github.bft-smart:library:library-master-v1.1-beta-g93fe541-124"

Its working with this version.

**Comment by mikehearn** [comment]
I worked with jitpack support to get this artifact back. Things should work better now.
