### ISSUE TITLE
Running the nodes on separate machines

### ISSUE THREAD

**Issue by raghurammullapudi44** [corda/corda#39]
i am trying to run the trader-demo nodes on three different machines.Notary node is succesfully started but the other nodes are not getting started.I had kept network mapping address for the node a and node b as the ip address of the machine where the  notary node was running and port on which the notary node is running.But only the notary node is started but the others nodes are not started.why?

node.conf of notary

```
artemisAddress="ipaddress of 1st machine:10002"
basedir=notary
extraAdvertisedServiceIds="corda.notary.validating"
myLegalName=Notary
nearestCity=London
rpcUsers=[]
webAddress="ipaddress of 1st machine:10003"
```
node.conf of nodea

```
artemisAddress="ipaddress of 2nd machine:10004"
basedir=nodea
extraAdvertisedServiceIds=""
myLegalName="Bank A"
nearestCity=London
networkMapAddress="ipaddress of 1st machine:10002"
rpcUsers=[]
webAddress="ipaddress of 2nd machine:10005"
```
node.conf of nodeb

```
artemisAddress="ipaddress of 3rd machine:10006"
basedir=nodeb
extraAdvertisedServiceIds=""
myLegalName="Bank B"
nearestCity="New York"
networkMapAddress="ipaddress of 1st machine:10002"
rpcUsers=[]
webAddress=ipaddress of 3rd machine:10007"
```

**Comment by patrickkuo** [comment]
it could be related to this problem https://github.com/corda/corda/issues/37

**Comment by joeldudleyr3** [comment]
We've done some tests, and have had no issues running the nodes on multiple machines on the same subnet. Here's what worked for us:

After deploying the nodes, navigate to the build folder (`kotlin/build/nodes` or `java/build/nodes`) and move some of the individual node folders to separate machines on the same subnet (e.g. using a USB key). It is important that no nodes end up on more than one machine, even the controller node. Each computer should also have a copy of `runnodes` and `runnodes.bat`.

 For example, you may end up with the following layout:
 * Machine 1: `controller`, `nodea`, `runnodes`, `runnodes.bat`
 * Machine 2: `nodeb`, `nodec`, `runnodes`, `runnodes.bat`
 
 You must now edit the configuration file for each node, including the controller. Open each node's config file (`[nodeName]/node.conf`), and make the following changes:

* Change the artemis address to the machine's ip address (e.g. `artemisAddress="10.18.0.166:10006"`)
 * Change the network map address to the machine's ip address as well (e.g. `networkMapAddress="10.18.0.166:10002"`) (please note that the controller will not have a network map address)

Each machine should now run it's nodes using `runnodes` or `runnodes.bat` files. Once they are up and running, the nodes should be able to place purchase orders among themselves in the same way as when they were running on the same machine.

**Comment by mikehearn** [comment]
Hi raghurammullapudi44, I'm going to close this issue. If you have further support requests please start a discussion in the forum:

http://discourse.corda.net/
