### ISSUE TITLE
corda-webserver logging level command line option has no affect on logging

### ISSUE THREAD

**Issue by pinkjersey** [corda/corda#3905]
The corda-webserver ignores this command line option. To recreate:

`java -jar corda-webserver.jar --log-to-console --logging-level ERROR`

The application should log less as the logging level is set to ERROR, yet it logs the same amount. Conversely setting the switch to TRACE should log more, but it doesn't.

**Comment by Clintonio** [comment]
Hello @pinkjersey 

Thank you for the bug report. After a brief look at the source for the webserver code it does appear that the logging level variable is not being used correctly.

**Comment by joeldudleyr3** [comment]
JIRA ticket here: https://r3-cev.atlassian.net/browse/CORDA-2060.
