### ISSUE TITLE
FR: initialiseSchema property couples corda node and cordapp ddl handling

### ISSUE THREAD

**Issue by remmeier** [corda/corda#3941]
Corda itself makes use of Liquibase. The cordapps make use of Hibernate DDL generation. Setting the database.initialiseSchema schema property only allows to enable/disable both together. There should rather be two properties that allow to configure the two separately, allowing to handle DDLs of cordapps outside of corda. For example:

- initialiseNodeSchema 
- initialiseCordappSchema

whereas initialiseSchema can continue two set both.

**Comment by joeldudleyr3** [comment]
@remmeier Would you be able to PR your fix back into the codebase? I've spoken to the DB guys and they're happy to implement your fix :)

**Comment by remmeier** [comment]
yes, sure, I should have time this week. After that two weeks on holidays.
