### ISSUE TITLE
Subscribers for Vault Track are notified before data being committed in database

### ISSUE THREAD

**Issue by nehalshah50** [corda/corda#3972]
I have two state A & B. I am executing a transaction which contains two outputs one for A and one for B. I am using CordaRPCClient from my Rest to track vault for stat A. My vault tracking observable has the map to query the vault for stat B whenever I see an update for stat A. What I have noticed that my query never finds latest on stat B. So it feels like subscribers for the vault track observables are being notified before the database commit happens. Following is the sample code:

```
data class UIViewStateA_StateB(val a: StateA, val b: StateB) 

..........

cordaRPCOps.vaultTrack(StateA::class.java)
        .updates
        .map { var b = cordaRPCOps.vaultQueryBy<StateB>.states.first().state.data
                UIViewStateA_StateB(it, b)
        }
```

**Comment by joeldudleyr3** [comment]
Thanks. Tracked here: https://r3-cev.atlassian.net/browse/CORDA-2056.
