### ISSUE TITLE
Explorer GUI aggregates transaction communications in the network view

### ISSUE THREAD

**Issue by ragmondo** [corda/corda#398]
This means that the following example is incorrectly rendered ( -> = sends / issues):
Bank -> A:  100 USD
A -> B : 50 USD 
A -> Bank : 50 USD
In the lowest transaction (when viewing the network as Bank) the transaction renders as also informing B. This is not the case on the ledger, but is due to the "fireBulletBetweenNodes" working on the aggregated map of communication, not the individual ones. As Bank resolves the transactions, it becomes informed of the A->B txn and includes that as parties in the rendered txn of A -> Bank.

**Comment by joeldudleyr3** [comment]
We have retired the "fireBulletBetweenNodes" animation, so I'm closing this for now.
