### ISSUE TITLE
Adding node to Raft cluster doesn't sync spent states

### ISSUE THREAD

**Issue by Quiark** [corda/corda#4016]
1. Deploy Raft nodes from notary-demo 
2. Launch `Alice Corp`, `Notary Service 0` and `Notary Service 1`
3. Launch the notarize demo to create 10 transactions
4. Launch `Notary Service 2`
5. Wait some time
6. Wait some more
7. ☕️ 
8. Notary Service 2's database `node_raft_committed_states` still doesn't contain all of the 10 transactions, just a subset

Expected behaviour: newly launched notary service 2 will fully sync and have all 10 transactions in its committed state database.

Looking into copycat's debug log it appears as if the algorithm is pretty happy about how the sync turned out and is not going to do any more syncing.

Tested on release-V3 as well as master.

Also note: it appears that snapshots are never done except on the very beginning, making that implementation pretty much unused.

**Comment by joeldudleyr3** [comment]
Thanks for flagging. Reported here: https://r3-cev.atlassian.net/browse/CORDA-2062.

**Comment by davidrapacchiale** [comment]
Issue closed as it has been tracked on Jira.
