### ISSUE TITLE
Cash will be locked if Flow suspends forever.

### ISSUE THREAD

**Issue by janisolekss** [corda/corda#4104]
Looks like case, when a Flow performs generateSpend and somewhere along the line suspends (for example waiting counterparty to sign, or some other sendAndReceive communication) and if the suspension is forever, then particular Cash will be softlocked in DB also forever.

There should be explicit programmatical way of "unsuspending" flow with some Exception or something similar.

**Comment by roastario** [comment]
Thanks for this @janisolekss - I will investigate re: chat on slack.

**Comment by janisolekss** [comment]
Because Cash uses ID from TranactionBuilder, it is possible to controle LockId used to lock. By default it is borrowed from the Flow, but it is possible to pass it explicitly in TransactionBuilder. In this case client can control the lockID, and in case of failure of flow to deliver, might use the same ID to call vaultService.softLockRelease() function to "free" the cash.
But I assume this might wreck the flow and logic along the line, if the original flow decides to resume.

**Comment by joeldudleyr3** [comment]
Tracked here: https://r3-cev.atlassian.net/browse/CORDA-2138.

**Comment by mikehearn** [comment]
It's possible to kill flows via RPC so an external watchdog can be created until flows are better able to control their own timeouts.

However it isn't really intended that flows suspend forever. That would normally indicate a bug.
