### ISSUE TITLE
MissingAttachmentRejection when trying to verify() a transaction built on 2 parties

### ISSUE THREAD

**Issue by foultre** [corda/corda#4108]
I issue an FxState from partyA which is a future fx cash exchange between partyB and partyC. (B sends USD to C and C sends EUR to B, A is informed and signer)
For the Settlement flow I build a transaction on 2 sides passing the txBuilder through flow to each node so they can exchange Cash states in diffrerent currencies. 
Then I add the FxState in inputState of the tx which consume it.

When I try to `transactionBuilder.verify(serviceHub)` I get this error 
`net.corda.core.contracts.TransactionVerificationException$MissingAttachmentRejection: Contract constraints failed, could not find attachment for: com.template.FxContract`

Workaround : `txBuilder.addAttachment(serviceHub.cordappProvider.getContractAttachmentID(FxContract.FX_CONTRACT_ID) as SecureHash)`

**Comment by tudor-malene** [comment]
Created: https://r3-cev.atlassian.net/browse/CORDA-2143

**Comment by josecoll** [comment]
@foultre Please can you confirm some additional information.

- What version of Corda are you running? 
- Do all 3 parties (A,B,C) have the same CorDapp.jar deployed (containing the same FxContract)?
- When Party A issues the FxFuture, do parties B and C receive a copy? (as participants)
   I assume they must as you then build a settlement transaction on Party B with that FxFuture state as an input.
- Is Party B is building the new settlement transaction and explicitly calling verify()? (and failing at this point of the flow; eg party C receives nothing)

**Comment by foultre** [comment]
- Corda open source 3.3
- yes
- yes
- yes
When doing the settlement I'm passing the txBuilder from B to C and C back to B. Then B try to verifie and fails.

**Comment by josecoll** [comment]
Just to clarify on the latter point, is your code explicitly calling` verify`, or are you delegating that to a standard core flow (Eg. `FinalityFlow`) ?

**Comment by foultre** [comment]
My code is explicitly calling `verify`

**Comment by josecoll** [comment]
Without revealing any IP can you send me a cleansed/stripped-down version of your CorDapp so I can verify the behaviour on Master (Corda 4 codebase is significantly different to OS 3.3).

**Comment by josecoll** [comment]
With regards to your workaround:
`txBuilder.addAttachment(serviceHub.cordappProvider.getContractAttachmentID(FxContract.FX_CONTRACT_ID) as SecureHash)`

- if you are constructing a new Txn then it is expected that you add attachments to be verified.
- if you have received the Txn over the wire from another participant, it is expected that the contents are preserved (eg. the attachment reference should be preserved from the original txn received from the sender). <=== is this the scenario you are describing?

**Comment by foultre** [comment]
Yes this is the scenario I'm describing. So this is normal behaviour ? I would think the hash of the Contract would be the same on all nodes.

**Comment by josecoll** [comment]
Yes - the scenario you are describing should work as-is.
Are you able to re-test this using OS master?

**Comment by tudor-malene** [comment]
Hi @foultre , is this issue still valid?

**Comment by davidrapacchiale** [comment]
Closing this issue as it is related to an old version of the software. Either not relevant any longer, or fixed elsewhere. Please do reopen this issue if is still a valid bug on the latest version of Corda OS
