### ISSUE TITLE
2 differents parties can't send each other cash in 2 currencies in 1 single tx

### ISSUE THREAD

**Issue by foultre** [corda/corda#4110]
This is because `Cash.verify()` checks that there is only one `Move` command in `verifyMoveCommand`: `val command = commands.requireSingleCommand<T>()` 

The `Cash.verify()` function groups inputs,outputs, and keys by Token but commands are not grouped:

```
for ((inputs, outputs, key) in groups) { 
...
verifyMoveCommand<Commands.Move>(inputs, tx.commands)
}

**Comment by joeldudleyr3** [comment]
@foultre Doesn't it work fine if you put in two sets of currencies, but only one `Move` command?

**Comment by foultre** [comment]
2 parties send different tokens so they each need a move command

**Comment by lankydan** [comment]
id like to pick this up 👍

**Comment by foultre** [comment]
dirty fix :
```
fun rebuildMoveCommand(txb:TransactionBuilder): TransactionBuilder {
    val moveCmds: List<Command<*>>  = txb.commands().filter{it.value is MoveCommand}
    val signersOfCashMoveCmd = mutableListOf<PublicKey>()
    for (elem in moveCmds){
        signersOfCashMoveCmd.addAll(elem.signers)
    }
    val moveCmd = Command(Cash().generateMoveCommand(), signersOfCashMoveCmd)
    val otherCmds  = txb.commands().filter{it.value !is MoveCommand}
    val allCmd  = otherCmds.plus(moveCmd)
    return TransactionBuilder(
            notary = txb.notary,
            inputs = ArrayList(txb.inputStates()),
            attachments = ArrayList(txb.attachments()),
            outputs = ArrayList(txb.outputStates()),
            commands = ArrayList(allCmd),
            window = null,
            privacySalt = PrivacySalt()
    )
}
```

**Comment by joeldudleyr3** [comment]
Thanks Remi. Flagged here: https://r3-cev.atlassian.net/browse/CORDA-2184.

**Comment by peterli-r3** [comment]
Hi foultre,

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
