### ISSUE TITLE
create notary api to enable extraction of notarised transactions

### ISSUE THREAD

**Issue by Bartman250** [corda/corda#4156]
To enable a uniform approach to extracting notarised transactions from a notary's vault regardless of the notary type. I propose a new notary api that enables notarised transactions to be extracted by date.
The full design proposal and whys and wherefores can be found [here](https://gist.github.com/Bartman250/9c98076cc69923a1f48dcfb3fb5dda57)

The api description is as follows:

### Api Input:

* lastTransactionTime
  This will extract all the notary transactions greater than equal to the input time which is specified in UTC time.
    Note: Instead of using transaction time, we did discuss using a sequence number but decided that 
this would be  more difficult to implemented, particularly in a BFT scenario. However, we are open to this approach if achievable.
  
### Api Outputs:

* transactionIdHash

   The hash of the transactionId is used here to prevent following of the transaction chain.
   
* transactionTime

   The UTC time of the transaction. This will be used by the consumers of the Api to track how far they have got - we would expect them
   to store the last transaction value in their own vaults or databases and then use this value to extract the next 'batch' of notarised transactions. 
   
* abstractParty
 
  The party that instigated the transaction, so that we know where to send the metering invoice.
  
  There is no need to identify the party by name here, unless it is required by the 'rules' of a notary cluster.

* transactionSignature
 
  The instigating node will use this to verify that it did actually create the transaction in the first instance.
  The current metering process checks that the transactionId is in its vault which works fine, but does give away the transaction tree
  to the notary - hence using the hash of the transactionId above.

* Transaction metadata - this is Key/Value map of optional data that can be used by metering services to charge appropriately for the transaction such as :
    - numberOfStates
    
      This gives the billing 'engine' a rough size of the transaction and potentially it may charge more for large transactions
      
    - Transaction Priority
    
      We may introduce notaries that can process transactions according to priority and be rewarded with higher transaction fees.
      
    - transactionType (i.e. is it a notary transfer)
        
      Notaries transfers can potentially be expensive and so the billing engine could charge more for these
    
    - numberOfStatesResolved
     
      In the case of validating notaries the number of states pulled in a notary transfer could have significant impact on the 
      notary and therefore be expensive.
      
    - retries
    
      It is possible that there will be duplicate transactions held in the notary as the result of transaction retries. 
      The billing service may choose to bill for these if there are excessive to prevent DDoS style behaviour.

     Note: We have also discussed having a list of all the signers of a transaction for clustered notaries, so that fees can be 
     selectively distributed to notaries that actually took part in the transaction. This idea has been dismissed as its quite heavyweight,
     and we'd have to wait for all signers slowing down notarisation.

**Comment by mikehearn** [comment]
Working on a response to Mark's email now.
