### ISSUE TITLE
Enable Node Blacklisting and Whitelisting

### ISSUE THREAD

**Issue by Bartman250** [corda/corda#4157]
This issue relates to the design proposal for enhancements to Corda to support metering which can be found [here](https://gist.github.com/Bartman250/9c98076cc69923a1f48dcfb3fb5dda57)

In order to prevent nodes from using you as a notary for free, we need to have a flexible mechanism to
    * blacklist - i.e. refuse transactions from certain nodes/parties if they are behaving badly
    * whitelist - i.e. only allow notarisation for a pre-approved list of nodes/parties 

Business networks may also want to control who connects to nodes in their network - so again blacklisting/whitelisting would also be a useful feature.

I propose that we add some new api calls to the service hub as follows:
```
addToBlackList(party : abstractParty)
removeFromBlackList(party : abstractParty)
addToWhiteList(party : abstractParty)
removeFromWhiteList(party : abstractParty)
```

If a party is blacklisted it will be rejected to perform any flow with the node.
If there is at least one party in the whitelist then only the parties in the whitelist will be able to perform flows on the node.
I don't know which services are best placed to put this feature yet - open to suggestions, but I would strongly suggest that this data is maintained in the vault as opposed to a config file - so that it is easily recoverable in HA scenarios.

**Comment by Bartman250** [comment]
@joeldudleyr3 Thanks for this - I'm not sure at what level this needs to be in the code as the check for the blacklist/whitelist needs to happen before a flow can be kicked off - so I assume somewhere deep in the messaging server - but if this can be implemented as a corda service then great.. I think I would prefer the data for this to be maintained in the database/vault - as then it benefits from all the lookup search and random access - i.e. for adding and removing parties from the list, which would be safer than rewriting a file.

**Comment by joeldudleyr3** [comment]
@Bartman250 You could still store this data in the database, or event store it as a state.

I guess the difference is that you don't want to write calls to `isPartyOnBlacklist` inside your flows (although this would be completely possible using a service or some state stored in your vault). Rather, you want the process to be automatic.

What's the reason for this? Just to make the notary/BNO/etc. code easier to write?

**Comment by Bartman250** [comment]
@joeldudleyr3 Basically this is a door policy for nodes and notaries. The scenario is that you have a compatibility zone with a large number of BNs and Notary pools. The CZ has a door policy but once you are in the zone you can use any notary and send transactions to any node - bit like getting a wristband for alton towers and being able to go on all the rides for free . For the BN you probably want to only connect to other people in the BN who have gone through some additional KYC - i.e you don't just want some random node sending you data - I just picked up this comment from Corda general chat as an example:

****** [6:37 AM] (7/11/2018)
how can I prevent receiving states (using `FinalityFlow`) created by parties outside my BN?

For notaries, I imagine there will be a number of notary pools who want to charge (by whatever means) for their services or at least only allow 'free' notarisation to particular nodes.
The Cordite Metering notaries require that the client nodes have the cordite libraries - so that we can send them invoices and they can pay for them - so we would like to be able to 'whitelist' the node before they start using the notaries. We also want to blacklist nodes if they haven't paid their bills.
We put blacklisting/whitelisting on a per flow basis and put it in every receiver (including the notary flows) which would make sense as you need to have some 'flow' that enables the client node to beg for forgiveness and take them off your blacklist. It seems sensible to put this functionality as common service that can be used by anyone. A Corda service would do the job initially, but it would be good to have this on the service hub and have the option of a blacklist/whitelist that works for all flows.
Sorry, a bit of a long and wordy explanation - I hope this makes some kind of sense.

**Comment by joeldudleyr3** [comment]
@Bartman250 Hey Mark, sorry for the delay. I just don't see what's gained by having this directly on the `ServiceHub`, as opposed to a standard `CordaService` nodes could install? The `CordaService` would behave in the same way, storing the whitelists/blacklists in the nodes' databases. Is the upside of putting it on `ServiceHub` that it comes by default and is slightly less onerous to invoke (one less dot operator)?

**Comment by mikehearn** [comment]
This looks quite a lot like the BNO membership service - the notion of being "in" or "out" is a part of that and the idea is, you call into it from the top of your (possibly subclassed) flows.

https://github.com/corda/corda-solutions/tree/master/bn-apps

I tend to agree that ServiceHub is probably not the right place to put this logic. The notion of 'blacklist' as separate from 'whitelist' is somewhat subtle - where do these lists come from? What exactly do they contain, and how are they updated?

From a core API perspective I think we'll want to solve these questions by just merging the BNO app. It answers all those questions.

**Comment by Bartman250** [comment]
Hello Mike,

Thanks for coming back on this.
Originally I thought that the blacklist/whitelist would be at a lower level than flows - i.e. deeper in the messaging layer, but then I realised that we need some flows for people to get on the whitelist and probably a flow to plead redemption from the blacklist.

My initial concern was around having whitelisting / blacklisting for a notary so that you could control who used it - my thinking that in a large compatibility zone with lots of BNs and Notaries - anyone can use any notary, and I’m pretty sure that notary owners would like some say in who uses their services.

For our Cordite DAOs, which are effectively decentralised BNs we would like to use blacklisting/whitelisting   - so I think this could be a common corda service that can be used by all kinds node types.

My definitions of these are as follows:
	whitelisting - you agree that a party can use some or all of the flows on your node - be it a notary or ‘business’ node.
	blacklisting - a node on your whitelist has not paid their bills or is behaving badly, so you cut them off for some of your flows except the ‘redemption’ flow where they can get themselves back on the whitelist.

So, my thinking is that this could be a common corda service that has and API that nodes can use control access to flows.
As I’m writing this, it’s starting to look like a permissions structure - but for the moment I don’t really need to go that far.

Cheers
Mark
