### ISSUE TITLE
Wrong URL on website

### ISSUE THREAD

**Issue by TAC911** [corda/corda#4162]
Not sure if this is the right place for opening the issue but I couldn't find a repository for the website.

### Error
Being on the following page on the corda.net website https://www.corda.net/discover/demobench.html the link to Develop in the top nav-bar leads to a non-existent page https://www.corda.net/discover/develop/index.html (404 Error). 

### Expected
The correct link would be https://www.corda.net/develop/index.html

**Comment by joeldudleyr3** [comment]
Fixed!
