### ISSUE TITLE
Persisting Parent and Child Tables to H2

### ISSUE THREAD

**Issue by rogersanick** [corda/corda#4193]
Hi there,

The following is a non-blocking (low-priority) bug. It has been recommended that this is potentially not best practice. I thought I should log it anyway for posterity's sake. 

**Issue**
I have created a simple iteration on the [Corda Bootcamp application](https://github.com/rogersanick/bootcamp-cordapp) that attempts to implement a parent and child relationship between states. The states themselves make no reference to each other but should generate parent and child tables that connect the associated data.

Each state has a class defined in TokenSchemaV1 that implements PersistentState. I am trying to persist the parent-child relationship in my database (H2) via @OneToMany and @ManyToOne JPA annotations. When I run a flow to issue parent and tokens I am presented with the following error. 

**Logs**
'E 11:26:09-0500 [Node thread-1] spi.SqlExceptionHelper.logExceptions - Table "TOKEN_CHILD_STATES" not found; SQL statement:
insert into token_child_states (amount, child proof, issuer, owner, persistentToken_output_index, persistentToken_transaction_id, output_index, transaction_id) values (?, ?, ?, ?, ?, ?, ?, ?) [42102-194] {}'

<img width="1318" alt="screen shot 2018-11-07 at 2 50 41 pm" src="https://user-images.githubusercontent.com/16504493/48157883-e6d18100-e29e-11e8-8a3a-0245d01c7dd4.png">

**Steps To Reproduce**
1. Deploy Nodes: `./gradlew clean deployNodes`;
2. Launch Nodes: `build/nodes/runNodes`;
3. Run TokenIssueFlow: `build/`

**Comment by rogersanick** [comment]
I was able to circumvent this issue by creating a Corda service that runs on startup to manually inserts the appropriate table. Unfortunately, the `@ManyToOne` and `@OneToMany` JPA annotations are not implementing a relationship between TokenStates and TokenChildStates inside of h2.

**Comment by joeldudleyr3** [comment]
Resolved here: https://stackoverflow.com/questions/53233011/corda-how-to-implement-hierarchical-relationships-between-state-data-persisted.
