### ISSUE TITLE
NodeVaultService.generateSpend() may have thread safe problem

### ISSUE THREAD

**Issue by bigstar119** [corda/corda#421]
hi,i read the NodeVaultService.generateSpend() `s source code found that the method may  have thread safe problem!!!  if muti thread execute generateSpend simultaneously , two tx may have the **same input**. 
if notary works good ,one tx will be refused..but to user and developer **a normal tx refused** ,this is confused.
i think this problem should be solved in the generateSpend() method.

**Comment by mikehearn** [comment]
Yup, this is fixed by PR #315 already which implements mutual exclusion at the database level, integrated with the flow framework. So it works across processes and restarts as well as across threads.
