### ISSUE TITLE
DemoBench: term widget doesn't support exotic unicode (like emoji) but is not detected as such

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#422]
On MacOS X we try to print emoji through the jediterm, although it's not supported. I suspect because we're keying off TERM_PROGRAM rather than TERM which will be inherited from the parent process environment when demobench is run from the command line.

**Comment by chrisr3** [comment]
In `net/corda/demobench/pty/R3Pty.kt`:
```kotlin
val environment = HashMap<String, String>(envs)
if (!UIUtil.isWindows) {
    environment["TERM"] = "xterm"
}
```
So DemoBench will set `TERM=xterm` before invoking JediTerm on MacOSX. Modifying `Emoji.kt` to examine `TERM` rather than `TERM_PROGRAM` therefore seems like a logical thing to do.

**Comment by mikehearn** [comment]
The problem is that on macOS:

mike@littlegreen /p/tmp> echo $TERM
xterm-256color

That's why it uses TERM_PROGRAM. The Apple terminal emulator reports itself as an xterm, I guess this is a variant of the `User-Agent: Mozilla/5.0 (not really, actually IE, not really actually Gecko, not really, actually Safari) SamsungTV` problem where everyone claims to be everyone who came before them for better compatibility.

So for now I'd suggest just setting TERM_PROGRAM to being "demobench"

**Comment by chrisr3** [comment]
`TERM_PROGRAM` looks specific to MacOSX, so maybe DemoBench could just remove it from the environment instead?

**Comment by mikehearn** [comment]
That also works but you never know, being able to identify we're in demobench might be useful and it's the same amount of code either way.

**Comment by chrisr3** [comment]
If `TERM_PROGRAM` is specific to MacOSX then I'd prefer not to use it to infer anything on other platforms. And if we ever need to recognise when we're in DemoBench then I'd also prefer to define that environment variable myself.

**Comment by chrisr3** [comment]
Fixed.
