### ISSUE TITLE
Network builder download link broken 

### ISSUE THREAD

**Issue by sd189** [corda/corda#4233]
The download link for network builder in 
https://github.com/corda/corda/blame/master/docs/source/network-builder.rst#L13
is broken.

**Comment by sd189** [comment]
I was trying 3.3 the latest but it doesn't exists 
3.2 is working fine

**Comment by sd189** [comment]
I was trying 3.3 the latest but it didn't work
3.2 is working fine

**Comment by opticyclic** [comment]
[V4 docs](https://docs.corda.net/releases/release-V4.0/network-builder.html) point to https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases/net/corda/corda-network-builder/4.0-corda/corda-network-builder-4.0-corda-executable.jar
 
However, the latest version in artifactory is 3.2
https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases/net/corda/corda-network-builder/

**Comment by jschmiede** [comment]
Any news about this???, it has been a while

**Comment by mikehearn** [comment]
Seems like there was an issue with shipping it and now there's some misalignment internally. Assigning to Cais to keep it on his radar whilst this gets sorted out.

@CaisR3

**Comment by joshtharakan** [comment]
If I am using CE 4, I cant use https://software.r3.com/artifactory/corda-releases/net/corda/corda-network-builder/3.2-corda/ right?

**Comment by rick-r3** [comment]
Can't find any reference to it in the docs, but the artefacts are still there under `/net/corda/corda-tools-network-builder/`
