### ISSUE TITLE
VaultService queryBy returned duplicate rows in StateMetadata

### ISSUE THREAD

**Issue by adrian-soon** [corda/corda#4267]
I have a snippet of code that looks something like this. 

```
val sortAttribute = SortAttribute.Custom(DocumentStateSchema.DocumentStateEntity::class.java, "documentEntryDate")
val sort = Sort.Direction.ASC
val sorting = Sort(listOf(Sort.SortColumn(sortAttribute, sort)))

val vaultCriteriaForReturn = QueryCriteria.VaultQueryCriteria(status = ALL, stateRefs = stateRefs)
val pageSpec = PageSpecification(pageNumber = pageNumber, pageSize = pageSize)
serviceHub.vaultService.queryBy<DocumentState>(vaultCriteriaForReturn, pageSpec, sorting)
```
When I compared the stateRefs against the database in postgres 9.6, I have 19 records, all unconsumed. I have specified the pageNumber = 1 pageSize = 10. I expected 10 distinct records to be returned. 

But the actual result returned from Vault.Page was 2 rows of stateAndRef. There was 10 counts of StateMetadata where 9 of them are duplicates. And totalRecordsAvailable as 19. 

I am currently on Corda Open Source 3.3.

**Comment by josecoll** [comment]
Thanks for raising this. 
Would you be able to send through a DDL/data export of your corda node vault tables (including any custom schema tables) and your `DocumentStateSchema.DocumentStateEntity` contract definition?
We can re-test this in-house, and advise next steps.

**Comment by adrian-soon** [comment]
Replicated on https://github.com/adrian-soon/obligation-cordapp/blob/9f0b9fe50dd35ae3ac33928abee4b4b51cdfc5e3/src/test/kotlin/ObligationTestTwo.kt#L43

This issue exist only on 3.3 and only when Sort is given in the param.

**Comment by sollecitom** [comment]
It will be fixed by https://github.com/corda/corda/pull/4366, currently open.

**Comment by joeldudleyr3** [comment]
Fixed.
