### ISSUE TITLE
Unable to evolve Enum by appending new fields.

### ISSUE THREAD

**Issue by marko-mets-gt** [corda/corda#4281]
When I have an enum serialized in the vault as this: 

```
@CordaSerializable
enum class MyEnum { A, B, C }
```
 and then in later version of my cordapp I update it to:
```
@CordaSerializationTransformEnumDefaults(
    CordaSerializationTransformEnumDefault("E", "C"),
    CordaSerializationTransformEnumDefault("D", "C")
)
@CordaSerializable
enum class MyEnum { A, B, C, D, E }
```
then I receive such exception: `java.io.NotSerializableException: Constants have been reordered, additions must be appended to the end`.

Looking at the unit tests it seems that they test this scenario:
Node A receives serialized enum from node B. This received enum has new constants added and the required annotation added and node A has only "old" enum constants. Node A is able to deserialize as required transforms are described in the deserialized enum from node B. That seems to work nicely.

My scenario is vice versa. I have some enum in my vault and I just want to add new constants to it. After adding new constants and the annotation and starting up the nodes I try to retrieve a state with that enum but I get an aforementioned exception.

Same issue when appending a single new value. And the same issue when appending same value without using `CordaSerializationTransformEnumDefaults` (only using `CordaSerializationTransformEnumDefault`)

Happened on V3.1

**Comment by marko-mets-gt** [comment]
Same issue in 3.3

**Comment by mikehearn** [comment]
Thanks for testing.

**Comment by marko-mets-gt** [comment]
I was trying to fix it myself and have come up with the following.
Here it is checked whether the enum constants have been reordered:
https://github.com/corda/corda/blob/release-V3.X/node-api/src/main/kotlin/net/corda/nodeapi/internal/serialization/amqp/EnumEvolutionSerializer.kt#L111

When replicating my use case then `ordinals` is bigger (it has new constants which are found on the classpath) than `serialisedOrds` (it contains only 'old' constants which were present during serialization). As it is bigger, then `filterNot` finds those new constants and assumes that something was reordered and throws. I added an additional check to apply `filterNot` on 'smaller' collection, like that:

```
if (ordinals.size <= serialisedOrds.size) {
    if (ordinals.filterNot { serialisedOrds[it.value] == it.key }.isNotEmpty()) {
        throw NotSerializableException("Constants have been reordered, additions must be appended to the end")
    }
} else {
    if (serialisedOrds.filterNot { ordinals[it.value] == it.key }.isNotEmpty()) {
        throw NotSerializableException("Constants have been reordered, additions must be appended to the end")
    }
}
```
With this fix all existing tests in `EnumEvolveTests` passed and I was able to perform the enum update which I described in the issue description. 

I know that in future versions of corda whole serialization will be overhauled but could you tell if this would be safe to do until I can start using newer corda?

**Comment by adamturski** [comment]
@distributedleetravis In our project we faced that issue too. Does above solution added by @marko-mets-gt can be used as a workaround?

**Comment by distributedleetravis** [comment]
It seems it will work (I have reproduced it in the new serialisation code, and it works there too); my only concern is to understand why the Corda documentation for enums currently states that new values _cannot_ be added: presumably this was a design decision made at some point, and I would like to understand the reason for it before recommending that this behaviour should be changed.

**Comment by joeldudleyr3** [comment]
@distributedleetravis @adamturski I've spoken to the serialisation people and the intent is definitely that enums can be serialised. My apologies for the mistake in the docs. I will address that.

**Comment by joeldudleyr3** [comment]
This looks like a bug. Raising a JIRA so this is picked up by bug triage here: https://r3-cev.atlassian.net/browse/CORDA-2264.

Marko proposed this test case to replicate the issue:

```
    // Version of the class as it was serialised
    //
    // enum class MyEnum { A, B, C }
    //
    // Version of the class as it's used in the test
     @CordaSerializationTransformEnumDefaults (
             CordaSerializationTransformEnumDefault("E", "C"),
             CordaSerializationTransformEnumDefault("D", "C")
     )
    enum class MyEnum { A, B, C, D, E}

    @Test
    fun evolveEnum() {
        val resource = "${javaClass.simpleName}.${testName()}"
        val sf = testDefaultFactory()

        data class C(val e: MyEnum)

        // Uncomment to re-generate test files
//         val so = SerializationOutput(sf)
//         File(URI("$localPath/$resource.A")).writeBytes(so.serialize(C(MyEnum.A)).bytes)
//         File(URI("$localPath/$resource.B")).writeBytes(so.serialize(C(MyEnum.B)).bytes)
//         File(URI("$localPath/$resource.C")).writeBytes(so.serialize(C(MyEnum.C)).bytes)

        val path1 = EvolvabilityTests::class.java.getResource("$resource.C")
        val path2 = EvolvabilityTests::class.java.getResource("$resource.B")
        val path3 = EvolvabilityTests::class.java.getResource("$resource.A")

        // fails here
        val obj1 = DeserializationInput(sf).deserialize(SerializedBytes<C>(File(path1.toURI()).readBytes()))
    }
```

**Comment by joeldudleyr3** [comment]
Fixed.
