### ISSUE TITLE
macOS Corda nodes won't start properly by ./build/nodes/runnodes

### ISSUE THREAD

**Issue by osancus** [corda/corda#4291]
When starting nodes using terminal command **'./build/nodes/runnodes'** on **macOS**, it starts opening tabs and running commands but fails to start a few of the Corda node servers or web servers of network randomly. Terminal seems to be trying to run multiple commands on one terminal. This problem was easily avoidable in previous versions by just clicking and focusing on the terminal app and not touching anything until the whole network starts. _This issue has been raised in past_ here: (https://r3-cev.atlassian.net/browse/CORDA-666?attachmentViewMode=gallery) but the solution proposed was to close the terminal app completely and re-run the command. Unfortunately, it is not working in my case.

<img width="1352" alt="screenshot 2018-11-23 at 18 07 59" src="https://user-images.githubusercontent.com/6899072/48952566-50ae8380-ef4b-11e8-8f11-4c0cf41eb399.png">

**Comment by joeldudleyr3** [comment]
@epicsol-inc Can you re-test this on master? We've done some work on the node start-up script since 3.3.

**Comment by Koshub** [comment]
Not sure if next info is related to current issue

Currently we are using corda 3.2 and `./build/nodes/runnodes` usually runs nodes correctly. But after reinstalling macOS and other apps like IntelliJ it stops. So currently script do not run nodes. It just prints that they are running:

>  ...
Started 5 processes
Finished starting nodes

but no java processes could be found in activity monitor.

System info:
Corda 3.2
macOS Mojave 10.14.2 (18C54)
IntelliJ IDEA 2018.3.3 (Ultimate Edition) Build #IU-183.5153.38, built on January 9, 2019

**Comment by joeldudleyr3** [comment]
Yeah, see https://stackoverflow.com/questions/54127811/mojave-terminal-not-starting-nodes-from-runnodes-corda-deploynodes.

**Comment by Koshub** [comment]
@joeldudleyr3 Ok, it works, but only after additionally IntelliJ added itself and Terminal to Accessibility **and** Automation setting and, of corse since I run nodes from IntelliJ terminal.

**Comment by tejusk06** [comment]
Im using Corda 4 on Mac(mojave), Intellij is added to both Accessibility and Automation, but I'm still facing the exact problem shown in the above image by epicsol-inc

**Comment by tejusk06** [comment]
The work around is to manually start the nodes via "java -jar corda.jar" in each nodes directory.
