### ISSUE TITLE
Nodes Hangs, when using appservicehub to start a flow in a blocking way

### ISSUE THREAD

**Issue by kid101** [corda/corda#4313]
Bug can be reproduced using repo: https://github.com/kid101/AppserviceHub/

Step 1: Clone and do a `gradle clean deployNodes`
Step 2: `build\nodes\runnodes` and wait for nodes and web server to start.
Step 3:  `curl http://localhost:10007/api/primes/create-prime?n=2`

The node will now hang and can be seen in the logs that the `DummyServiceFlow` never executed.

when `appservicehub` tries to start a flow (which calls `subflows`) in a blocking way it would hang, but If the call is non-blocking, it would work. 

https://github.com/kid101/AppserviceHub/blob/release-V3/service/src/main/kotlin/net/corda/examples/oracle/service/service/Oracle.kt#L47

**Comment by joeldudleyr3** [comment]
Thanks. Tracked here: https://r3-cev.atlassian.net/browse/CORDA-2265.

**Comment by florian-f** [comment]
>   services.startFlow(DummyServiceFlow()).returnValue.toCompletableFuture().get();// If I Don't wait for the result it would work. Not sure if it's an intended functionality.

That it wouldn't hang when you don't wait for the completion of the future is expected behaviour. 
Now, the question is why your flow would not complete. I'd have to take a closer look.
Have you tried debugging it? Do your logs reflect that the flow was actually started/ are there any errors?
If you make the DummyFlow `@StartableByRPC` (and override progressTracker), what happens if you start it via the shell of the Oracle node?

**Comment by kid101** [comment]
well my bad I didn't frame it correctly. The Flow would execute if it's called in a non-blocking way, though, the node would hang and flow wont get executed, if it's called in a blocking way. 

I had a look at the logs but couldn't get much as the `DummyServiceFlow`'s call method won't get executed it hangs somewhere before. I did annotate `DummyServiceFlow` with `@StartableByRPC` but it didn't help either.

**Comment by florian-f** [comment]
Ah OK.
I can reproduce your issue, will take a closer look.

**Comment by florian-f** [comment]
PrimesClientTests appears to reproduce this as well.

**Comment by joeldudleyr3** [comment]
Fixed.
