### ISSUE TITLE
Finality Flow has both extraRecipients and extraParticipants label for two functions.

### ISSUE THREAD

**Issue by anticlimactic** [corda/corda#4367]
From this [API document](https://docs.corda.net/api/kotlin/corda/net.corda.core.flows/-finality-flow/index.html), I noticed that there are two constructors for FinalityFlow which are the same, but have different argument names. 

FinalityFlow(transaction: SignedTransaction, extraParticipants: Set<Party>)
FinalityFlow(transaction: SignedTransaction, extraRecipients: Set<Party>, progressTracker: ProgressTracker)

Only extraRecipients is defined in the document, so unless extraParticipants is undocumented and does fulfils a different purpose,  I think it should be renamed to reduce ambiguity.

**Comment by mikehearn** [comment]
Unfortunately I don't see a way to rename this without breaking source compatibility for Kotlin. Someone might have used it as a named parameter. Agree?

**Comment by anticlimactic** [comment]
Agree.

**Comment by mikehearn** [comment]
Sadly, closing then.
