### ISSUE TITLE
Cash Contract : CashSelectionH2Impl picking up data from Queryable Table (cash_contract_states)

### ISSUE THREAD

**Issue by mahesh-bandkar** [corda/corda#4369]
* Description : Cash Contract/State has a queryable table : cash_contract_states. The code in CashSelectionH2Impl picks up data from this table in the call to generateSpend. This is incorrect as the data in the cash_contract_states can be tampered with leading to incorrect results.
* No logs
* Code Issue
* Corda 3.3

Code 👍 val selectJoin = """
                    SELECT vs.transaction_id, vs.output_index, ccs.pennies, SET(@t, ifnull(@t,0)+ccs.pennies) total_pennies, vs.lock_id
                    FROM vault_states AS vs, contract_cash_states AS ccs
                    WHERE vs.transaction_id = ccs.transaction_id AND vs.output_index = ccs.output_index
                    AND vs.state_status = 0
                    AND ccs.ccy_code = ? and @t < ?
                    AND (vs.lock_id = ? OR vs.lock_id is null)

**Comment by joeldudleyr3** [comment]
We consider it the node operator's responsibility to secure their database and thus attacks that involve tampering with the node's database are outside of our threat model.

**Comment by mahesh-bandkar** [comment]
@joeldudleyr3  The contract_cash_states is created due to the queryable annotation on the Cash State. We have seen that any changes to the table created due to the queryable state is only for the means for analytical and other aids. this would mean that the state is also stored outside of the NODE_TRANSACTIONS and VAULT_STATES table which would lead to it susceptible to tampering. Including the queryable table it in the transactional context increases the risk of data tampering.

**Comment by joeldudleyr3** [comment]
Hi @mahesh-bandkar, trying to understand.

"We have seen that any changes to the table created due to the queryable state is only for the means for analytical and other aids." - where have we seen this?
