### ISSUE TITLE
CashIssueAndPaymentFlow - should transfer cash which was issued in same flow

### ISSUE THREAD

**Issue by mahesh-bandkar** [corda/corda#4370]
* CashIssueAndPaymentFlow issues cash and transfers it to the receipient. 
 
override fun call(): Result {
        subFlow(CashIssueFlow(amount, issueRef, notary))
        return subFlow(CashPaymentFlow(amount, recipient, anonymous, notary))
    }

It should have a return from the CashIssueFlow and that reference should be used for the CashPaymentFlow for transfer.

* no logs- Code issue.
* No steps.
* Corda v3.3

**Comment by mahesh-bandkar** [comment]
@joeldudleyr3  My understanding is that if we already had cash we should have used it for the transfer. Now if we are issuing new cash - then it would be logical to use the same reference for the transfer.

**Comment by joeldudleyr3** [comment]
Ah, I see what you mean - the cash transferred may be with a different ref?

**Comment by joeldudleyr3** [comment]
Raised here: https://r3-cev.atlassian.net/browse/CORDA-2316.

**Comment by mikehearn** [comment]
I'm not quite sure I understand this one. Coin selection does not take into account recency.  Coins are meant to be fungible so why does it matter?

**Comment by joeldudleyr3** [comment]
@mikehearn I thought coins were supposed to be non-fungible if they have different `issueRef`s?

**Comment by shamsasari** [comment]
Echoing Mike's comment, the current behaviour is as designed.
