### ISSUE TITLE
Corda DemoBench source file corrupted

### ISSUE THREAD

**Issue by MubashirullahD** [corda/corda#4378]
New User here.
Hey, I am working on a semester project. I will skip the details of the voting system. I am facing issues as I set up the Corda DemoBench 3.3. I am on a 64-bit machine with the windows 10 pro OS. (jdk 10.0.2)

![image](https://user-images.githubusercontent.com/45071858/49601333-5c686400-f9a7-11e8-941e-ae9cfef44e3a.png)

Just wanted to point it out.

Retry does not help. 
In case this was not the place for this issue, do excuse.
Thank you.

**Comment by orionarmz** [comment]
download again^_^
