### ISSUE TITLE
Upgrade quasar to support newer JDKs

### ISSUE THREAD

**Issue by remmeier** [corda/corda#4423]
Corda makes use of Quasar 0.7.x and with this is also stuck with Java 8 that more or less is considered being end-of-life. Quasar 0.8 is available with support for JDK 11. See https://github.com/puniverse/quasar/issues/317.

**Comment by woutslakhorst** [comment]
The dependency on jdk8 is becoming an increasing problem. Older linux distro's no longer support an Oracle jdk with update version > 151. This gives problems with build services like Travis. For now there's a workaround with using openjdk8 but this requires custom configs.

Newer releases of java libs are being released for >jdk11, so any software that is being connected to Corda is also stuck on older releases of those libs.

**Comment by countfloyd** [comment]
To add to that, newer versions of Java have faster, more efficient runtimes, more choices in garage collectors, use less memory and can save a lot of money when running in the cloud.

**Comment by nargas-ritu** [comment]
Internal ticket [CORDA-4243](https://r3-cev.atlassian.net/browse/CORDA-4243)

**Comment by peterli-r3** [comment]
Hi remmeier,

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
