### ISSUE TITLE
update bintray setup

### ISSUE THREAD

**Issue by remmeier** [corda/corda#4425]
for custom patch releases we make use of a bintray account. But it seems that the current setup in corda or rather the used bintray version is broken.  for it to work we have to:

1. Upgrade the plugin to `classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.2'` from the current `1.4.0`.

2. fix the `vcUrl` and `websiteUrl!` like

```
allprojects{
    it.afterEvaluate {
        if (it.extensions.findByName("bintray") != null) {
            bintray {
                pkg {
                    vcsUrl = 'https://github.com/.....git'
                    websiteUrl = 'http://www.github.com/...'
                }
            }
        }
    }
}
```

3. Modify `repo` and `org` property.

Would be great if the first two could be fixed. Otherwise Gradle seems to get stuck and waits forever without actually uploading anything. That seems to be related to the outdated plugin. If there is a possiblity to override the `repo` and `org`  property with an environment variable, that would be even better because it would allow publishing without changing the sources.

**Comment by nargas-ritu** [comment]
Descoping as Bintray is decommissioned.
