### ISSUE TITLE
follow Java Bean conventions for setters

### ISSUE THREAD

**Issue by remmeier** [corda/corda#4441]
PropertyDescriptor.kt class makes use of reflection to discover the properties of classes for entities, states, flow inputs, etc. It is used by AMQP for serialization. One of the conditions looks like:

```
when (classifier) {
     GET -> parameterCount == 0 && returnType != Void.TYPE
     SET -> parameterCount == 1 && returnType == Void.TYPE
     IS -> parameterCount == 0 &&
                    (returnType == Boolean::class.java ||
                            returnType == Boolean::class.javaObjectType)
        }
```

For setters this is not entirely correct. It is well possible for setters to have a return type, most notably to return the object itself again for chaining of setter calls. https://projectlombok.org/ is one popular library that allows to generate setters (if somebody chooses not to use Kotlin, but rather go with Java). It generates setters exactly like this to allow chaining. With more recent Corda versions from the master branch this stopped working. The setters do not get recognized. And probably(?) Corda stopped accessing fields. This results in properties being silently ignored.

It would be great to remove the void condition or allow the object itself again as return type. When using Java, Lombok and related libraries become rather important since Java by itself as no construct for value types and properties, resulting in a lot of unnessary boilerplate.

**Comment by mikehearn** [comment]
Are you working on an app where this breaks your code? 

I'm not sure what the JavaBeans spec says, but if such methods used to be recognised then this would indeed be a regression. Bear in mind that it's much preferable to use immutable objects with constructors and getters rather than setters though!

**Comment by distributedleetravis** [comment]
Raised a ticket, will fix today: https://r3-cev.atlassian.net/browse/CORDA-2352

**Comment by mikehearn** [comment]
👍

**Comment by distributedleetravis** [comment]
PR raised: https://github.com/corda/corda/pull/4442

**Comment by remmeier** [comment]
thx! we are mostly immutable, not yet on all the inputs to the flows.

**Comment by distributedleetravis** [comment]
PR is merged. If you can confirm that this resolves your problem, @remmeier, I will close this issue.

**Comment by remmeier** [comment]
PR looks good, thx a lot. I think this can be closed, I doubt anything can be wrong with that changed line. Will be able to try again once https://github.com/corda/corda/pull/4415 is ready too.
