### ISSUE TITLE
Corda Exception - spi.SqlExceptionHelper.logExceptions - Unique index or primary key violation:

### ISSUE THREAD

**Issue by RK3713** [corda/corda#4447]
Hi All

Getting the below error after restarting the Corda node. It is coming every time and the node hangs and stops responding.

[ERROR] 10:31:11+0530 [Node thread-1] spi.SqlExceptionHelper.logExceptions - Unique index or primary key violation: "PRIMARY_KEY_C ON PUBLIC.VAULT_STATES(OUTPUT_INDEX, TRANSACTION_ID) VALUES (0, '4B8CA84DCFFD32C45BDF2391DF6BCF2E64DD37C337B2B008BDC9B429BFF0D9FA', 2181)"; SQL statement: insert into vault_states (consumed_timestamp, contract_state_class_name, lock_id, lock_timestamp, notary_name, recorded_timestamp, state_status, output_index, transaction_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-194] [ERROR] 10:31:11+0530 [Node thread-1] internal.ExceptionMapperStandardImpl.mapManagedFlushFailure - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]

**Comment by RK3713** [comment]
Corda open source version 3.3
Scenario
1. One node stopped responding while it was in the middle of a transaction.
2.Restarted the node multiple times. It showed the above mentioned exception every time.

I believe the node was trying to start again from the last db checkpoint but for some reason, every time when it was trying to rerun the transactions , the node hanged and stopped responding and couldn't recover back. 

Can anyone help me understand the above scenario?

**Comment by aalok05** [comment]
Facing the same issue.
