### ISSUE TITLE
addCommand should prevent accidental passing zero public keys

### ISSUE THREAD

**Issue by voddan** [corda/corda#4463]
When I write Corda flows I often make a mistake of adding a `CommandData` as a command without a public key:

    // Throws in runtime "The list of signers cannot be empty"
    transactionBuilder.add(myCommandData)

It is possible to pass a `CommandData` instead of a `Command` because of the following overload helper:

    fun addCommand(data: CommandData, vararg keys: PublicKey) = addCommand(Command(data, listOf(*keys)))

Note that `vararg` syntax can accept zero-length arrays, thus making it easy to ignore the `keys` parameter.

 Ideally this function should had had an additional `key` parameter to indicate that it needs at least one key and prevent accidental incorrect usages:

    fun addCommand(data: CommandData, key0: PublicKey, vararg keys: PublicKey) = addCommand(Command(data, listOf(key0, *keys)))

I use Corda 3.3

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4244](https://r3-cev.atlassian.net/browse/CORDA-4244)

**Comment by peterli-r3** [comment]
Hi voddan,

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
