### ISSUE TITLE
Download of attachment fails due to serialization failure

### ISSUE THREAD

**Issue by amiracam** [corda/corda#447]
I want to be able to download an attachment from a node down to a local filesystem for viewing from a GUI and I want to do it via the proxy.

I am exercising this via the Trader Demo for which there's a Prospectus attachment. It would seem that it would be as easy as this:

proxy.openAttachment(SellerFlow.PROSPECTUS_HASH)

unfortunately I get the following stack:

> Attachment exists true
> 
> net.corda.node.services.persistence.NodeAttachmentService$HashCheckingStream is not annotated or on the whitelist, so cannot be used in serialization
> Serialization trace:
> value (net.corda.core.ErrorOr)
> com.esotericsoftware.kryo.KryoException: Class net.corda.node.services.persistence.NodeAttachmentService$HashCheckingStream is not annotated or on the whitelist, so cannot be used in serialization
> Serialization trace:
> value (net.corda.core.ErrorOr)
> 	at net.corda.node.services.messaging.CordaRPCClientImpl$RPCProxyHandler.invoke(CordaRPCClientImpl.kt:184)
> 	at CommercialPaper.purchase(CommercialPaper.groovy:54)
> 	at TraderDemoTest.buyCommercialPaper(TraderDemoTest.groovy:131)
> 

As per Clinton perhaps its it looks like a missing Kyro registration.

**Comment by kchalkias** [comment]
resolved in [#471](https://github.com/corda/corda/issues/471)
