### ISSUE TITLE
ClassCastException in RPC interactive shell while using List<any Enum> in ContractState class

### ISSUE THREAD

**Issue by lolo8304** [corda/corda#4470]
**description:**
in the interactive shell of corda I receive the following message
`RPC failed: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Enum
`
after creating a new state using
`flow start MandateRequestFlow broker: PartyB, startAt: "2019-01-01T00:00:00Z", allowedBusiness: [ PnC ]
`
and then listing the vault with
`run vaultQuery contractStateType: ch.insurance.cordapp.broker.MandateState
`

**Steps to reproduce the issue**
I have modelled a ContractState class with a variable type List<Line>

```
public class MandateState implements LinearState {
...
    private final List<Line> allowedBusiness;
...
}

```

while Line is an Enum defined with 4 values
```
    @CordaSerializable
    public enum Line {
        PnC,
        IL,
        GL,
        Health;
    }

```

The object seems to be correcly loaded but finally its not. Because the objects  loaded from database  cannot be used due to TypeMissmatch in the variable "allowedBusiness"

**Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)**
while remote debugging the issue I have figured out that in the constructor annotated with @ConstructorForDeserialization the List ist passed as a type List<String> (instance Collections$UnmodifiableRandomAccessList) and including an Object "PnC" as a String instead of the enum.
Seems that enums are fully supported if they are used directly as variables but not in Lists

**The version/tag/release or commit hash it occurred on**
`    ext.corda_release_version = 'corda-3.0'
`

**Comment by lolo8304** [comment]
I guess the issue is finally NOT in the RCP interactive shell - this is only a follow up error to printout the object based on the metadata.
Actually the deserialization is wrong

**Comment by lolo8304** [comment]
i just saw on https://docs.corda.net/releases/release-V3.3/serialization.html that EnumSet are supported. Important would be that corda raises an exception during save that this type of List<Enum> is not supported

**Comment by arsalankhalid** [comment]
Has this been tested for 4.0? I'm happy to look into this...

**Comment by gitgabrio** [comment]
Hi @joeldudleyr3, @lolo8304 
I've tested the following one inside 4.1

```
data class CarState(val owningBank: Party, val holdingDealer: Party,
                    val manufacturer: Party,
                    val make: CarMaker,
                    val features: List<CarFeatures>,
                    val linearId: UniqueIdentifier
) 

@CordaSerializable
enum class CarFeatures {

    NICE,
    FAST,
    SLOW,
    BIG,
    SMALL,
    BAD
}
```

and successfully started the flow inside one node. I could also see the transaction with the `run vaultQuery` command.

Is this bug to be closed?

**Comment by joeldudley** [comment]
Yep, let's close it out :)
