### ISSUE TITLE
Cannot build a cordapp alongside a dependant cordapp that uses a different version of a 3rd party library.

### ISSUE THREAD

**Issue by ragmondo** [corda/corda#4654]
I've tried to explain the issue a few times and think it's probably best to demonstrate via code and I have finally managed to boil it down to a test.

I created the repo https://github.com/ragmondo/corda-bug-3rd-party-libs which is based on today's version of cordapp-template-kotlin

What I have done is added two 3rd party library dependencies and a new module called "contracts-old"

In https://github.com/ragmondo/corda-bug-3rd-party-libs/blob/release-V4/contracts-old/build.gradle you can see that I am depending on version 0.9 of joda-money
In https://github.com/ragmondo/corda-bug-3rd-party-libs/blob/release-V4/contracts/build.gradle I depend on the version 1.0.1 of joda-money

A testable difference in the two libraries is that the new version has the inclusion of a currency "VES" and the old version is not aware of this currency.

This is testable via the two unit tests https://github.com/ragmondo/corda-bug-3rd-party-libs/blob/release-V4/contracts-old/src/test/kotlin/com/template/ContractTests.kt and https://github.com/ragmondo/corda-bug-3rd-party-libs/blob/release-V4/contracts/src/test/kotlin/com/template/ContractTests.kt where you can see the library that relies on 0.9 will pass if the exception is thrown and 1.0.1 will pass if no exception is thrown. This is the required behaviour.

If you run these tests in IJ, you will find that they both pass. However, if you run via gradlew test, you will see that it fails due to 
```
> Task :contracts:test FAILED
 
com.template.ContractTests > VESCurrencyTest FAILED
    org.joda.money.IllegalCurrencyException: Unknown currency 'VES'
        at org.joda.money.CurrencyUnit.of(CurrencyUnit.java:260)
        at org.joda.money.BigMoney.parse(BigMoney.java:373)
        at org.joda.money.Money.parse(Money.java:337)
        at com.template.ContractTests.VESCurrencyTest(ContractTests.kt:15)
```
This is due to the fact that the wrong library (i.e. the 0.9 version) is being bundled with the new cordapp. Interestingly (and I'm not sure why this is), using reflection to try and get the library version number out returns null when run via the test.

The expected behaviour is that the new library should be bundled with the updated app and the old library is bundled with the old app. If my gradle-fu was up to much, then I would start getting into the depths of the cordformation stuff and raise a PR. 

I believe that this issue prevents anybody who wishes to do a migration from using an updated version of a 3rd party library.

As I always say when I bring up stuff like this is that I am more than happy to be corrected or to be shown a workaround etc.

**Comment by josecoll** [comment]
Thanks @ragmondo. Will take a look and revert back with a response shortly.

**Comment by richardblocksure** [comment]
Hey @josecoll . Appreciate it.

Don't underestimate this though; I won't deny that I have deliberately structured it as somewhat of a Pandora's box. There is the initial issue that cordformation does not build the cordapps correctly but then there is the classloader issue. Note that the cordapps require different versions of their third party libraries but also note that *both* versions of the respective libraries must be accessible during the `upgrade` method (hence the reason I've included them in the state constructor, if they were just used after the corda boundary it wouldn't be half the challenge!) - this is (unsurprisingly) way beyond my level of javanese to fix. This will probably manifest when you start digging below the surface. A beer in it for you when it's resolved.

**Comment by tudor-malene** [comment]
Hi @ragmondo ,

I had a look at this and it seems to be a bug with the cordapp gradle plugin.

@chrisr3 might want to take a look at this sometimes.

**Comment by ragmondo** [comment]
It is indeed a bug with the cordapp gradle plugin @tudor-malene . However, when that bug is fixed, it will reveal the classloader issue, as I mentioned in my comment (from my other github account).

**Comment by tudor-malene** [comment]
Indeed, I missed that.

There's a couple of issues with the code. When you're doing explicit upgrades you're supposed to replace both the contract and the state. In this case you use the same name for the contract.

**Comment by ragmondo** [comment]
Are you asking me to make the changes? If I do make the contract name different and the same bug occurs what happens then ?  I first raised this last year I think, but just to prove it even went to the lengths of creating an example based on the cordapp template. Once the gradle plugin template's fixed then I might revisit but right now I (we) just code "around" migrations and that'll be the case until I start seeing others going through the pain. Have been banging on trying to find out who else is trying to do a non-trivial cordapp migration on corda-dev (amongst other places) for almost a year now and still there's very little real world experience.

**Comment by tudor-malene** [comment]
Explicit upgrades have severe limitations in Corda 4. 

The attachment as code concept has not been implemented for them.
For example, an explicit upgrade will be run in the classloader of the node. 
In case you have 2 versions of joda-time in that classloader, the results will not be very predictable.

The Signature constraint is meant to replace most cases where you'd use explicit upgrades though.
