### ISSUE TITLE
fix Java version check

### ISSUE THREAD

**Issue by remmeier** [corda/corda#4665]
e.g. it fails for 

`You are using a version of Java that is not supported (1.8.0_202-ojdkbuild). Please upgrade to the latest version of Java 8.`

obtained from https://github.com/ojdkbuild/ojdkbuild. a warning may would also be sufficient rather than terminating the process.

(In general it would be nice to see Java 11+ supported. Java 8 is end-of-life, more difficult to download, complicated to use with an outdated quasar and rather bad memory characteristics compare to newer JVMs like openj9)

**Comment by woutslakhorst** [comment]
Also using any update version higher that 1.8.0_151 is causing problems with hosted CI solutions. Travis for example uses Ubuntu Trusty or Xenial. Trusty uses 1.8.0_151 and does not have an apk update to _202. Xenial uses openjdk11 and also does not have an apk install for jkd8.

**Comment by rick-r3** [comment]
I believe changes in Feb 2019 should have solved this for `1.8.0_202-ojdkbuild`
