### ISSUE TITLE
Crash Shell Is Not Published Correctly To Artifactory

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#4701]
Despite [attempts](https://github.com/corda/corda/pull/3891) to remove the dependency on jitpack, it is still required.

Only the crash shell jar is published to artifactory
https://ci-artifactory.corda.r3cev.com/artifactory/corda-dependencies/com/github/corda/crash/crash.shell/cadb53544fbb3c0fb901445da614998a6a419488/

The pom is missing which causes Runtime Errors such as:

    Caused by: java.lang.NoClassDefFoundError: org/apache/sshd/common/util/security/SecurityUtils
	    at net.corda.testing.node.internal.InternalMockNetwork.<init>(InternalMockNetwork.kt:159)
	    at net.corda.testing.node.internal.InternalMockNetwork.<init>(InternalMockNetwork.kt:150)
	    at net.corda.testing.node.MockNetwork.<init>(MockNetwork.kt:286)
	    at net.corda.testing.node.MockNetwork.<init>(MockNetwork.kt:275)

The only way to fix it is to add jitpack back to the repository list:

    allprojects {
      repositories {
        jcenter()
        //SNAPSHOTS are only on R3 CI Server
        maven { url 'https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases' }
        maven { url 'https://ci-artifactory.corda.r3cev.com/artifactory/corda-dependencies' }
        //Crash Shell dependencies are not published correctly in R3 repo
        maven { url 'https://jitpack.io' }
      }
    }

**Comment by opticyclic** [comment]
Bumped into this again today.

@mikehearn can you either publish it correctly to artifactory or remove it completely.

Compile time errors are much more preferable to runtime errors.

**Comment by remmeier** [comment]
+1

in general it would be very good to see official corda releases move away from having pieces in private repositories and host everything on jcenter. On the one side it causes an administrative burden in every involved companies, as most have rather strict policies of what is allowed to access. And the other side it has a performance impact by having to add various additional third-party repositories.

**Comment by opticyclic** [comment]
This is a pretty simple fix. Why is it taking a year to fix?

**Comment by nargas-ritu** [comment]
Fixed with Corda 4.9
