### ISSUE TITLE
Open methods in TransactionBuilder

### ISSUE THREAD

**Issue by manosbatsis** [corda/corda#4708]
Is there a particular reason for `copy`, `withItems` and `addOutputState` methods to be final? The kdoc says 

> The builder can be customised for specific transaction types, e.g. where additional processing is needed before adding a state/command.

so this looks like an omission. At the moment I can only partially implement  what I'm after and  not very reliably, at least not without a wrapper/decorator which feels rather ugly.

Would be happy to add a PR.

**Comment by joeldudleyr3** [comment]
@manosbatsis What kind of stuff are you looking to implement that you're unable to?

**Comment by manosbatsis** [comment]
@joeldudleyr3 wanted an implementation that would abstract easy access to all participants of in/out states already added to it. Of course this is only an example of how one could extend the `TransactionBuilder`. Opening `copy`, `withItems` and `addOutputState` seems a reasonable enough change to lower the bar but that's just me.

**Comment by series0ne** [comment]
@manosbatsis I think you could get all the output state participants with an extension property, but I didn't find a way to do this with input states.

```
val TransactionBuilder.outputStateParticipants: Iterable<AbstractParty> get() =
        this.outputStates().flatMap { it.data.participants }
```

**Comment by series0ne** [comment]
@manosbatsis @joeldudleyr3 On another note, perhaps I don't know enough about it, but I can't actually see a reason why `TransactionBuilder` is `open` in the first place. If I'm honest, it seems like an unusual thing to want to extend. 

Maybe another approach would be to [favour composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance). With this approach, you would just encapsulate a `TransactionBuilder` inside your own `ParticipantAwareTransactionBuilder`. You could still adopt the same method contracts, or change them if it made sense to do them. Your methods simply collect participants from input and output states, and then call the equivalent method on the transaction builder instance to perform the required task.

Quick example:

```
class ParticipantAwareTransactionBuilder {
    private val transactionBuilder: TransactionBuilder()
    private val mutableOutputParticipants = mutableListOf<AbstractParty>()

    val outputParticipants: Iterable<AbstractParty> get() = mutableOutputParticipants

    fun addOutputState(state: ContractState): ParticipantAwareTransactionBuilder {
        state.participants.forEach { mutableOutputParticipants.add(it) }
        transactionBuilder.addOutputState(state);
        return this
    }

    fun getTransactionBuilder(): TransactionBuilder {
        return transactionBuilder;
    }
}
```

**Comment by manosbatsis** [comment]
@series0ne yes wrapping the `TransactionBuilder` is of course an option as suggested in the issue description. Good point on `TransactionBuilder` being open, looks like this issue is becoming about clearing things out, i.e. either open the methods suggested or close `TransactionBuilder` altogether.

**Comment by rick-r3** [comment]
It's part of the API stability assurance, so cannot be changed.
