### ISSUE TITLE
Unable to import sumCashBy using IntelliJ IDEA

### ISSUE THREAD

**Issue by TywinLannister1313** [corda/corda#4738]
IntelliJ IDEA started highlighting errors in some of my import statements that worked previously. This is not unexpected as net.corda.finance is still in the "incubating" stage.

I am working in Java.

Corda Release: 3.3

Noticed #4700 

So I made what I thought are the necessary changes...

//Old

//import static net.corda.finance.utils.StateSumming.sumCashBy;

//New

import static net.corda.finance.contracts.utils.StateSumming.sumCashBy;

...but I'm still getting an error. I am sure I must be overlooking something simple.

**Comment by TywinLannister1313** [comment]
I added:

`cordaCompile "$corda_release_group:corda-finance:$corda_release_version"`

...to the build.gradle file under the dependencies section. No more errors with my import statement:

`import net.corda.finance.utils.StateSumming;`

...and no issues calling the sumCashBy method.

**Comment by abax1** [comment]
@TywinLannister1313, I'm getting the same issue but adding `cordaCompile "$corda_release_group:corda-finance:$corda_release_version"` to my root `build.gradle` hasn't seemed to add that dependency.

![image](https://user-images.githubusercontent.com/37125661/57760447-785cf800-76f3-11e9-9bac-de559ec824c4.png)

Am I doing something wrong?  Can you tell me exactly what you did to get it working?

Many thanks!

**Comment by TywinLannister1313** [comment]
@abax1  sorry for the delay.  What version of Corda are you using?  I think it has changed in version 4.  I just tested it against the template that Corda provides (which is setup to be version 4):

[https://github.com/corda/cordapp-template-java](url)

![image](https://user-images.githubusercontent.com/47535461/57990489-35d54b80-7a64-11e9-9022-a363cf928e63.png)

... and I had to change what goes in the build.gradle file compared to what worked in version 3.3

Here are the steps:

1) Make a call to sumCashBy in your code and you will get an error...

![image](https://user-images.githubusercontent.com/47535461/57990114-6a470880-7a60-11e9-93fe-542a2843baa9.png)


2) Go to the build.gradle file that is in the same module...

![image](https://user-images.githubusercontent.com/47535461/57990043-07557180-7a60-11e9-901f-ee1f1c9690a0.png)

3) Add:

`cordaCompile "$corda_release_group:corda-finance-contracts:$corda_release_version"`

... into the dependencies section (Note the difference compared to what I mentioned earlier in version 3.3).

4) Upon making that change Gradle will prompt you to Import Changes...

![image](https://user-images.githubusercontent.com/47535461/57990149-f0634f00-7a60-11e9-90bc-3050b20d25ba.png)

5) Once Gradle is complete everything should work...

![image](https://user-images.githubusercontent.com/47535461/57990178-5c45b780-7a61-11e9-90c0-ab6b2b441c82.png)

If you are using Corda version 3.3 the steps are the same except the entry in the build.gradle file is...

`cordaCompile "$corda_release_group:corda-finance:$corda_release_version"`

If you are still having trouble let me know.
