### ISSUE TITLE
enhancement: ServiceHub service for observing node's state machines and hospital

### ISSUE THREAD

**Issue by forstema** [corda/corda#4742]
We are implementing a monitoring service that collects different kinds of metrics in a node for Elastic. What is still missing are flow metrics which are, as far as we know, not directly readable. See also https://stackoverflow.com/questions/54304554/tracking-the-corda-flows.

To improve this it would be great if AppServiceHub/ServiceHub provided services returning data feeds on the node's state machines and the flow hospital.

**Comment by adelel1** [comment]
Can you tell us what you are trying to achieve here, and why specifically a service to provide this info is needed. Thanks.

**Comment by peterli-r3** [comment]
Hi forstema,

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
