### ISSUE TITLE
Corda 4 nodes defined with the net.corda.plugins.Cordform task hang in the initialization routine when the “runnodes” script is launched with the "--logging-level=DEBUG" option.

### ISSUE THREAD

**Issue by pgrindean** [corda/corda#4755]
Out of three nodes, at least one will hang with the last log lines looking like the excerpt below. When removing the "--logging-level=DEBUG" runnodes option, all nodes come up successfully. The “logging-level” option works fine with the Corda 3 nodes.

```[INFO ] 2019-02-13T11:45:17,081Z [main] network.PersistentNetworkMapCache.addNode - No previous node found
[INFO ] 2019-02-13T11:45:19,873Z [main] internal.Node.updateNodeInfo - New node-info: NodeInfo(addresses=[localhost:11007], legalIdentitiesAndCerts=[CN=Issuer Org, OU=Issuer, O=ISNYUS33XXX, L=New York, ST=NY, C=US], platformVersion=4, serial=1550058317034)
[INFO ] 2019-02-13T11:45:20,196Z [main] pool.HikariPool.shutdown - HikariPool-1 - Close initiated...
[INFO ] 2019-02-13T11:45:20,212Z [main] pool.HikariPool.shutdown - HikariPool-1 - Closed.```

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4247](https://r3-cev.atlassian.net/browse/CORDA-4247)

**Comment by peterli-r3** [comment]
Hi pgrindean

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
