### ISSUE TITLE
CordaFuture's get() method goes into the blocking state indefinitely.

### ISSUE THREAD

**Issue by surajkaudgave** [corda/corda#4757]
Here is some code which I'm trying to get transaction by id, 
   when it gets subscribes by stateMachineRecordedTransactionMappingFeed.

```
 public void subscribeForTransactionFuture() {
        DataFeed<List<StateMachineTransactionMapping>, StateMachineTransactionMapping> smtFeed = 
        rpcConnection.getProxy() .stateMachineRecordedTransactionMappingFeed();
        smtFeed.getUpdates().subscribe(it -> getTransactionById(it.getTransactionId()));
   }
```
	
It's going into blocking state randomly for `transactionInfoFlowHandle.getReturnValue().get(20, TimeUnit.SECONDS)`. Also tried for `transactionInfoFlowHandle.getReturnValue().get()` but the result is same.
	
```
public synchronized void getTransactionById(SecureHash transactionId) {
      FlowHandle<TransactionInfo> transactionInfoFlowHandle = 
           rpcConnection.getProxy().startFlowDynamic(FetchTransactionsFlow.ByTxId.class, transactionId);	
           try {
                //Following get() method gets blocked indefinitely.
		TransactionInfo transactionInfo = transactionInfoFlowHandle.getReturnValue().get(20, TimeUnit.SECONDS);		
        } catch (Exception e) {
            logger.error(e.getMessage() + "- transactionId " + transactionId);
        }
    }
```

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4248](https://r3-cev.atlassian.net/browse/CORDA-4248)

**Comment by peterli-r3** [comment]
Hi surajkaudgave

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
