### ISSUE TITLE
Documentation of hello world example out of date

### ISSUE THREAD

**Issue by grebnetiew** [corda/corda#4822]
The tutorial includes source code for [a "hello world" example](https://github.com/corda/corda/tree/master/docs/source/example-code/src/main/java/net/corda/docs/java/tutorial/helloworld). However, this code does not compile as written, and is different from the [solution](https://github.com/corda/corda-tut1-solution-java) also maintained by the corda account. This solution does work correctly. The docs should therefore reflect the code in the solution (and be slightly revised to omit the `IOUFlowResponder.java` code).

**Comment by prateektiwari7** [comment]
#5024 raised I think.

**Comment by rick-r3** [comment]
PR was merged
