### ISSUE TITLE
Improve Metrics

### ISSUE THREAD

**Issue by remmeier** [corda/corda#4833]
Would be great to see some enhancements to the metrics part of Corda:

- the documentation points out the use of JMX to access the metrics through Jolokia. But JMX is not overly much "fun" to use and for this reason never gained much adoption.
- Dropwizard metrics is used in the underlying implementation. The past two years micrometer gained a lot of traction and activity, while not so much happened on the dropwizard side. e.g. it is also part of the default Spring stack. Maybe it would make sense to switch the implementation. It comes out-of-the-box with a rich set of adapters like Prometheus and Elastic.
- Allow for cordapps to expose metrics.

I could also provide some contributions. Currently we run micrometer within a cordapp.

**Comment by adelel1** [comment]
We're currently doing some research into this area. Specifically looking at opentelemetry and what that can give us.
