### ISSUE TITLE
DemoBench cordapps directory ignored when loading profile

### ISSUE THREAD

**Issue by gtabmx** [corda/corda#4843]
When loading cordapp jars from the UI when creating nodes, cordapps load fine, as evidence by both the logs listing the loaded cordapps, as well as the available flows from `flow list`. However, building a profile with the same cordapp jars in the cordapps directories does not result in them loading when the profile is loaded.

How I tested. I deployed 3 nodes (Notary, A, and B) with the UI, manually adding the cordapps I wanted. I checked the flows were available. Then closed DemoBench, and cleansed/normalized the demobench session folder that was created, in order to archive it and create my own .profile. Loaded the profile, and the cordapps did not load, however, everything else loaded fine.

The logs did not show any errors. I'm inclined to believe the jars were not even detected, since once detected, any errors in loading them would produce log errors, in which there were none.

I am running release/branch v4.

**Comment by rick-r3** [comment]
DemoBench is deprecated.  Won't fix.
