### ISSUE TITLE
Invalid Kotlin Source Code in Tutorials "Hello, World! Pt.2"

### ISSUE THREAD

**Issue by PatrickPan2012** [corda/corda#4885]
Hi,

The kotlin source codes in ["Updating the borrower’s flow"](https://docs.corda.net/tut-two-party-flow.html#updating-the-borrower-s-flow) can't be displayed successfully though I can find them in Github repo. Personally, it would be better to fix.

Thanks very much.

**Comment by prateektiwari7** [comment]
Hi @PatrickPan2012 

Can you please show me your error. I think for Java it is working and in Java it is using some of .kt files to call the libraries.

**Comment by PatrickPan2012** [comment]
> Hi @PatrickPan2012
> 
> Can you please show me your error. I think for Java it is working and in Java it is using some of .kt files to call the libraries.

**Comment by PatrickPan2012** [comment]
> Hi @PatrickPan2012
> 
> Can you please show me your error. I think for Java it is working and in Java it is using some of .kt files to call the libraries.

Hi @prateektiwari7 

The source codes are correct. What I mean is the codes can't be shown correctly in the [document](https://docs.corda.net/tut-two-party-flow.html#updating-the-borrower-s-flow). Please click the hyper link and click tab "Kotlin".

**Comment by prateektiwari7** [comment]
Hi @PatrickPan2012 

Yes I agree with you. At many places we have find the bug to call the events. I think Corda team must need to work on documentation part.

**Comment by lankydan** [comment]
Raised https://github.com/corda/corda/pull/5024 to address this.

**Comment by lankydan** [comment]
merged #5024 so closing this issue.
