### ISSUE TITLE
Improvements to docker image : compatible with v3.3; image size; truststore 

### ISSUE THREAD

**Issue by rickcrook** [corda/corda#4954]
Great to see [official docker images for corda](https://hub.docker.com/u/corda).

A few improvements if I might be so bold:

1. backward compatible with 3.3 : add `--` to initial-registration in [generate-config.sh](https://github.com/corda/corda/blob/master/docker/src/bash/generate-config.sh#L52)
2. Remove hardcoding : Use `${CONFIG_FOLDER}/node.conf` in [run-corda.sh](https://github.com/corda/corda/blob/master/docker/src/bash/run-corda.sh#L10)
3. backward compatible with 3.3 : remove `=` from `--config-file=` in [run-corda.sh](https://github.com/corda/corda/blob/master/docker/src/bash/run-corda.sh#L10)
4. Docker image size : delete yum cache
5. Docker image size : minimize number of layer using [Docker best practises](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers)
6. Maintainability : Default `JVM_ARGS` and `CORDA_ARGS` in [Dockerfile](https://github.com/corda/corda/blob/master/docker/src/docker/DockerfileAL) rather than [run-corda.sh](https://github.com/corda/corda/blob/master/docker/src/bash/run-corda.sh#L4)
7. ~~UX : Add network-root-truststore to improve [onboarding process to Corda.Network UAT](https://corda.network/participation/index.html) and stop two-stage deploy process~~
8. ~~Security : Remove `EXPOSE` from Dockerfiles. Ports should be exposed at run-time not build-time.~~

Happy to raise a PR if there is desire for these changes

**Comment by Bartman250** [comment]
I don't recommend exposing the p2p ports in the dockerfile as if you are running in docker compose, a docker 'swarm' or kubernetes network or in vpn, you don't need to expose these ports

**Comment by Bartman250** [comment]
Ideally - the docker file paths should be compatible with the 'deployNodes' directory structure - so that it is easy to migrate to docker locally in dev mode - and it saves the joy of try to sus out where all the directories and files need to go (So far spent nearly 2 days trying to figure this out in front of clients) !.

**Comment by rickcrook** [comment]
Image size post #4965 
```bash
REPOSITORY                          TAG                 CREATED             SIZE
corda/corda-zulu-5.0-snapshot       latest              3 hours ago         692MB
corda/corda-zulu-5.0-snapshot       20190329190533      2 days ago          716MB
corda/corda-corretto-5.0-snapshot   release             2 days ago          1.19GB

corda/corda-corretto-5.0-snapshot   latest              3 hours ago         660MB
corda/corda-corretto-5.0-snapshot   20190329190533      2 days ago          1.19GB
corda/corda-corretto-4.0            RELEASE             5 weeks ago         1.16GB
```

**Comment by nargas-ritu** [comment]
PR was merged. Hence closing the issue
