### ISSUE TITLE
Windows Classpath Issues Cause Contract Unit Tests Fail In v4

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#4975]
The unit tests fail in v4 on Windows due to classpath length issues.

On non-Windows systems the unit tests pass.
However, on Windows the classpath is too long so you need to modify the run config in IDEA to either use JAR manifest or classpath file. 
Both of these options fail.
Interestingly, they fail for different reasons.

e.g. In the samples project: 

**JAR Manifest:**

    net.corda.core.transactions.MissingContractAttachments: Cannot find contract attachments for com.example.contract.SanctionedEntitiesContractnull. See https://docs.corda.net/api-contract-constraints.html#debugging
    
            at net.corda.core.transactions.TransactionBuilder.selectAttachmentThatSatisfiesConstraints(TransactionBuilder.kt:445)

As aside note: the null is being concatenated to the contract in a String here `SanctionedEntitiesContractnull`

**Classpath File**

    
    net.corda.core.internal.TransactionDeserialisationException: Failed to deserialise group COMMANDS_GROUP at index 0 in transaction: Could not carpent net.corda.testing.core.DummyCommandData
    
            at net.corda.core.internal.TransactionUtilsKt$deserialiseComponentGroup$1.invoke(TransactionUtils.kt:82)
            at net.corda.core.internal.TransactionUtilsKt$deserialiseComponentGroup$1.invoke(TransactionUtils.kt)

**Comment by sanjukammath** [comment]
I was facing the same issue. This seems to be an IDEA issue. If you try to run the tests from cmd in windows the tests are succeeding.

**Comment by jmorrispa** [comment]
Hi, I got 'Yo-cordapp' sample unit and integration test working in Windows Intellij 2019.3.1 after switching **Gradle JVM** from OpenJDK 11 to 8.
