### ISSUE TITLE
Unable to install rpm installer - demobench

### ISSUE THREAD

**Issue by pklaus1** [corda/corda#5004]
I'm unable to install rpm installer in OpenSuse Leap 42.3 
x86_64 kernel  4.4.176-96-default
1. See first picture - it says "no dependency" missing libXtst.so.6
2. There is required lib installed though, see second picture
![rpm1](https://user-images.githubusercontent.com/49517135/55949055-0efc4c00-5c52-11e9-9174-7c1f5bec82d0.png)
![lib1](https://user-images.githubusercontent.com/49517135/55949068-158ac380-5c52-11e9-9c58-2c05f221ecc6.png)

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4250](https://r3-cev.atlassian.net/browse/CORDA-4250)
