### ISSUE TITLE
Experimental - netparams needs to support NETWORK_MAP (and NETWORK_PARAMETERS) cert issued by an CA other than the root CA

### ISSUE THREAD

**Issue by cxyzhang0** [corda/corda#5027]
Thank you for choosing to report an issue with Corda. 

When reporting an issue please make sure it contains;

* A clear description of the issue
* Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)
* Steps to reproduce the issue
* The version/tag/release or commit hash it occurred on

**Comment by cxyzhang0** [comment]
Currently, if we use the tool to sign network-parameters by a cert issued by a subordinate CA under root CA, the path validation would fail at node start. That is because it only includes a single cert in the signed network-parameters. The fix is to include the parentCertsChain as well.

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4238](https://r3-cev.atlassian.net/browse/CORDA-4238)

**Comment by peterli-r3** [comment]
Hi cxyzhang0,

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
