### ISSUE TITLE
Using VaultQuery with Sorting won't work if no other field condition

### ISSUE THREAD

**Issue by Satienpong** [corda/corda#5060]
I'm using **vaultQueryBy** that query all **Unconsumed state** and sorting with some field of that state but it not working (result is completely random sorting). Then I use the same **vaultQueryBy** but add some equal condition, then result is perfectly sorting.

I tried with other field also (type String and long) but it not work also, Unless using with other field condition.

Here some code
```
QueryCriteria queryCriteria = new QueryCriteria.VaultQueryCriteria(Vault.StateStatus.UNCONSUMED);

Sort.SortColumn sortCol = new Sort.SortColumn(new SortAttribute.Custom(CustomerSchema.CustomerEntity.class, "changeDate"), Sort.Direction.DESC);
List list = new ArrayList();
list.add(sortCol);
List<StateAndRef<CustomerState>> list = rpcOps().vaultQueryBy(queryCriteria, pageSpecification, new Sort(sortList), CustomerState.class).getStates();
```
And it's not working then I add this condition before **vaultQueryBy**

```
QueryCriteria baseCriteria = new QueryCriteria.VaultCustomQueryCriteria(Builder.notNull(getField("linearId", CustomerSchemaV01.CustomerEntity.class)));
queryCriteria = queryCriteria.and(baseCriteria);
```
And it' work fine get result with correct sorting.

I'm not quite sure that it's Corda's intention or just some bug, but I think it should be able to order without using any field condition.

Develop with Corda OS3.3

**Comment by johnbuckle** [comment]
This is probably expected behaviour since the sorting criteria is only applicable to custom queries, and hence you need to provide a custom query for it to be added to the overall query. Let me verify this.

**Comment by nargas-ritu** [comment]
Internal ticket [CORDA-4235](https://r3-cev.atlassian.net/browse/CORDA-4235)
