### ISSUE TITLE
RPC Client Shuts Down Node

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5069]
I have a spring webserver that connects to a node via RPC.

Stopping the web server obviously closes the rpc connection.

However, this somehow triggers the node to shutdown as well.

The only info in the logs is:

```
[INFO ] 2019-04-29T18:13:46,673Z [main] BasicInfo.printBasicNodeInfo - Node for "BankA" started up and registered in 24.79 sec
[INFO ] 2019-04-29T18:13:46,675Z [main] rpc.RPCServer.start - Starting RPC server with configuration RPCServerConfiguration(rpcThreadPoolSize=4, reapInterval=PT1S, deduplicationCacheExpiry=PT24H)
[INFO ] 2019-04-29T18:13:57,913Z [pool-7-thread-1] BasicInfo.printBasicNodeInfo - Shutting down ...
```

**Comment by opticyclic** [comment]
The issue seems to be down to how the CordaRPCOps is created in the Spring context.

If you create it as a bean and pass it to the Controller the node shuts down when the client shuts down.

    @Component
    public class CordaComponent {
    
      @Value("${rpc.user}")
      private String username;
    
      @Value("${rpc.password}")
      private String password;
    
      @Value("${host}")
      private String host;
    
      @Value("${port}")
      private int port;
    
      @Bean
      public CordaRPCOps proxy() {
        NetworkHostAndPort networkHostAndPort = new NetworkHostAndPort(host, port);
        CordaRPCClient rpcClient = new CordaRPCClient(networkHostAndPort);
        CordaRPCConnection rpcConnection = rpcClient.start(username, password);
        return rpcConnection.getProxy();
      }
    }

    public class RPCController {
    
      private final CordaRPCOps proxy;
    
      public RPCController(CordaRPCOps proxy) {
        this.proxy = proxy;
      }

However, if you don't create a bean but create a wrapper class like [here](https://github.com/corda/corda-tut2-solution-java/blob/release-V3/clients/src/main/java/com/template/webserver/NodeRPCConnection.java)  and then manually set the proxy

      public class Controller {
          private final CordaRPCOps proxy;

          public Controller(NodeRPCConnection rpc) {
              this.proxy = rpc.proxy;
      }

The issue does not occur.

In Corda v2, if Spring injected the CordaRPCOps then the hashCode method caused problems with the RPCServer. This no longer appears to be the case but this new issue has turned up.

Since we can't control how clients are constructing their code we shouldn't have a security vulnerability where they can shut down nodes remotely without permission.

**Comment by opticyclic** [comment]
See attached for partial TRACE logs of the nodes for the 2 different ways of connecting. 

They show the section when the RPC client starts to shut down.

[inject.log](https://github.com/corda/corda/files/3139336/inject.log)
[wrapper.log](https://github.com/corda/corda/files/3139337/wrapper.log)

Note the lines in the first file where we inject the `CordaRPCOps` with Spring.
You can see the `shutdown` method being sent:

    [TRACE] 2019-05-02T17:43:26,450Z [Thread-1 (activemq-netty-threads)] impl.RemotingConnectionImpl.bufferReceived - RemotingConnectionID=e2d60284 handling packet PACKET(SessionSendMessage)[type=71, channelID=10, packetObject=SessionSendMessage, message=CoreMessage[messageID=0,durable=false,userID=null,priority=4, timestamp=Thu May 02 13:43:26 EDT 2019,expiration=0, durable=false, address=rpc.server,size=798,properties=TypedProperties[JMSReplyTo=rpc.client.user1.4645115711283106039,tag=0,rpc-id=2caf6562-ab82-40c8-9b42-f464fb2421c7,deduplication-sequence-number=2,rpc-id-timestamp=1556819006448,rpc-session-id-timestamp=1556818969877,method-name=shutdown,rpc-session-id=eb826ba4-99a3-4064-9d5a-46ced637d285]]@262413043, requiresResponse=false]
    [TRACE] 2019-05-02T17:43:26,451Z [Thread-29 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@32c6eb3c)] core.ServerSessionPacketHandler.onMessagePacket - ServerSessionPacketHandler::handlePacket,PACKET(SessionSendMessage)[type=71, channelID=10, packetObject=SessionSendMessage, message=CoreMessage[messageID=0,durable=false,userID=null,priority=4, timestamp=Thu May 02 13:43:26 EDT 2019,expiration=0, durable=false, address=rpc.server,size=798,properties=TypedProperties[JMSReplyTo=rpc.client.user1.4645115711283106039,tag=0,rpc-id=2caf6562-ab82-40c8-9b42-f464fb2421c7,deduplication-sequence-number=2,rpc-id-timestamp=1556819006448,rpc-session-id-timestamp=1556818969877,method-name=shutdown,rpc-session-id=eb826ba4-99a3-4064-9d5a-46ced637d285]]@262413043, requiresResponse=false]

**Comment by opticyclic** [comment]
The root of the issue is because you have defined a method/function called `shutdown` in CordaRPCOps
https://github.com/corda/corda/blob/master/core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt#L408

Spring auto-detects this and calls it when destroying the bean.
https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html#destroyMethod--

The temporary fix is to change the annotation on the Bean to disable the destroy method

      @Bean(destroyMethod = "")
      public CordaRPCOps proxy() {

However, as with the wrapper approach of not defining CordaRPCOps as a Bean and passing a wrapper instead, that doesn't stop other clients constructing their Beans in the normal way and accidentally shutting down the node.

You should probably rename the `shutdown` function.

**Comment by nargas-ritu** [comment]
We cant rename the function as we have an API compatibility guarantee.

**Comment by opticyclic** [comment]
So because of your API guarantee you are going to leave a security hole where clients can accidentally or maliciously shutdown the node???

The following modules form part of Corda’s public API and we commit to API/ABI backwards compatibility in following releases, **unless an incompatible change is required for security reasons:**
