### ISSUE TITLE
Node Explorer does not display node running network-map-service as a "peer".

### ISSUE THREAD

**Issue by chrisr3** [corda/corda#508]
Create 3 nodes:

Legal Name | Nearest City | Services |
-------- | --------- | --------------
Bank A | Lima | **network map service**, corda.cash, corda.issuer.GBP
Bank B | Cairo | corda.cash, corda.issuer.USD
Notary |  London | corda.notary.validating

Open the Node Explorer for Bank B and examine its network view. Bank A should be displayed in South America, but is actually missing both from the map and from the list of peers.

**Comment by joeldudleyr3** [comment]
The network map node has been removed in Corda 3, so this is no longer an issue.
