### ISSUE TITLE
CN on Corda node SSL cert does not have to reflect the hostname on which the node is running

### ISSUE THREAD

**Issue by ragmondo** [corda/corda#5116]
Although this was resolved on slack, I would like to keep the record of the discussion somewhere a little more permanent - as we will need to refer to this as it is not part of the corda documentation yet (perhaps I'll make a PR to reflect a doc change). 

The SSL standard is that the CN reflect the hostname on which the host is running : https://support.dnsimple.com/articles/what-is-common-name/

Slack link : https://cordaledger.slack.com/archives/CF4F3B264/p1557331648048300

Slack text 

> 1. Corda REQUIRES `organisation, locality and country`. `state, organisational-unit and common name` are optional
> 2. I used deployNodes for bank of corda sample to try and see what certificates it generated. You can put CN=XYZ and the cert is generated with your attributes
> 3. You are correct. Corda does not care if the domain name doesn’t match CN in the SSL cert.  For all intents, I believe the choice was made that identity should be used and an IP/DNS name can change. I would not rely on this for validation

**Comment by nargas-ritu** [comment]
Internal ticket [CORDA-4231](https://r3-cev.atlassian.net/browse/CORDA-4231)
