### ISSUE TITLE
QueryableState interface violates Corda packaging principles

### ISSUE THREAD

**Issue by remmeier** [corda/corda#5127]
One of the packaging guidelines is to keep corda flows and contracts in seperate cordapps (https://r3-cev.atlassian.net/browse/CORDA-2539?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel). This because it is of importance is to keep contract cordapps as small as possible. To my understanding there should be no need to have entities in the contract cordapp. As such it might be useful to have an alternative mean to register and use such entities rather than states having to implement QueryableState.

**Comment by arsalankhalid** [comment]
An interesting idea, but how else can you communicate to the node that it shouldn't use the regular LINEAR STATES or FUNGIBLE table for storing state data? From a glance, it seems logical to to tell the state to ensure a new table specific to the data within the state is created... unless you're pointing to a potential vulnerability/attack vector? There could be a case there.

**Comment by mikehearn** [comment]
Yeah, this is a glitch in the design. It's not a killer problem - entity classes are no big deal and won't be used, but, it'd be nicer to divide things in a more intuitive way.

**Comment by remmeier** [comment]
in our case the entities are not as light as one would desire for inclusion in a contract cordapp. next to the entities we have a mapping framework so that we don't have to do the mapping by hand. and some more things for the rest layer. We make use of the entities as API, so outside of Corda related things, we don't need states, just entities, input to flows and (as for the time being) the flow class to trigger the flow. so yes, deviing things would be nice, help us decoupling quite a few things.

**Comment by remmeier** [comment]
FYI: currently we applied now a workaround by implementing a Mapper contract and discover it with a ServiceLoader. This way we eliminated all the entities from our contract JARs. But we may or may not run into issues with this approach at some point in the future... So we consider it temporary.

A very different approach would be to eliminate the need for entity classes altogether. Most databases support semi-structured formats like JSON (e.g. https://www.postgresql.org/docs/10/datatype-json.html). If one would persists transactions to the database in JSON rather than AMQP the vault itself would become queryable. Alternatively one can go with NOSQL stores and apply similar techniques (but involving a lot more effort and changing setups). Could be interesting for two reasons: simplfy development and and improve consistency by directly running queries against the "vault" without involvment of mapped and potentially migrated data.

**Comment by mikehearn** [comment]
We have to keep the binary around in many cases because the hashes and signatures are important, JSON loses a lot of information that could make it difficult to re-establish the exact original bytes.

That said, if we were pushing the right data structures onto an MQ someone could write an adapter that converted the dbtxns to other formats like JSON, XML etc if someone wanted to use such datastores.

**Comment by remmeier** [comment]
yes, maybe it is an avenue will follow-up to investigate mid-term if there is some more time. since we are end-user facing the topic would also be interesting from that perspective.

**Comment by nargas-ritu** [comment]
Internal link - [CORDA-4229](https://r3-cev.atlassian.net/browse/CORDA-4229)
