### ISSUE TITLE
Update tutorial docs in "Writing a contract"

### ISSUE THREAD

**Issue by alicer3** [corda/corda#5132]
at the tutorial "[writing a contract/checking-the-requirements](https://docs.corda.net/tutorial-contract.html#checking-the-requirements)", the kotlin code is outdated.

In detail, the kotlin code use the function `sumCashBy` in `val received = tx.outputs.map { it.data }.sumCashBy(input.owner)`. And according to tutorial page,

> To calculate how much cash is moving, we use the sumCashBy utility function. 

This `sumCashBy` function was located in `net.corda.contracts.asset.CashKt`, but this class has been removed in corda4.0. Please update the sample code and doc accordingly.

**Comment by lankydan** [comment]
Resolved by - https://github.com/corda/corda/pull/5338
