### ISSUE TITLE
Improvements for containerized/cloud-native deployments

### ISSUE THREAD

**Issue by remmeier** [corda/corda#5139]
Corda comes with a Docker image, but more out-of-the-box Kubernetes/Docker support would be desirable. Shared standards like Kubernetes are helpful to us since we deploy to many different companies. The companies have different infrastructure providers from on-premise to public cloud. As such a shared base layer can save a lot of time. 

- Helm charts for all components
- run Cordapps in dedicated pods (isolation/scalablity/upgradablity/immutablity)
- metrics, tracing & health checks: OpenTracing, Prometheus => https://github.com/corda/corda/issues/4850 => JMX is not overly much "fun" :-)
- allow to do log to console only
- pickup configuration from the environment rather than playing with the config file (official docker image)
- initContainers to initalize a node before its start
- support JVMs more tailored towards containerized operations. Eclipse has with OpenJ9 some extensions that help to greatly reduce the footprint.  Currently at least Quasar has issues with this https://github.com/puniverse/quasar/issues/321.

We now mostly have a setup in this area and could contribute one or the other thing.

**Comment by nargas-ritu** [comment]
Internal ticket [CORDA-4228](https://r3-cev.atlassian.net/browse/CORDA-4228)
