### ISSUE TITLE
dev/prod parity: devMode does too much for us

### ISSUE THREAD

**Issue by remmeier** [corda/corda#5140]
we would like to avoid issues when moving from development to production, as such we strive to keep them as close together as possible. In that regard the devMode does too much for us.
for example, the ClientRelevantError is not necessary when devMode is enabled, which can be confusing when exceptions do work locally but not in integration environments. Or different logging behavior depending on devMode. From a "dev/prod parity" point of view (12 factor apps), the flag should proably not exist.

**Comment by mikehearn** [comment]
ClientRelevantError is scheduled for destruction:

https://r3-cev.atlassian.net/browse/CORDA-2740

You can develop without devMode=true, but it'll be less convenient. What we do want to do is document what it does and break down the different settings into individual flags, so each aspect of devMode is individually controllable (and devMode itself just sets defaults).

I guess I'm tempted to rename this one to something like: "Document and break down devMode so each change is documented and controllable". Would that be OK?

**Comment by nargas-ritu** [comment]
Internal ticket [CORDA-4227](https://r3-cev.atlassian.net/browse/CORDA-4227)
