### ISSUE TITLE
dev/prod parity: support Liquibase for unit testing

### ISSUE THREAD

**Issue by remmeier** [corda/corda#5141]
we stopped using the Hibernate generator for integration/production environments. It would be helpful to be able to get rid of it in unit tests as well to have the same schema setup. There seem two possiblities:

- add Liquibase support to MockNetwork 
- allow external configuration of the data sources used by the nodes of the MockNetwork

depending on whether Liquibase is supposed to target Corda Enterprise-only, one or the other solution would be great.

**Comment by mikehearn** [comment]
I believe this is currently working as designed, but I'll leave it to Tudor to explain the current position on this.

**Comment by tudor-malene** [comment]
Hi @remmeier ,

The current usage of liquibase is:

   - on OS , we use it *only* for the internal Corda tables
   - on Enterprise,  migrations declared by CorDapps  are understood by the node and by the advanced database management tool that we provide.

If you are developing against the Enterprise version, then the migration files that you declare in your CorDapp will be executed in all tests, including the MockNetwork  unit tests.

**Comment by dazraf** [comment]
Can we consider prioritising? I see several issues - please correct me if wrong:
1. Liquibase in 4.6 now has a central role in the mere bootup of any node, whether OS or ENT.
2. It's notably missing from the documentation for mapped schemas: https://docs.corda.net/docs/corda-os/4.6/api-persistence.html#schemas
3. Writing liquibase scripts by hand is labour intensive and error prone. Maintaining them is even more so troublesome.
4. Some of our clients have raised issues in portability of liquibase XML files across databases.  

FWIW, an ideal solution for me is to keep developers focussed directly within Kotlin/Java code with JPA annotations etc. We should have a tool / development phase that can auto generate the database schema and a proposed liquibase xml fileset at a configured logical schema version.

**Comment by nargas-ritu** [comment]
Internal ticket [CORDA-4226](https://r3-cev.atlassian.net/browse/CORDA-4226)
