### ISSUE TITLE
Subscriber for the Vault updates using DataFeed  fails with VaultQueryException if vault record is more than 200 (From rpc connection side)

### ISSUE THREAD

**Issue by manishchainThat** [corda/corda#5157]
Error Description:
**Rpc connection failed to get subscription if  the records for a state in vault is more than 200 ,it fails with vaultQueryException**.
Please find the steps below to reproduce.

1.  load the records more than 200 in vault
2. Now , try to have subscription code by vaultrack
for example:  **final DataFeed<Vault.Page<SomeContractState>, Vault.Update<SomeContractState>>
                riskContractDataFeed =
                proxy.vaultTrack(SomeContractState.class);**
         
  3. We do corda deployment and do lots of transaction.(<200)
  4. we start the spring and everythings works fine
  5. Now , we again some changes in corda and deployment but no reset of data.
  6. After corda deployment ,we did lots of transactions (now we have records more than 200)
  7. let say, now ,we try to restart the spring , it spits the same error at same above line 
  In the steps above , what I think whenever corda restart spring looses all the subscriptions that it has by previous deployment.
 Now If we start the spring, it is trying to have subscription on the whole records presents in vault for a 
  particular state and thats where it catch up in the pagination limit error.\

Error log:

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.chainthat.insurance.placement.server.PlacementObserverCtrl]: Constructor threw exception; nested exception is net.corda.client.rpc.RPCException: Please specify a `PageSpecification` as there are more results [201] than the default page size [200]
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
> 	... 26 more
> Caused by: net.corda.client.rpc.RPCException: Please specify a `PageSpecification` as there are more results [201] than the default page size [200]
> 	at net.corda.client.rpc.internal.RPCClientProxyHandler.invoke(RPCClientProxyHandler.kt:250) ~[corda-rpc-3.3-corda.jar!/:?]
**> 	at com.sun.proxy.$Proxy114.vaultTrack(Unknown Source) ~[?:?]**
> 	at com.chainthat.insurance.placement.server.PlacementObserverCtrl.<init>(PlacementObserverCtrl.java:95) ~[classes!/:?]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
> 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271) ~[spring-beans-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
> 	... 26 more
**> Caused by: net.corda.core.node.services.VaultQueryException: Please specify a `PageSpecification` as there are more results [201] than the default page size [200]**
> [INFO ] 2019-05-10T05:54:30,049Z [main] server.PlacementServer.logStarting - Starting PlacementServer on BM-PartyA-Dev with PID 21799 (/home/ct_admin/CT-IBF-SpringWeb/ct-placement/ct-placement-observer.jar started by ct_admin in /home/ct_admin/CT-IBF-SpringWeb/ct-placement) {}
> [INFO ] 2019-05-10T05:54:30,057Z [main] server.PlacementServer.logStartupProfileInfo - No active profile set, falling back to default profiles: default {}
>

**Comment by shamsasari** [comment]
https://r3-cev.atlassian.net/browse/CORDA-2956

**Comment by mikehearn** [comment]
Hi,

As the error says:

> Please specify a PageSpecification as there are more results [201] than the default page size [200]

If you do that then you will be able to page through the results and handle however many results there are. 

The choice to provide a default value in the API here provides poor usability, and we should fix that, but the current behaviour is working as intended.

**Comment by manishchainThat** [comment]
@mikehearn  The above issue occurs when We try restart the Spring server with vault has more than 200 records.

We have increased it to 1000 as of now .I think eager snapshot of the State has the issue.

Can we expect different Api for this kind of scenarios in next release ??
Thanks !!
