### ISSUE TITLE
Links broken in https://docs.corda.net/head/testnet-explorer-corda.html

### ISSUE THREAD

**Issue by mariowr2** [corda/corda#5172]
In the  [ Using the Node Explorer to test a node on Corda Testnet ](https://docs.corda.net/head/testnet-explorer-corda.html) on the Corda documentation, the guide asks you to perform a ``wget`` in the following paths:

* https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases/net/corda/corda-finance-contracts/5.0-SNAPSHOT/corda-finance-contracts-5.0-SNAPSHOT.jar

* https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases/net/corda/corda-finance-workflows/5.0-SNAPSHOT/corda-finance-workflows-5.0-SNAPSHOT.jar

Both paths return ``404``. The directory ``5.0-SNAPSHOT`` does not appear to exist at all in the ``corda-finance-workflows`` directory at https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases/net/corda/corda-finance-contracts/

**Comment by mikehearn** [comment]
Hi - the /head/ subdirectory is for the docs generated from unreleased master code, so it's expected it'll have broken links in it from time to time. If you just navigate to https://docs.corda.net/ and go from there (or use the version picker), then the pages should work. Or at least broken links there are definitely bugs :)

We should probably exclude /head/ from search engines using robots.txt
