### ISSUE TITLE
CollectSignaturesFlow not aligned with "No need to notarise this transaction" optimization.

### ISSUE THREAD

**Issue by remmeier** [corda/corda#5189]
We hava a transaction where the notary is also involved as signer in the transaction.

The FinalityFlow has an optimization:

```
    private fun needsNotarySignature(stx: SignedTransaction): Boolean {
        val wtx = stx.tx
        val needsNotarisation = wtx.inputs.isNotEmpty() || wtx.references.isNotEmpty() || wtx.timeWindow != null
        return needsNotarisation && hasNoNotarySignature(stx)
    }
```

which triggers for our transaction. Unfortunately, the CollectSignaturesFlow does not honor this optimization and excludes the notary from signing:

```
 val unsigned = if (notaryKey != null) notSigned - notaryKey else notSigned
```

which leads to a transaction where the notary is not involved and fails to receive the transaction.

**Comment by mikehearn** [comment]
https://r3-cev.atlassian.net/browse/CORDA-2980

**Comment by mikehearn** [comment]
Thanks for the bug report!
