### ISSUE TITLE
devMode : true in node.conf does not appear to work. Behaviour remains as false

### ISSUE THREAD

**Issue by GavT** [corda/corda#519]
When altering node.conf file so devMode : true the node continues to behave as is devMode : false

Node.conf capture:
myLegalName : "Corda Node"
nearestCity : "London"
emailAddress : "anonymous@.com"
artemisAddress : "0.0.0.0:10002"
keyStorePassword : "cordacadevpass"
trustStorePassword : "trustpass"
basedir : "Users/gavinthomas/GavCordaNode"
h2port : 11000
webAddress : "0.0.0.0:10004"
extraAdvertisedServiceIds: []
networkMapService : {
    address : "testnet-networkmap.corda.r3cev.com:10002"
    legalName : "R3 TestNet Network Map"
}
useHTTPS : false
rpcUsers=[
		{
			user=corda
			password=rgb
			permissions=[
				StartFlow.net.corda.flows.CashIssueFlow,
				StartFlow.net.corda.flows.CashExitFlow,
				StartFlow.net.corda.flows.CashPaymentFlow
			]
		}
]
devMode : true
//certificateSigningService="https://testnet-doorman.corda.r3cev.com"

Corda node output at startup:
Gavins-MacBook-Pro-2:GavCordaNode gavinthomas$ java -jar corda.jar
objc[7674]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java (0x1032634c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1033e44e0). One of the two will be used. Which one is undefined.

   ______               __
  / ____/     _________/ /___ _
 / /     __  / ___/ __  / __ `/         Kind of like a regular database but
/ /___  /_/ / /  / /_/ / /_/ /          with emojis, colours and ascii art. 😎  
\____/     /_/   \__,_/\__,_/

--- MILESTONE 9 -------------------------------------------------------------------

📚  New! Training now available worldwide, see https://corda.net/corda-training/

Logs can be found in                    : /Users/gavinthomas/GavCordaNode/logs
E 16:01:49 [main] Main.main - Exception during node startup
 java.lang.IllegalArgumentException: Identity certificate not found. Please either copy your existing identity key and certificate from another node, or if you don't have one yet, fill out the config file and run corda.jar --initial-registration. Read more at: https://docs.corda.net/permissioning.html
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:192) ~[node-0.9.1.jar:?]
	at net.corda.node.internal.Node.start(Node.kt:205) ~[node-0.9.1.jar:?]
	at net.corda.node.Corda.main(Corda.kt:101) [node-0.9.1.jar:?]
Gavins-MacBook-Pro-2:GavCordaNode gavinthomas$ java -jar corda.jar --initial-registration

**Comment by GavT** [comment]
May need to delete the certs folder and start again. To be tested. Will report back

**Comment by GavT** [comment]
OK, need to delete / rename certs folder before trying to use devMode : true. Issue solved. Need to update docs

**Comment by gendal** [comment]
Hang on... not so quick...   I also ran into this when I tried to configure my node...    while I was waiting for my cert to be signed, I thought I'd run the node in dev mode and it didn't work.  At the very least, we need to improve the logging...  eg "dev mode not supported when...." or somesuch.
