### ISSUE TITLE
Flow watch command cuts off UUID on small terminals

### ISSUE THREAD

**Issue by MasX** [corda/corda#5202]
The columns in the `flow watch` command are all of the same width. This results in the UUID of flows to be cut off on smaller terminals, even when there is plenty of space to expand into other columns.

I suggest making the columns variable width, so the columns requiring less space take less and everything is still visible.

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4223](https://r3-cev.atlassian.net/browse/CORDA-4223)

**Comment by peterli-r3** [comment]
Hi MasX

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
