### ISSUE TITLE
New Network builder Tool (version 4)

### ISSUE THREAD

**Issue by JoseAntonioBarriga** [corda/corda#5203]
According to Release notes for Corda 4, there is a New Network builder. Can someone point me where I can download it?

![image](https://user-images.githubusercontent.com/32968292/59115668-c68ea100-8917-11e9-90f3-bb9c4739cd0f.png)

**Comment by gendal** [comment]
Hi José - sorry about this. The team are working on getting this released.  Bear with us - but it may be a few days.  cc @anthonykeenan   Have a good weekend!

**Comment by szymonsztuka** [comment]
Corda Network Builder is now available and uses Docker image Corda 4.1 (corda-zulu-4.1) .
The doc page https://docs.corda.net/network-builder.html has the correct link and it has been updated.
