### ISSUE TITLE
Remove the Liquibase from MockNetwork tests

### ISSUE THREAD

**Issue by dazraf** [corda/corda#5216]
When we run MockNetwork tests with Corda 4.x, I see about 5 seconds of Liquibase activity (on a fairly fast Macbook Pro) in the logs. Is it possible to avoid performing the liquibase initialisation for MockNetwork tests?

**Comment by tudor-malene** [comment]
Something has to create the database tables. If liquibase doesn't do that, then hibernate will and spend a couple of seconds on that.
Liquibase spends some time on parsing the changelogs, but actually running the database "create table" statements would take the same.
Ideally that parsing step should be optimised away.

Also, not running liquibase would move the tests further away from production, which is not desired by everyone: https://github.com/corda/corda/issues/5141

**Comment by dazraf** [comment]
Good points, thanks @tudor-malene.  I wonder if we can mute the `info` logs. Haven't had much luck with attuning these with `<root-cordapp-project>/config/test/log4j2.xml`

**Comment by tudor-malene** [comment]
Liquibase has some special logging framework. 
Unfortunately, I don't know what the magic incantation is to change the log level for it.
