### ISSUE TITLE
Issue with tx.fails() inside a tweak ledger during contract testing

### ISSUE THREAD

**Issue by TywinLannister1313** [corda/corda#5225]
I’m not sure if this is a bug but I have discovered an anomaly using tweak() when performing contract tests in Corda version 4 that does not occur in version 3.3.

The issue occurs when I create an invalid transaction that I need to end with tx.fails inside a tweak ledger (l.tweak).  You could argue that no one should ever test this so it is not a bug and I would accept that answer.  I fully appreciate that the test ledger will not behave exactly like a full node and I need to work within those limitations.  Nevertheless I wanted to record the issue in case it is a bug or someone else stumbles onto the same problem.

In this example I perform a double spend within a single transaction  that I need to end the transaction with tx.fails(): 

    private static final TestIdentity alice = new TestIdentity(new CordaX500Name("Alice", "New York", "US"));
    private static final TestIdentity bob = new TestIdentity(new CordaX500Name("Bob", "New York", "US"));
    private static final TestIdentity charlie = new TestIdentity(new CordaX500Name("Charlie", "New York", "US"));
    private static final TestIdentity bank = new TestIdentity(new CordaX500Name("Bank", "New York", "US"), 10L);
    private static final PartyAndReference DUMMY_CASH_REFERENCE = bank.ref((byte)123);
    private MockServices aliceMockServices = new MockServices(alice);

    @Test
    public void doubleSpend() {

        NodeTestUtils.ledger(aliceMockServices, l -> {

            l.transaction("Transfer Money From Bank to Alice", tx-> {
                tx.output(Cash.PROGRAM_ID, "Alice's Money", new Cash.State(
                        issuedBy(DOLLARS(10), DUMMY_CASH_REFERENCE),
                        alice.getParty()));
                tx.attachments(Cash.PROGRAM_ID);
                tx.command(bank.getPublicKey(), new Cash.Commands.Issue());
                return tx.verifies();
            });

            System.out.println();
            System.out.println("Transfer Money From Bank to Alice TransactionID: " + l.retrieveOutputStateAndRef(Cash.State.class,"Alice's Money").getRef());
            System.out.println("Alice's Cash.State: " + l.retrieveOutputStateAndRef(Cash.State.class,"Alice's Money").getState().getData());

            l.tweak(lw->{
                lw.transaction("Alice Double Spend to Bob and Charlie", tx->{

                    tx.input("Alice's Money");

                    tx.output(Cash.PROGRAM_ID, "tweak - Bob's Money", new Cash.State(
                            issuedBy(DOLLARS(10), DUMMY_CASH_REFERENCE),
                            bob.getParty()
                    ));

                    tx.output(Cash.PROGRAM_ID, "tweak - Charlie's Money", new Cash.State(
                            issuedBy(DOLLARS(10), DUMMY_CASH_REFERENCE),
                            charlie.getParty()
                    ));

                    tx.attachments(Cash.PROGRAM_ID);
                    tx.command(alice.getPublicKey(), new Cash.Commands.Move());

                    return tx.fails();
                });

                System.out.println("    Tweak - Alice Transfer to Bob TransactionID: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Bob's Money").getRef());
                System.out.println("    Tweak - Bob's Cash.State: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Bob's Money").getState().getData());
                System.out.println("    Tweak - Alice Transfer to Charlie TransactionID: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Charlie's Money").getRef());
                System.out.println("    Tweak - Charlie's Cash.State: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Charlie's Money").getState().getData());

                lw.fails();
                return Unit.INSTANCE;
            });

            l.verifies();
            return Unit.INSTANCE;
        });
    }

Here is the output:

	Transfer Money From Bank to Alice TransactionID: C45674DDD7752432321DC96AFC039B7F3EF63A68CA384C9C9EFB9BE5364386DC(0)
	Alice's Cash.State: Cash(10.00 USD issued by O=Bank, L=New York, C=US[7B] at O=Bank, L=New York, C=US[7B] owned by O=Alice, L=New York, C=US)

	Tweak - Alice Transfer to Bob TransactionID: 9B33A9431406A39914293142D248148D49D0B47AABD583297E96F04662C82674(0)
	Tweak - Bob's Cash.State: Cash(10.00 USD issued by O=Bank, L=New York, C=US[7B] at O=Bank, L=New York, C=US[7B] owned by O=Bob, L=New York, C=US)
	Tweak - Alice Transfer to Charlie TransactionID: 9B33A9431406A39914293142D248148D49D0B47AABD583297E96F04662C82674(1)
	Tweak - Charlie's Cash.State: Cash(10.00 USD issued by O=Bank, L=New York, C=US[7B] at O=Bank, L=New York, C=US[7B] owned by O=Charlie, L=New York, C=US)

	[ERROR] 14:39:45,729 [Test worker] internal.Verifier.verifyContracts - Error validating transaction 9B33A9431406A39914293142D248148D49D0B47AABD583297E96F04662C82674. [errorCode=1epy9gt, moreInformationAt=https://errors.corda.net/OS/4.0/1epy9gt]
	java.lang.IllegalArgumentException: Failed requirement: for reference [7B] at issuer O=Bank, L=New York, C=US the amounts balance: 1000 - 0 != 2000

The code appears to fail at the call to lw.fails().  I also get the same error if I end with lw.verifies().  

In Corda 3.3 lw.fails() would move on with no issue while lw.verifies() would raise an error.

If I re-write my double spend (like you would see in the Corda documentation) over two transactions where each transaction can tx.verifies()  but get caught by the lw.fails() no error is raised.

    private static final TestIdentity alice = new TestIdentity(new CordaX500Name("Alice", "New York", "US"));
    private static final TestIdentity bob = new TestIdentity(new CordaX500Name("Bob", "New York", "US"));
    private static final TestIdentity charlie = new TestIdentity(new CordaX500Name("Charlie", "New York", "US"));
    private static final TestIdentity doug = new TestIdentity(new CordaX500Name("Doug", "New York", "US"));
    private static final TestIdentity bank = new TestIdentity(new CordaX500Name("Bank", "New York", "US"), 10L);
    private static final PartyAndReference DUMMY_CASH_REFERENCE = bank.ref((byte)123);
    private MockServices aliceMockServices = new MockServices(alice);

    @Test
    public void doubleSpend() {

        NodeTestUtils.ledger(aliceMockServices, l -> {

            l.transaction("Transfer Money From Bank to Alice", tx-> {
                tx.output(Cash.PROGRAM_ID, "Alice's Money", new Cash.State(
                        issuedBy(DOLLARS(10), DUMMY_CASH_REFERENCE),
                        alice.getParty()));
                tx.attachments(Cash.PROGRAM_ID);
                tx.command(bank.getPublicKey(), new Cash.Commands.Issue());
                return tx.verifies();
            });

            System.out.println();
            System.out.println("Transfer Money From Bank to Alice TransactionID: " + l.retrieveOutputStateAndRef(Cash.State.class,"Alice's Money").getRef());
            System.out.println("Alice's Cash.State: " + l.retrieveOutputStateAndRef(Cash.State.class,"Alice's Money").getState().getData());

            l.tweak(lw->{
                lw.transaction("Transfer Money to Bob", tx->{
                    tx.input("Alice's Money");
                    tx.output(Cash.PROGRAM_ID, "tweak - Bob's Money", new Cash.State(
                            issuedBy(DOLLARS(10), DUMMY_CASH_REFERENCE),
                            bob.getParty()
                    ));
                    tx.attachments(Cash.PROGRAM_ID);
                    tx.command(alice.getPublicKey(), new Cash.Commands.Move());

                    return tx.verifies();
                });

                lw.transaction("Attempt a Double Spend to Charlie", tx->{
                    tx.input("Alice's Money");
                    tx.output(Cash.PROGRAM_ID, "tweak - Charlie's Money", new Cash.State(
                            issuedBy(DOLLARS(10), DUMMY_CASH_REFERENCE),
                            charlie.getParty()
                    ));

                    tx.attachments(Cash.PROGRAM_ID);
                    tx.command(alice.getPublicKey(), new Cash.Commands.Move());

                    return tx.verifies();
                });

                System.out.println("    Tweak - Alice Transfer to Bob TransactionID: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Bob's Money").getRef());
                System.out.println("    Tweak - Bob's Cash.State: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Bob's Money").getState().getData());
                System.out.println("    Tweak - Alice Transfer to Charlie TransactionID: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Charlie's Money").getRef());
                System.out.println("    Tweak - Charlie's Cash.State: " + lw.retrieveOutputStateAndRef(Cash.State.class,"tweak - Charlie's Money").getState().getData());

                lw.fails();
                return Unit.INSTANCE;
            });

            l.verifies();
            return Unit.INSTANCE;
        });
    }

Output:

	Transfer Money From Bank to Alice TransactionID: 5A82CAB8F2387A1CC24A3F980E9B542F8F3BEC2BB9DDB1940515570728ED5FC2(0)
	Alice's Cash.State: Cash(10.00 USD issued by O=Bank, L=New York, C=US[7B] at O=Bank, L=New York, C=US[7B] owned by O=Alice, L=New York, C=US)

	Tweak - Alice Transfer to Bob TransactionID: FB6F4762A5A212EBA249FFA74CE4B3F020525ED30288FED29885ED9DDF2F2861(0)
	Tweak - Bob's Cash.State: Cash(10.00 USD issued by O=Bank, L=New York, C=US[7B] at O=Bank, L=New York, C=US[7B] owned by O=Bob, L=New York, C=US)
	Tweak - Alice Transfer to Charlie TransactionID: 3E94DFD221DC0B0AEC08E13FC70DDC22965FCCC438B1070C01A5BBF45CDE7A9A(0)
	Tweak - Charlie's Cash.State: Cash(10.00 USD issued by O=Bank, L=New York, C=US[7B] at O=Bank, L=New York, C=US[7B] owned by O=Charlie, L=New York, C=US)

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4222](https://r3-cev.atlassian.net/browse/CORDA-4222)

**Comment by peterli-r3** [comment]
Hi Tywin

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
