### ISSUE TITLE
Inefficient Attachment Classloading when using data attachments - Corda 4

### ISSUE THREAD

**Issue by dimashblocksure** [corda/corda#5249]
Following our conversation on slack with Tudor Malene we were asked to raise this issue - “No need for code to reproduce it as it’s pretty obvious”.

We have found that in Corda 4.0+ when including an attachment as part of a transaction the performance suffers greatly compared to Corda 3.3. It takes x10 more time to complete a transaction. Including more attachments slows it down even more. 

During debugging, we found that this happens in `AttachmentsClassLoader.kt` between lines 326 and 327: (https://github.com/corda/corda/blame/a4cd85928278c3b45c2fa552a6d69cf45b1bbf13/core/src/main/kotlin/net/corda/core/serialization/internal/AttachmentsClassLoader.kt#L326)

```
val serializers = createInstancesOfClassesImplementing(transactionClassLoader, SerializationCustomSerializer::class.java)
val whitelistedClasses = ServiceLoader.load(SerializationWhitelist::class.java, transactionClassLoader)
       .flatMap { it.whitelist }
       .toList()
```

As our repository classpath is large it keeps rescanning it for every new attachment.

We know that the initial execution will be slow for the first transaction of a specific type. Consequent transactions should be faster because attachments are cached and transactions would use the same attachments. 

**Observed behaviou**r : This recomputes the key to the cache for every individual transaction as we are attaching different images to these transactions. This means that for every new image the classpath will be recomputed which takes 3+ seconds on each node. 

**Expected / Desired Behaviour**: The caching should just use one precomputed value instead and ignore the image attachments as part of the key.

**Comment by rick-r3** [comment]
Hi,

Can I ask, are the other attachments (the large images you mention) ZIP files, or are they JAR files?

**Comment by dimashblocksure** [comment]
Hey Rick, 

Our images are converted into ZIP files.

**Comment by rick-r3** [comment]
Are you on a shared network or do you run your own?  We're considering backwards compatibility issues with other nodes.

**Comment by dimashblocksure** [comment]
Hey Rick,

We are running our own network and we are not part of the Corda Network. 

If possible, could you elaborate more on the backward compatibility issues, please? Thank you.

**Comment by nargas-ritu** [comment]
Internal ticket : [FEAT-537](https://r3-cev.atlassian.net/browse/FEAT-537)

**Comment by peterli-r3** [comment]
Hi Dimashblocksure

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
