### ISSUE TITLE
Node based tests are logged to the temp directory

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#525]
They should be logged to the build directory so that a) it's local to Corda and b) it gets cleaned with gradle clean. I had a few thousand of these directories in my tmp directory on Windows.

Test output is technically a test artifact and TeamCity treats it that way too, so if the logs aren't in the build directory they aren't going to be picked up by TeamCity either when publishing artifacts for debugging purposes.

**Comment by Clintonio** [comment]
Upon further inspection the logs aren't even being written there because `NodeBasedTest` doesn't set the properties for logging. It makes the tests difficult to debug.

**Comment by chrisr3** [comment]
You probably want to add the appropriate `log4j2.xml` file to the integration test resources:
```
diff --git a/client/rpc/build.gradle b/client/rpc/build.gradle
index c6ad9c5..fa69ec7 100644
--- a/client/rpc/build.gradle
+++ b/client/rpc/build.gradle
@@ -20,6 +20,9 @@ sourceSets {
             runtimeClasspath += main.output + test.output
             srcDir file('src/integration-test/kotlin')
         }
+        resources {
+           srcDir "../../config/test"
+        }
     }
     test {
         resources {
```
This enabled logging for `CordaRPCClientTest` as part of my RPC API work. Although #325 would also appear relevant here.
