### ISSUE TITLE
[doc] Tutorial "Structuring a CorDapp#Template CorDapps" needs to be updated

### ISSUE THREAD

**Issue by joshtharakan** [corda/corda#5283]
While following the tutorial in the [Tutorials->Structuring a CorDapp->Template CorDapps](https://docs.corda.r3.com/writing-a-cordapp.html#template-cordapps) the definition of modules are currently as per the release branch release-v2 needs to be updated as per the latest release branch(release-v4) of those templates.

eg:

> The templates are split into two modules:

>A cordapp-contracts-states module containing the contracts and states
>A cordapp module containing the remaining classes that depends on the cordapp-contracts-states module

**Comment by joshtharakan** [comment]
I can make a PR to update the docs

**Comment by nargas-ritu** [comment]
Templates were updated
