### ISSUE TITLE
while starting corda node getting internal.NodeStartupLogging.invoke - Exception during node startup [errorCode=36pu1l, moreInformationAt=https://errors.corda.net/OS/4.0/36pu1l]

### ISSUE THREAD

**Issue by karankk1991** [corda/corda#5296]
Thank you for choosing to report an issue with Corda. 

When reporting an issue please make sure it contains;

while i try to run corda node i am getting internal.NodeStartupLogging.invoke - Exception during node startup [errorCode=36pu1l, moreInformationAt=https://errors.corda.net/OS/4.0/36pu1l]
and node goes in CrashLoopBackOff 
I am using kubernetes

**Comment by nargas-ritu** [comment]
Not enough information.
