### ISSUE TITLE
Notary

### ISSUE THREAD

**Issue by supersbbb** [corda/corda#53]
Hi there,

After read the tech white paper, i have one question about how notary works. If two parties has done several transactions via different notaries, how would a third party join them? Can someone explain the procedure please?

**Comment by mikehearn** [comment]
Hi @supersbbb - this sort of question is best put on our discussion forum:

http://discourse.corda.net/

Briefly, the answer to your question is that you use the NotaryChangeFlow. Doing it manually is a bit low level. In future we hope to automate this by letting you configure things like preferred notaries, so the vault can pick one. But we don't support commits across two notaries. All input states must be controlled by a single notary and if you don't have that situation, you have to move states around until you do.
