### ISSUE TITLE
Improve participants JavaDocs

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5302]
The Javadocs for the participants on a state are not clear.

https://docs.corda.net/api/kotlin/corda/net.corda.core.contracts/-contract-state/participants.html

> The list of participants is required for certain types of transactions. For example, when changing the notary for this state,

This doesn't give enough information about the actual purpose of the participants.

The info on the doc site is clearer 
https://docs.corda.net/api-states.html

> participants is a List of the AbstractParty that are considered to have a stake in the state. Among other things, the participants will:
> 
>     * Usually store the state in their vault (see below)
>     * Need to sign any notary-change and contract-upgrade transactions involving this state
>     * Receive any finalised transactions involving this state as part of FinalityFlow / ReceiveFinalityFlow
> 
> Whenever a node records a new transaction, it also decides whether it should store each of the transaction’s output states in its vault. 
> 
>         * If the state is an OwnableState, the vault will store the state if the node is the state’s owner
>         * Otherwise, the vault will store the state if it is one of the participants
> 
> States that are not considered relevant are not stored in the node’s vault. However, the node will still store the transactions that created the states in its transaction storage.
> 

You should update the javadocs so that it provides more detail like the online docs.

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4220](https://r3-cev.atlassian.net/browse/CORDA-4220)
