### ISSUE TITLE
 Issue: VaultQueryCriteria(status=ALL) mixed with CustomQueryCriteria returns only UNCONSUMED statues

### ISSUE THREAD

**Issue by kaushikb92** [corda/corda#5328]
Corda version used: 4.1

Issue: VaultQueryCriteria(status=ALL) mixed with CustomQueryCriteria returns only UNCONSUMED statues

Steps to reproduce:

Clone modified version of official Corda example from 
[GitHub] (https://github.com/kaushikb92/samples.git)

Checkout to branch `bug/VaultStateStatusAll`. 

I've edited in cordapps-example/contracts-kotlin/IOUContracts.kt, added cordapps-example/contracts-kotlin/ExampleFlowTest.kt and cordapp-example/workflows-kotlin/src/main/kotlin/com/example/flow/ExampleUpdateFlow.kt

Open cordapps-example/contracts-kotlin/ExampleFlowTest.kt and run the test.
`resultAll` has a size of 5 - normal behaviour.
`resultAllFiltered`: Expected to have a size of 5, actually has a size of 1. 

After going deep I found out that in `HibernateQueryCriteriaParser` (refer to https://github.com/corda/corda/blob/master/node/src/main/kotlin/net/corda/node/services/vault/HibernateQueryCriteriaParser.kt) at line 267, its hard-coded to query on `UNCONSUMED` states only.
```
var stateTypes: Vault.StateStatus = Vault.StateStatus.UNCONSUMED
```

**Comment by mattbradburyuk** [comment]
HI Kauskik, 

The constructor for VaultCustomQueryCriteria() looks like this: 
QueryCriteria.kt (line 340):
```
constructor(
                expression: CriteriaExpression<L, Boolean>,
                **status: Vault.StateStatus = Vault.StateStatus.UNCONSUMED**,
                contractStateTypes: Set<Class<out ContractState>>? = null
        ) : this(expression, status, contractStateTypes, Vault.RelevancyStatus.ALL)
```
So your query as it stands in the test will only bring back unconsumed tests. If you add in setting the status, then the result is the full 5 states, like this:  
ExampleFlowTest.kt (line 80):
```
        var resultAllFiltered = playerA.services.vaultService.queryBy<IOUState>(
                criteria = QueryCriteria.VaultQueryCriteria(status = Vault.StateStatus.ALL)
                        .and(QueryCriteria.VaultCustomQueryCriteria(
                                IOUSchemaV1.PersistentIOU::value.lessThanOrEqual(5),
                                **status = Vault.StateStatus.ALL**
                        ))).states
        println(resultAllFiltered)
        assertEquals(resultAllFiltered.size, 1)
```
(This will fail because I haven't changed the assertion)
