### ISSUE TITLE
Missing Generated.class from deterministick JDK

### ISSUE THREAD

**Issue by lucacampanella** [corda/corda#5332]
Hi everyone,
Testing out the deterministic JDK to compile contract code I realized that there is no Generated.class annotation in the javax package in the deterministic JDK. For this reason my (otherwise deterministic) code doesn't compile. Is there a reason why this annotation was excluded? And if not, can it be integrated? 
Thanks!
Keep up the good work

**Comment by chrisr3** [comment]
Hi Luca,

Do you _need_ `@javax.annotation.Generated` in the `deterministic-rt.jar`? As I understand it, itn is also available via this Maven artifact:
> javax.annotation:javax.annotation-api:1.3.2

Cheers,
Chris

**Comment by nargas-ritu** [comment]
Workaround provided above

**Comment by chrisr3** [comment]
_Yikes!_ A voice from 2019...
