### ISSUE TITLE
Logo image is broken

### ISSUE THREAD

**Issue by mbrukman** [corda/corda#5340]
[`README.md`][readme] specifies the logo as follows:

> ```
> <p align="center">
>   <img src="https://www.corda.net/wp-content/uploads/2016/11/fg005_corda_b.png" alt="Corda" width="500">
> </p>
> ```

However, that image URL currently returns 404, which makes the README for the project look suboptimal. Please update the URL to point to the current logo location, and also, consider checking in the logo into the repo so that it doesn't disappear due to a website redesign.

[readme]: https://github.com/corda/corda/blob/a2cde10df3adc6faa87946f601861c1774b6970f/README.md

**Comment by lankydan** [comment]
The readme looks fine to me, but yes you are correct, the link is broken and should be corrected. Keeping the logo out of the repo just helps reduce how fatty the repo is to download.

**Comment by bergmannlucas** [comment]
Hello! I would like to work on this issue.
Should this one be the new logo? https://www.corda.net/wp-content/themes/corda/assets/images/crda-logo-big.svg

**Comment by mikehearn** [comment]
@lankydan You could have just fixed it ;)
