### ISSUE TITLE
Checkpoints are not removed if flow failed due to transaction rollback

### ISSUE THREAD

**Issue by adamturski** [corda/corda#5350]
In Corda 3.3 (git tag **release-V3.3**) we found a bug which causes that failed flow is not removed from node_checkpoints table. Basically in code we can see that we remove checkpoint but in the finally block we rollback transaction in which there is a DELETE checkpoint statement.

net.corda.node.services.statemachine.StateMachineManagerImpl:
* line 450 - checkpoint removal: checkpointStorage.removeCheckpoint(it)
* line 460 - transaction rollback: fiber.rollbackTransaction()

`fiber.actionOnEnd = { result, propagated ->
            try {
                mutex.locked {
                    stateMachines.remove(fiber)?.let { checkpointStorage.removeCheckpoint(it) }
                    notifyChangeObservers(StateMachineManager.Change.Removed(fiber.logic, result))
                }
                endAllFiberSessions(fiber, result, propagated)
            } finally {
                if (result.isSuccess) {
                    fiber.commitTransaction()
                    totalFinishedFlows.inc()
                    unfinishedFibers.countDown()
                } else {
                    fiber.rollbackTransaction()
                }
                decrementLiveFibers()
            }
        }` 

Steps to reproduce the issue:
1. Create a simple flow which will throw an exception or choose exisitng one and make it fail.
2. Start node
3. Run below query which should return 0
`select count(*) from node_checkpoints`
4. Start the flow and wait until it fails
5. Observe logs and extract flow id (statemachinerun id)
6. Stop node
7. Run below query which should return 1
`select count(*) from node_checkpoints`
8. Start node
9. Check in logs that after restart Corda resumed suspended flow with the same id

**Comment by adamturski** [comment]
I have a possible fix for that, but I need to make 1 test green.

**Comment by mikehearn** [comment]
Does this bug show up with the latest code? The open source project doesn't support 3.x anymore.

**Comment by adamturski** [comment]
@mikehearn This bug doesn't show up on Corda 4.
