### ISSUE TITLE
Feature Request - Reverse Lookup State Pointers

### ISSUE THREAD

**Issue by MrMatthewLayton** [corda/corda#5354]
# Reverse Lookup State Pointers

Corda currently supports `StatePointer<T>` - a mechanism whereby the current state can refer to another state of type `T`; more specifically:

 - `StaticPointer<T : ContractState>` - refers to a specific state version by `StateRef`.
 - `LinearPointer<T : LinearPointer>` - refers to the latest state version by `UniqueIdentifier`

I would like Corda to support reverse-lookup state pointers, such that rather than the current state referring to another state (A -> B), a reverse-lookup state pointer would find all other states referring to itself (A <- [B, B, B, ...])

### Rationale/Example

I have an obligation to which certain participants need to attest...they can either:
1. Consume the state, add their attestation, producing a new state _(which introduces the potential for race conditions on spent states)_
2. Just refer to the obligation in an _attestation_ state, and perform the lookup manually.

The introduction of a reverse-lookup state pointer would just alleviate the need for manual vault queries (similar to the way state pointers do).

Firstly, an attestation state could be modelled to point to a specific version of a state by state ref:

```
data class AttestationState(
    val obligation: StaticPointer<ObligationState>, 
    val status: AttestationStatus = AttestationStatus.OK
) : ContractState { ... }
```

The obligation state would then contain a property that represents a resolvable vault lookup _(note, it's not a constructor parameter, because you don't *know* what you're looking for - that's the job of the reverse lookup to handle for you)_

```
data class ObligationState(...) {
    val attestations: Iterable<AttestationState>
        get() = ReverseLookupStatePointer.all(AttestationState::obligation)
}
```

This could then be called...

```
val attestations: Iterable<AttestationState> = obligation.attestations.resolve(serviceHub)
```

Just to add some extra thought on `ReverseLookupStatePointer`...

```
class ReverseLookupStatePointer {
    companion object {
        fun <T, R : ContractState> all(property: KProperty1<T, StatePointer<R>): ... {
           // uses KProp to identify which column of type StatePointer<R> to query
           // returns a reference to something that can be resolved to a collection.
        }
    
        fun <T, R : ContractState> single(property: KProperty1<T, StatePointer<R>): ... {
            // uses KProp to identify which column of type StatePointer<R> to query
           // returns a reference to something that can be resolved to a single item, or fails if there is more/less than one.
        }
    }
}
```

I guess one thing that might need to be taken into consideration, given that the proposal needs to look up custom fields is - can this be done without the attestation state needing to implement QueryableState?

**Comment by gendal** [comment]
Thanks for this proposal! I'll let the team respond formally but I just wanted to check something for my own understanding.  I'm trying to get my head around how this would work from a consensus perspective.  In the LinearPointer / Reference States case, we can ensure all parties (at all times) agree that a particular state was indeed the most current at the time the transaction was notarised by requiring the notary to attest to this fact (hence the inclusion of reference states as a new input state type in transactions.... it is how we signal to the notary "please only sign this tx if the listed reference states are indeed the most current ones).  We have to achieve the same thing here, right? Since different nodes could have different things in their vaults at any given instant and so calls to resolve() could yield different answers to different parties at different times. Are you implicitly saying that the list of Attestations arising from resolve() should themselves be included as reference state inputs to any transaction which includes the Obligation State in your example? That would ensure currentness I guess.  But it doesn't assure _completeness_. But maybe that doesn't matter?  Just thinking out loud for now.

**Comment by lankydan** [comment]
My impression was that this was a feature that revolved around being able to query the vault for relevant states. Although it's usefulness for proposing transactions might be limited (I would need to think about this more), being able to do queries like this is likely to be helpful.

In other words, I want to output a report of all A states that reference B (the parent). Which would result in a query of, get me all the things that reference B (the children).

Hopefully, I am thinking about this in the right way 🙂.

**Comment by gendal** [comment]
yes... but if it is called by a method on a state object, as is proposed above, then it can be called from within a verify() function, right?  Which means we need to ensure all parties (at all times) get the same answer when running verify() on a notarised transaction that contains one of these things. But if the answer depends on the contents of a node's vault, different parties will get different answers.  We ensure this with reference states by requiring the "answer" to the query is included as a (reference) input to any tx that relies on it... hence ensuring the tx can only be notarised if the answer is 'correct' (as in current) at the time of notarisation. I'm trying to think through how/if we could achieve the same thing here. Maybe I'm worrying over nothing though?

**Comment by gendal** [comment]
we've just discussed this in person and I now understand the use-case better.  The motivating scenario is in the flow level, not the contract level.  Effectively: there are classes of apps where being able to take a state and ask one's _own vault_ "which states in my vault have pointers to this state?" would be useful.   

Now, to support this, I guess we'd need to record this information at the time we persist any given state... so we'd be incurring an ongoing cost.  So I suppose the question is how common this kind of lookup would be...   ie is it better to provide a recommended pattern to those app developers that need it to show how to record this information themselves in their own table?  Or is it important/common enough to be a standard vault feature.  And, if so, we'd need to ensure if could never be called from contract logic of course.

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4215](https://r3-cev.atlassian.net/browse/CORDA-4215)
