### ISSUE TITLE
StatePointerSearch - Exception during resolveStatePointers - Corda 4.1

### ISSUE THREAD

**Issue by trferreira-BR** [corda/corda#5362]
Hi Everyone,

Since I migrated our CorDapp from Corda 3.2 to 4.1 OpenSource, We've started receiving an exception origined from a new API related to StatePointer.
In transactions in our CorDapp don't have at least one transaction using reference state in any Transaction.

There are moments that the transaction is OK and there are moments that transaction is not OK throwing an exception below.

```
java.util.ConcurrentModificationException: null
	at java.util.Vector$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_221]
	at java.util.Vector$Itr.next(Unknown Source) ~[?:1.8.0_221]
	at net.corda.core.internal.StatePointerSearch.handleIterable(StatePointerSearch.kt:109) ~[corda-core-4.1.jar:?]
	at net.corda.core.internal.StatePointerSearch.handleObject(StatePointerSearch.kt:73) ~[corda-core-4.1.jar:?]
	at net.corda.core.internal.StatePointerSearch.handleField(StatePointerSearch.kt:85) ~[corda-core-4.1.jar:?]
	at net.corda.core.internal.StatePointerSearch.search(StatePointerSearch.kt:92) ~[corda-core-4.1.jar:?]
	at net.corda.core.transactions.TransactionBuilder.resolveStatePointers(TransactionBuilder.kt:538) ~[corda-core-4.1.jar:?]
	at net.corda.core.transactions.TransactionBuilder.addOutputState(TransactionBuilder.kt:612) ~[corda-core-4.1.jar:?]
	at br.com.test.flow.IssueFlow$Initiator.executeMoviment(IssueFlow.kt:268) ~[?:?]
	at br.com.test.flow.IssueFlow$Initiator.call(IssueFlow.kt:178) ~[?:?]
	at br.com.test.flow.IssueFlow$Initiator.call(IssueFlow.kt:54) ~[?:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:269) ~[corda-node-4.1.jar:?]
```

We reproduce this exception in Corda Open Source 4.1

**Comment by praveennagpal** [comment]
Is there any update on this issue?  We too are encountering this issue while running Junits on Corda 4.1 and the error is quite random.

**Comment by shamsasari** [comment]
Can you provide an example contract state which has this issue?

**Comment by trferreira-BR** [comment]
Hi Shams,
This problem is occurring when We are trying to create new states on Ledger through a batch process (e.g: 10 new states, 20 new states and so on). 
How about the frequency, Sometimes it happens and sometimes it doesn't happen. I've detected it through at JUnit

I decided to deep in it to find and understand better what kind of problem is hapenning and I found some important information. I'll describe below:

1) In my scenario, My State doesn't have any StatePointer
2) It isn't specific with Corda Open Source 4.1. In Corda Enterprise 4.1 it throws too.
3) About your requisition to share my state here: I can't share here at GitHub because it pertains from a project developed by a Financial Institution (I'll share by email with you and R3 Support 
Team because We also have a relation between customer, besides my role in Corda community as contributor)
4) I cloned Corda Open Source and I changed the code. The handleIterable method in StatePointerSearch.kt was altered with a try/catch to inspect content:

```
    private fun handleIterable(iterable: Iterable<*>) {
        try{
            iterable.forEach { obj -> handleObject(obj) }
        } catch (e: ConcurrentModificationException){
            e.printStackTrace()
        }
    }
```
	
5) As you could see in log trace posted, the exception is started from a Iterable. The most curious and strange that I caught during a debug: an Iterable received in handleIterable method 
has 12311 elements with packages and class not related to as input or output possibly recognize as StatePointer.

Below is a part of list captured where the size is 12311 (I will share the original by e-mail)

![StatePointer1](https://user-images.githubusercontent.com/34104414/64173263-4059fc00-ce2d-11e9-8d26-42734691141b.jpg)
 
![StatePointer2](https://user-images.githubusercontent.com/34104414/64173335-6b445000-ce2d-11e9-9434-314a80736439.jpg)

![StatePointer3_modified](https://user-images.githubusercontent.com/34104414/64173453-b78f9000-ce2d-11e9-9337-0b0014852409.jpg)

[class worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager,
  class worker.org.gradle.process.internal.streams.EncodedStream$EncodedInput,
  class co.paralleluniverse.fibers.instrument.JavaAgent,
  class co.paralleluniverse.asm.ClassVisitor,
  class co.paralleluniverse.asm.ClassWriter,
  class co.paralleluniverse.fibers.instrument.JavaAgent$2,
  interface co.paralleluniverse.fibers.instrument.Log,
  class co.paralleluniverse.concurrent.util.MapUtil,
  class co.paralleluniverse.fibers.instrument.QuasarInstrumentor,
  class co.paralleluniverse.fibers.instrument.LabelSuspendableCallSitesClassVisitor,
  class co.paralleluniverse.fibers.instrument.DBClassWriter,
  class co.paralleluniverse.asm.util.CheckClassAdapter,
  class co.paralleluniverse.fibers.instrument.InstrumentClass,
  class co.paralleluniverse.asm.ClassReader,
  class co.paralleluniverse.fibers.instrument.OffsetClassReader,
  class co.paralleluniverse.fibers.instrument.SuspOffsetsAfterInstrClassVisitor,
  class co.paralleluniverse.asm.util.TraceClassVisitor,
  interface co.paralleluniverse.fibers.instrument.SuspendableClassifier,
  class co.paralleluniverse.common.util.SystemProperties,
  class co.paralleluniverse.fibers.instrument.LogLevel,
  class co.paralleluniverse.fibers.instrument.SuspendableHelper,
  class co.paralleluniverse.fibers.instrument.JavaAgent$1,
  class co.paralleluniverse.fibers.instrument.Retransform,
  class co.paralleluniverse.asm.util.Printer,
  class co.paralleluniverse.asm.util.Textifier,
  class co.paralleluniverse.fibers.instrument.JavaAgent$Transformer,
  class co.paralleluniverse.fibers.instrument.Classes,
  class co.paralleluniverse.fibers.instrument.Classes$BlockingMethod,
  class co.paralleluniverse.fibers.RuntimeSuspendExecution,
  class co.paralleluniverse.fibers.SuspendExecution,
  interface co.paralleluniverse.fibers.Suspendable,
...
  class com.esotericsoftware.reflectasm.PublicConstructorAccess,
  class org.hibernate.query.criteria.internal.AbstractManipulationCriteriaQuery,
  class org.hibernate.query.criteria.internal.CriteriaDeleteImpl,
  class org.hibernate.query.criteria.internal.AbstractManipulationCriteriaQuery$1,
  class org.hibernate.query.criteria.internal.AbstractManipulationCriteriaQuery$1$1,
  class org.hibernate.hql.internal.ast.tree.DeleteStatement,
  class org.hibernate.hql.internal.ast.exec.BasicExecutor,
  class org.hibernate.hql.internal.ast.exec.DeleteExecutor,
  class org.objectweb.asm.ClassVisitor,
  class org.objectweb.asm.ClassWriter,
  class org.hibernate.action.internal.BulkOperationCleanupAction,
  class org.hibernate.action.internal.BulkOperationCleanupAction$1,
  class org.objectweb.asm.AnnotationVisitor,
  class org.objectweb.asm.AnnotationWriter,
  class org.hibernate.engine.spi.ActionQueue$AbstractTransactionCompletionProcessQueue,
  class org.hibernate.engine.spi.ActionQueue$AfterTransactionCompletionProcessQueue,
  class org.objectweb.asm.FieldVisitor,
  class org.objectweb.asm.FieldWriter,
  class net.corda.node.services.statemachine.Action$ExecuteAsyncOperation,
  class org.objectweb.asm.MethodVisitor,
  class net.corda.node.services.statemachine.StateMachineManager$Change$Removed,
  class net.corda.node.services.statemachine.FlowStateMachineImpl$run$2,
  class net.corda.node.services.persistence.DBTransactionStorage$getTransaction$1,
  class org.objectweb.asm.MethodWriter,
  class org.objectweb.asm.ByteVector,
  class org.objectweb.asm.Item,
  class reflectasm.java.lang.StringConstructorAccess,
  class com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy$1,
  class reflectasm.java.util.HashMapConstructorAccess,
  class reflectasm.java.util.ArrayListConstructorAccess,
  class reflectasm.java.util.LinkedHashMapConstructorAccess,
  class rx.functions.Actions$EmptyActionConstructorAccess,
  class rx.internal.util.SubscriptionListConstructorAccess,
  class kotlin.coroutines.jvm.internal.DebugMetadataKt]

**6) In my opinion/sugestion: The method resolveStatePointers specifically at StatePointerSearch(contractState).search() should be controlled 
and stricted better using blackListedPackages attribute as a supporter to identified and filter what is the fact a possibly State identified 
as a Pointer. In addition, this point may generate a performance problem and a bottleneck unnecessary.**

Please, Let me know if I can help with more information
Kind regards

**Comment by shamsasari** [comment]
@trferreira-BR, to confirm did filtering out the synthetic fields fix the issue?

**Comment by roger3cev** [comment]
This could should be deprecated and replaced with @r3domfox 's code.

**Comment by trferreira-BR** [comment]
Hi Shams,

Yes, the issue was the synthetic field. To test if the problem would be resolved, I've changed inserting the follow condition in StatePointerSearch.addAllFields:
**if (field.isSynthetic || field.isStatic) return@mapNotNull null**

```
    // Helper for adding all fields to the queue.
    private fun ArrayDeque<FieldWithObject>.addAllFields(obj: Any) {
        val fields = getAllFields(obj::class.java)

        val fieldsWithObjects = fields.mapNotNull { field ->
            // Ignore classes which have not been loaded.
            // Assumption: all required state classes are already loaded.

            // Don't allow synthetic and static fields to be inserted
            if (field.isSynthetic || field.isStatic) return@mapNotNull null

            val packageName = field.type.packageNameOrNull
            if (packageName == null) {
                null
            } else {
                FieldWithObject(obj, field)
            }
        }
        addAll(fieldsWithObjects)
    }
```

Thank you
Thiago

**Comment by shamsasari** [comment]
https://r3-cev.atlassian.net/browse/CORDA-3188

**Comment by trferreira-BR** [comment]
To complement: After I changed the code, compile and install locally, I executed all tests in corda-core module in Corda Open Source at GitHub and all of them have finished with successful.
