### ISSUE TITLE
Node suspends when starting flow from Corda service (Corda v4, 4.1)

### ISSUE THREAD

**Issue by piotr-morozov** [corda/corda#5372]
We've discovered problem with starting flow from Corda Service using **Corda versions 4 and 4.1**
Modified version of `yo-cordapp` official sample application reveals the details of the problem (see commit details: https://github.com/piotr-morozov/samples/commit/29709dba807f426998b4ac432376f10eebbf7548)

**Steps to reproduce:**
1) clone forked `corda/samples` repository: https://github.com/piotr-morozov/samples.git
2) checkout branch `release-V4-service-starts-flow-issue`
3) build and deploy `yo-cordapp` application, run nodes
4) on PartyA node shell run command: `flow start YoFlow target: PartyB, yo: Request`

**Expected result:**

PartyB sends "Response" Yo message to PartyA, 
PartyA can see the new Yo state in the vault (command: `run vaultQuery contractStateType: net.corda.yo.YoState`)

**Actual result:** (logs attached: [4.1_logs.zip](https://github.com/corda/corda/files/3525157/4.1_logs.zip))

PartyB node suspends. It is not possible to run any flow on PartyB node.
PartyA does not receive "Response" Yo message from PartyB
PartyA does not see any Yo states in the vault.

At the same time, when corresponding changes are applied to `yo-cordapp` sample application running on **Corda version 3, 3.1** - no problem appears (see commit: https://github.com/piotr-morozov/samples/commit/016c10d7b86723cae99661acfcaddeeb9b87acd6)

**Steps to reproduce:**

1) clone forked corda/samples repository: https://github.com/piotr-morozov/samples.git
2) checkout branch `release-V3-service-starts-flow-issue` (for Corda v3) or `release-V3.1-service-starts-flow-issue` (for Corda v3.1)
3) build and deploy 'yo-cordapp' application, run nodes
4) on PartyA node shell run command: `flow start YoFlow target: PartyB, yo: Request`

As a result, PartyB sends "Response" Yo message to PartyA, PartyA receives the message and new Yo state can be seen in the vault.

**Comment by chrisciszak** [comment]
It's because the service and the initiated flow work on the same thread and you've got a deadlock. 

If calling a flow from within CordaService, you need to call in another thread.

companion object {
        val executor: Executor = Executors.newFixedThreadPool(8)!!
    }

fun()
{
executor.execute {
startFlow()
}
}

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4214](https://r3-cev.atlassian.net/browse/CORDA-4214)
