### ISSUE TITLE
Check Types When Calling Flows via RPC With Java

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5420]
With Kotlin you can start a flow from RPC with `startFlowDynamic` or `startFlow`.

The latter enables type safety via [these extension functions](https://github.com/corda/corda/blob/master/core/src/main/kotlin/net/corda/core/messaging/CordaRPCOps.kt#L475-L538).

However, when you use Java the only option available is `startFlowDynamic`.

Currently, if you send the wrong args to a flow via rpc you get this error:

>[rpc-server-sender] amqp.CachingCustomSerializerRegistry.doFindCustomSerializer - Illegal custom serializer detected for class net.corda.core.flows.IllegalFlowLogicException: net.corda.serialization.internal.amqp.custom.ThrowableSerializer

It would be useful to have similar type checking functions available in Java.

At the very least, to make fixing code easier, the runtime errors should say what the args should be and what you have sent by mistake.

**Comment by lolo8304** [comment]
I agree. We had the same issue and implemented in a Controller class a support fully in java with reflection. 

Checkout [cordalo.ch](www.cordalo.ch) framework and the controller

https://github.com/cordalo-ch/cordalo/blob/4.1/corda-common-client/src/main/java/ch/cordalo/corda/common/client/webserver/CordaloController.java

Our whole framework code base is java

**Comment by nargas-ritu** [comment]
Internal ticket- [ENT-6695](https://r3-cev.atlassian.net/browse/ENT-6695)

**Comment by peterli-r3** [comment]
Hi opticyclic

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
