### ISSUE TITLE
Make RPC Testing Easier

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5461]
Currently there seem to be 3 options for testing Corda:

1. MockNetwork
2. Driver DSL
3. Manually start a network then run tests

The MockNetwork is useful for testing flows but it doesn't implement an RPC interface so you can't use it in your Spring REST API tests.

The Driver DSL has an RPC interface but all the work appears to have to be done in the dsl closure which means you can't get the CordaRPCOps proxy out of the dsl and inject it into Spring tests because the dsl shuts down the nodes when you exit the closure.

Currently, you have to initiate the dsl at the start of every single test which is super slow as it has to start the nodes every single time, instead of once at the start of a group of tests.

Manually starting a network requires a lot of steps and is not really appropriate for developer testing.

There needs to be a _simple_ way to initialise a test network in the setup phase and _easily_ inject the components into _multiple_ tests.

**Comment by mikehearn** [comment]
Yes, I have no idea why the driver DSL is so picky about tying lifetime to scope. It should be easy to break that link with some new API.

**Comment by manosbatsis** [comment]
A hack really, but corbeans launches a network using the node driver DSL [1] via coroutines and keeps It running while REST integration tests  [2] are run against Spring Boot via JUnit 5. Corbeans is responsible for taking care of RPC connections from within Spring Boot but that's natural in my case where integration tests are not RPC centric. A similar hack is perfectly feasible of course, but still a hack!

[1] https://github.com/manosbatsis/corbeans/blob/master/corbeans-spring-boot-starter-test/src/main/kotlin/com/github/manosbatsis/corbeans/test/integration/NodeDriverHelper.kt
[2] https://github.com/manosbatsis/corbeans/blob/master/corbeans-spring-boot-starter-test/src/main/kotlin/com/github/manosbatsis/corbeans/test/integration/CorbeansSpringExtension.kt

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4208](https://r3-cev.atlassian.net/browse/CORDA-4208)
