### ISSUE TITLE
Open Finality Transaction Checking

### ISSUE THREAD

**Issue by MrMatthewLayton** [corda/corda#5484]
# Open Finality Transaction Checking

Sometimes there are cases where it would be useful to allow counter-parties to check transactions before recording them and any relevant states to the vault. Usually this would be performed during the `SignTransactionFlow` step; for example:

```kotlin
@Suspendable
override fun call(): SignedTransaction {
    val transaction = subFlow(object : SignTransactionFlow(session) {
        override fun checkTransaction(stx: SignedTransaction) {
            // Add your pre-signature transaction checks here...
        }
    })
    
    return subFlow(ReceiveFinalityFlow(session, transaction.id))
}
```

## Problem

There are cases where counter-parties are required to record transactions and relevant states, but don't need to sign the transaction. This can already be achieved by designing the flow to remove the `SignTransactionFlow` step; for example:

```kotlin
@Suspendable
override fun call(): SignedTransaction {
	// SignTransactionFlow has been removed (but so has transaction checking!)    
    return subFlow(ReceiveFinalityFlow(session, transaction.id))
}
```

Notice that whilst counter-parties are no longer required to sign the transaction, they can't check it either, and I believe there are cases where we might want to still perform checks before recording the transaction and relevant states - In fact, the underlying `ReceiveTransactionFlow` contains a `checkBeforeRecording` function, but since the `ReceiveFinalityFlow` class is sealed, this function can't be overridden.

## Proposal

My proposal is to open the `ReceiveFinalityFlow` in such a way that it maintains backwards compatibility with previous versions of the flow, but allows pre-finality transaction checking to be achieved.

```kotlin
open class ReceiveFinalityFlow @JvmOverloads constructor(
	private val otherSideSession: FlowSession,
	private val expectedTxId: SecureHash? = null,
	private val statesToRecord: StatesToRecord = ONLY_RELEVANT
) : FlowLogic<SignedTransaction> {

	@Suspendable
	override fun call(): SignedTransaction {
	    return subFlow(object : ReceiveTransactionFlow(
	        otherSideSession, 
	        checkSufficientSignatures = true, 
	        statesToRecord = statesToRecord
	    ) {
            override fun checkBeforeRecording(stx: SignedTransaction) {
                checkTransaction(stx)
                require(expectedTxId == null || expectedTxId == stx.id) {
                    // message truncated for clarity here.
                }
            }
        })
	}
	
	open fun checkTransaction(stx: SignedTransaction) = Unit
}
```

This implementation allows the flow to be used as-is, or extended to include transaction checking before finality.

**Comment by gendal** [comment]
Hi @series0ne...   just catching up with my backlog after vacation last week.   Imagine this were done and a recipient decides to reject the tx in the checkBeforeRecording step, what would you want to happen? Just suppress the recording of the tx on that node? Record the tx (to enable future tx resolution, etc) but don't populate the vault? Something else?

**Comment by MrMatthewLayton** [comment]
Hi @gendal I sort of feel like those decisions should be open to the consumer. In my case I've written a custom flow that does this, and `checkTransaction` throws a `FlowException` if some important part of the transaction isn't relevant to the counter-party.

That said, I like your ideas of suppressing recording the transaction or recording but not populating the vault. If this could also become more open and configurable per use case, I think you're onto a winner!

**Comment by gendal** [comment]
Thanks for this. I guess what I was driving at was: once a (valid per the rules of its contracts and correctly signed) transaction is finalised, the time for opinions is over: the transaction is valid. One or more participants might not _like_ that fact but if verify() succeeds and all required signatures are present then we're done.  So I wanted to triple check that the scope of this suggestion was solely related to what any given node might _do_ with a finalised transaction when it receives it.

So just to check: if checkTransaction in this proposal does throw a FlowException, where do you want that sent?  To the flow running on the node where it's thrown? Or back to the coordinating node for the finalisation process?

**Comment by MrMatthewLayton** [comment]
Yeah I see your point from the perspective of signatures. For my particular case, I have flows where sessions can be passed in, rather than generated from `participants - ourIdentity`. Only the initiator is required to sign the transaction, but all participants are required to record it and update their vaults, but, because sessions for non-participants can be passed into the flow, I want those participants to check if there's anything relevant in the transaction to them, and if not, they just ignore it.

I guess throwing an exception at this point _might_ be overkill. Unless I've misunderstood something, I was under the impression that `FlowException` is propagated back to the initiating node, which is really where it should go.

**Comment by gendal** [comment]
cc @adagys. Is this something for your team to look at and/or comment on?

**Comment by mikehearn** [comment]
I think you could do this better by having your own flow that wraps ReceiveTransactionFlow and just invokes it when the other side runs SendTransactionFlow. It shouldn't record to the vault because you won't be "relevant" if you're not a participant. You can then do what you want with the result. See the docs about observers.

ReceiveFinalityFlow is really meant for participants. And as Richard notes, you aren't meant to refuse to process a finalised transaction. You'd just get out of consensus.

**Comment by MrMatthewLayton** [comment]
@mikehearn That's exactly what I did in my case, though I might have gone a step too far in throwing a `FlowException` when the transaction is irrelevant to erroneous counter-parties. Might just be better for them to ignore it.

It was more a case that my custom flow is _almost_ identical to the `ReceiveFinalityFlow` except that it just performs custom checking before it finalizes the transaction.

On this, though...
> ReceiveFinalityFlow is really meant for participants. And as Richard notes, you aren't meant to refuse to process a finalised transaction. You'd just get out of consensus.

What happens when counter-parties (participants or otherwise) decide to write their own `@InitiatedBy` flows in order to be malicious?

**Comment by rick-r3** [comment]
It looks like the API for `FinalityFlow` explicitly mentions observer sessions.  What you are suggesting here is that observers want some optionality in whether they wish to record the transaction @MrMatthewLayton ?

The optionality would only apply if the receiving node is not a signer and `StatesToRecord.ALL_VISIBLE` is specified (to avoid extra processing when a participant)?

The check should really be the first line of the implementation of `unwrap` in `ReceiveTransactionFlow`, otherwise you will expend pointless effort resolving the back chain when it is not required.
