### ISSUE TITLE
A fresh logfile is started even if the node is about to quit due to an already running instance

### ISSUE THREAD

**Issue by wawrzek** [corda/corda#55]
**Scenario**:
I run the attachment demo. 
All nodes run in background. 
I _cd_ to a node (e.g. nodea) directory and run _java -jar corda.jar_. 
Corda kindly checks if there is other application running from the same directory and exits. 

 **Issue** 
it starts to write to logs before making a check, what means that original logs are overwrite. I think they are properly archived into archive subdirectory (BTW I expected to find them in logs directory), but the ‘main’ logs file is gone.

**Comment by gendal** [comment]
@wawrzek - no comment on the issue but just to say that I like the writeup...  clear description of the problem, clear reproduction info... good to see!
