### ISSUE TITLE
RPC client isn't retrying connections to the node properly if it goes down

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#550]
https://discourse.corda.net/t/node-webserver-connectivity-issues/1032

We configure it to retry here:

https://github.com/corda/corda/blob/master/client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt#L66

However:

* Maybe this mechanism isn't working
* Maybe backing off to 3 minute retry interval is just inappropriately long

**Comment by mkr237** [comment]
Hi, 

Have you been able to identify if this is indeed an issue as yet?  Is there anything we can do/provide to help?
-m

**Comment by mikehearn** [comment]
I've asked Andrzej to investigate this.

**Comment by andr3ej** [comment]
This was fixed in the linked PR, closing.
