### ISSUE TITLE
Custom Entities Need No Arg Constructors

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5520]
The documentation shows examples of how to add schema mapping.

https://docs.corda.net/api-persistence.html#object-relational-mapping

However, it skips over the fact that Hibernate requires default constructors to work.

You either need to add the default constructor to the Entity class or use gradle plugins  `kotlin-noarg` and  `kotlin-jpa` to generate them <sup>[1]</sup>

The documentation _and samples_ should be updated to reflect this as people are still getting confused.
e.g.
https://stackoverflow.com/questions/45475265/corda-error-org-hibernate-instantiationexception-no-default-constructor-for-en/45478049
https://stackoverflow.com/questions/55705970/vaultcustomquerycriteria-for-state-in-corda

<b><sup>[1]</sup></b> <sub>There is currently a bug in the IDEA kotlin plugin that means that the constructors are not generated from the kotlin-noarg plugin when you run your tests from IDEA.
This ends up with the same test succeeding when run from Gradle and failing when run from IDEA, which is also very confusing.
</sub>

**Comment by davidrapacchiale** [comment]
Thanks @opticyclic . We have filed a bug https://r3-cev.atlassian.net/browse/CORDA-3534 here to keep track of the progress of this ticket. I'll close the issue on github.
