### ISSUE TITLE
Our gradle config breaks IntelliJ

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#553]
Attempting to alter anything in the project/module view (f4 in project tree root) gives an error saying that two modules cannot share the same content root. The problem is the samples all add a content root of /config/ in order to get the log4j files, which IntelliJ can't cope with. We should find some other way to share the log4j configs that doesn't require this approach.

**Comment by chrisr3** [comment]
Duplicate of #325.

**Comment by mikehearn** [comment]
Fixed
