### ISSUE TITLE
Add support for OpenShift (CorDapps)

### ISSUE THREAD

**Issue by ghost** [corda/corda#5542]
Add support for OpenShift (CorDapps) { Notary, Node }

**Comment by mikehearn** [comment]
It'd help if you could elaborate on what specific support you'd like.

**Comment by ghost** [comment]
@mikehearn 

I would like to run CordApp (Notary and Node) on OpenShift Platform

Regards,
Fábio Sbano

**Comment by ghost** [comment]
Example below (OpenShift v3.11)

![CorDapp - Catalog](https://user-images.githubusercontent.com/48354484/66065965-f133e380-e51e-11e9-8afa-6cb27f9556fb.png)
![CorDapp - Example](https://user-images.githubusercontent.com/48354484/66065969-f3963d80-e51e-11e9-97e8-d09030b58e0c.png)


Regards,
Fábio Sbano

**Comment by ghost** [comment]
@mikehearn 

I would like to deploy to container platform using OpenShift and Self-Service Catalog as above images

Regards,
Fábio Sbano

**Comment by ghost** [comment]
@mikehearn 

Can I help with the project by running it on the kubernetes and openshift platform?
I see that currently it is only possible to run docker container

Best Regards,
Fábio Sbano

**Comment by peterli-r3** [comment]
Hi 

Corda now is available on Kubernetes. 

Please feel free to contact devrel@r3.com if you need any further information
