### ISSUE TITLE
Node Explorer freeze/loop on wrong address

### ISSUE THREAD

**Issue by gitgabrio** [corda/corda#5543]
@mikehearn 
When wrong url/port are inserted in the Node Explorer, 
the GUI freeze and became unresponsive.

Behind the scene, the connection process enter in a loop and try to reconnect undefinetely.
After some time, a popup window appear, giving only the chance to a) Force quit b) wait.

The following is  part of the relevant log, with the repeated attempts:

```
(repeated lines omitted)
[INFO ] 22:18:11,699 [JavaFX Application Thread] (ReconnectingCordaRPCOps.kt:183) internal.ReconnectingCordaRPCOps.establishConnectionWithRetry - Connecting to: 127.0.0.1:10101
[INFO ] 22:18:11,743 [JavaFX Application Thread] (InternalUtils.kt:207) internal.RPCClient.logElapsedTime - Failed Startup took 40 msec
[INFO ] 22:18:32,979 [JavaFX Application Thread] (ReconnectingCordaRPCOps.kt:183) internal.ReconnectingCordaRPCOps.establishConnectionWithRetry - Connecting to: 127.0.0.1:10101
[INFO ] 22:18:32,992 [JavaFX Application Thread] (InternalUtils.kt:207) internal.RPCClient.logElapsedTime - Failed Startup took 8 msec
...
```
Steps to reproduce:

1. start demobench
2. start a node from demobench
3. start a <ins>standalone</ins> instance of Node Explorer (<ins>not</ins> from the demobench itself) 
4. try connection to the running node with wrong url and/or port

Verified on release/os/4.3

Issues:

1. for ux perspective, the user has to wait too much before the GUI recover control, and then he/she is left with the only chance to close the app or wait further, without any way to edit the parameters (see https://github.com/corda/corda/issues/5552)
2. for background process, the iteration/loop in case of connection timeout should be fixed.

**Comment by davidrapacchiale** [comment]
Thanks @gitgabrio . This looks similar to a bug that we've raised internally https://r3-cev.atlassian.net/browse/ENT-4513 . We'll aim to have it fixed for OS4.4, so I will close this issue in github for now and reopened it if still relevant after the next release.
