### ISSUE TITLE
Start connection not fully managed by Node Explorer GUI 

### ISSUE THREAD

**Issue by gitgabrio** [corda/corda#5552]
@mikehearn 
This issue is somehow related to https://github.com/corda/corda/issues/5543.
When the connection can't be established, the GUI become unresponsive.
Looking at GUI implementation, two missing parts are:

1. parameters are not verified before attempting to connect (the "connect" button is enabled by default, and it is possible to start connection attempts leaving all the fields empty)
2. the connection thread is started in synchronous way inside the "resultconverter" callback, so until this thread ends, there is no way to interrupt it or gain control over the GUI

**Comment by davidrapacchiale** [comment]
Thanks @gitgabrio. 
Could you please test with the latest version of OS? 
We have moved to a new reconnecting RPC which should fix most of these issues
