### ISSUE TITLE
flow session send method takes Any, which might lead to confusions when sending closure

### ISSUE THREAD

**Issue by janisolekss** [corda/corda#5563]
It is very easy to misswrite code which involves closure when sending something using flowSession,send method

this code

session.send { true } compiles and works, but most likely will blow up in the runtime as actually it is
session.send ( { true } ) and closures are not CordaSerializable and of course counterparty won't expect clojure

Some sort of sanity check or type restriction on the method might help.
Ideally compile time check.

On of the solutions could be to change the signature of send method to have 2 parameters, where second one is defaulted
    @Suspendable
    abstract fun send(payload: Any, maySkipCheckpoint: Boolean = false)

and get rid of send(payload:Any) at all, then there is no possibility to pass clojure without explicitly setting it as first parameter, as attempt to "forget" round brackets, will yield compilation error

**Comment by peterli-r3** [comment]
Hi

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
