### ISSUE TITLE
Move samples To samples Repo

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5566]
There is a [samples directory](https://github.com/corda/corda/tree/release/os/4.3/samples) in the main corda repo.

However, there is also a separate [samples repo](https://github.com/corda/samples) as well.

It would make sense to move the samples from the corda repo to the samples repo so that all the samples are in the same place.

**Comment by davidrapacchiale** [comment]
Thanks @opticyclic 
We are currently reviewing the Corda testing infrastructure and we might be able to move the sample to a separate repo in the future. However, our current testing strategy does require some samples in the samples repo
