### ISSUE TITLE
Spelling Mistake "teh"

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5595]
There are a few typos where "the" is spelt "teh".

https://github.com/corda/corda/blob/release/os/4.3/docs/source/example-code/src/main/kotlin/net/corda/docs/kotlin/txbuild/WorkflowTransactionBuildTutorial.kt#L191

https://github.com/corda/corda/blob/release/os/4.3/serialization/src/test/kotlin/net/corda/serialization/internal/amqp/EnumEvolveTests.kt#L272

https://github.com/corda/corda/blame/release/os/4.3/docs/source/design/versioning/contract-versioning.md#L254

**Comment by davidrapacchiale** [comment]
Thanks @opticyclic for spotting these.
We have opened a jira ticket https://r3-cev.atlassian.net/browse/CORDA-3481. 
Could you please raise a PR and include "CORDA-3481" in the title?
