### ISSUE TITLE
Unable to control Log level (INFO, WARN etc.) when performing Flow tests

### ISSUE THREAD

**Issue by TywinLannister1313** [corda/corda#5634]
My Setup:

- OS: Windows 10 & Ubuntu 18.04.3
- Corda: 4.1 (I always start with the template.)
- IDE: IntelliJ 2019.1.3
- Language: Java

If this is not a bug I apologize in advance but I have spent hours trying to get Corda to behave like I expect and either I don't know something (quite possible) or my settings are being overridden.

If I use **JUnit** to run my Flow tests I can control the log levels (INFO, WARN etc.) by passing in my own custom log4j2.xml file with the VM option:

`-Dlog4j.configurationFile=/home/testuser/corda/template/myLog4j2.xml`

This works perfect.  The test recognizes and uses the settings in the xml file.

However the Corda documentation recommends using the **Gradle Test Runner** for performing tests.  If I switch to using the Gradle Test Runner the same VM option appears to have no effect.  The contents of the xml file are ignored and using Process Monitor for Windows I can see the file is never read.  However if I look at the output of the test it appears that the VM option was passed in:

`2:23:38 PM: Tasks execution finished ':workflows:cleanTest :workflows:test --tests "com.template.FlowTests.dummyTest" -Dlog4j.configurationFile=/home/testuser/corda/template/myLog4j2.xml'.`

Am I improperly using the Gradle Test Runner or is my xml file being ignored/overridden internally?

**Comment by peterli-r3** [comment]
Hi Tywin,

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact [devrel@r3.com](mailto:devrel@r3.com) if you need any further information
