### ISSUE TITLE
Serialization issues with capitalized data class fields

### ISSUE THREAD

**Issue by taavi-kala-gt** [corda/corda#5673]
### Description

When trying to serialize a JSON response of a data class that has a field that starts with capital letters, an IllegalStateException is thrown.

### Issue
`2019-11-05 15:15:21.455  WARN 31678 --- [io-10007-exec-6] .c.j.MappingJackson2HttpMessageConverter : Failed to evaluate Jackson serialization for type [class com.guardtime.api.test.TestCapitalizedValuesImpl]:  java.lang.IllegalStateException: Jackson didn't provide serialisers for [SOMEValue]`

### Steps to reproduce

```
@CordaSerializable
interface TestCapitalizedValues {
    val SOMEValue: String
    val someOtherValue: String
}

@JsonInclude(JsonInclude.Include.NON_NULL)
data class TestCapitalizedValuesImpl(
    @get:JsonProperty("Some_Value")
    override val SOMEValue: String,
    @get:JsonProperty("Some_Other_Value")
    override val someOtherValue: String
) : TestCapitalizedValues

@GetMapping("testCapitalizedField")
fun testCapitalizedField(): ResponseEntity<TestCapitalizedValuesImpl> {
    return ResponseEntity.ok(TestCapitalizedValuesImpl("test", "test2"))
}
```

### Version

Corda Enterprise 4.2

**Comment by davidrapacchiale** [comment]
@amosmwsmith I believe we're tracking this in our internal jira. I'll close this but can you please reference the SUP ticket here?
