### ISSUE TITLE
Serialization issues with Boolean type is-prefixed data class fields

### ISSUE THREAD

**Issue by taavi-kala-gt** [corda/corda#5674]
### Description

When trying to serialize a JSON response of a data class that has a Boolean field that starts with 'is' an IllegalStateException is thrown.

### Issue
`2019-11-05 15:15:21.455  WARN 31678 --- [io-10007-exec-6] .c.j.MappingJackson2HttpMessageConverter : Failed to evaluate Jackson serialization for type [class com.guardtime.api.test.TestIsPrefixImpl]:  java.lang.IllegalStateException: Jackson didn't provide serialisers for [isBooleanValue]`

### Steps to reproduce

```
@CordaSerializable
interface TestIsPrefix {
    val isBooleanValue: Boolean
    val otherValue: String
}

@JsonInclude(JsonInclude.Include.NON_NULL)
data class TestIsPrefixImpl(
    @get:JsonProperty("Is_Boolean_Value")
    override val isBooleanValue: Boolean,
    @get:JsonProperty("Other_Value")
    override val otherValue: String
) : TestIsPrefix

@GetMapping("testIsPrefix")
fun testIsPrefix(): ResponseEntity<TestIsPrefixImpl> {
    return ResponseEntity.ok(TestIsPrefixImpl(true, "test2"))
}
```

### Version

Corda Enterprise 4.2

**Comment by davidrapacchiale** [comment]
@amosmwsmith I believe we're tracking this in our internal jira. I'll close this but can you please reference the SUP ticket here?
