### ISSUE TITLE
Broken links on https://www.corda.net/2017/04/07/corda-m10-released/

### ISSUE THREAD

**Issue by fracting** [corda/corda#574]
Congratulations on the new release! This release introduced many interesting features, thank you for the great work.

Unfortunately the external links on the release blog are broken, for example:

https://www.corda.net/%22https://www.corda.net/corda-training//%22

Cheers.

**Comment by Clintonio** [comment]
Thank you very much @fracting. It is corrected now.

**Comment by fracting** [comment]
To be honest I don't really care that much, but it seems not all the links are fixed, most of them have an extra trailing `"`, for example

https://blog.jetbrains.com/kotlin/2017/03/kotlin-1-1//%22
https://docs.corda.net/releases/release-M10.1/%22

**Comment by joeldudleyr3** [comment]
Thanks @fracting - I've re-fixed them. It should be working now :)

**Comment by mikehearn** [comment]
@joeldudleyr3 can you file a JIRA task to set up a cron job that runs a 404 scanner over corda.net and docs.corda.net?
