### ISSUE TITLE
Driver throws FileNotFoundException for project using Springboot 

### ISSUE THREAD

**Issue by patrickkuo** [corda/corda#5751]
In `net.corda.testing.node.internal.TestCordappImpl.Companion#runGradleBuild`, corda driver attempt to build out the `lib` directory using Gradle:jar task, however if the project uses springboot, jar task is disabled (replaced by bootJar), this causes test to fail throwing File not found exception, when driver try to locate the `lib` dir later on.

**Comment by davidrapacchiale** [comment]
Thanks @patrickkuo to raise this, it looks like a genuine bug. 
We have created https://r3-cev.atlassian.net/browse/CORDA-3462 where you will be able to track the progress of this ticket hence closing this ticket.
