### ISSUE TITLE
Reference states break selection of contract jar

### ISSUE THREAD

**Issue by Quiark** [corda/corda#5753]
Let's say I'm building a transaction with an older version of attachment than what is currently under `cordapps/` because I don't want to force counterparty to upgrade. I do `addAttachment(attV1)` on the transaction, indicating explicit choice of contract version.

This works .. until I add a reference state. In that case, this code in `TransactionBuilder.selectContractAttachmentsAndOutputStateConstraints` 

```
        val refStateContractAttachments: List<AttachmentId> = referenceStateGroups
                .filterNot { it.key in allContracts }
                .map { refStateEntry ->
                    selectAttachmentThatSatisfiesConstraints(true, refStateEntry.key, refStateEntry.value, emptySet(), services)
                }
```
goes in and selects a cordapp attachment by itself, without consulting what is already on the transaction. In my case, it selects the latest version. Further down, I get the error 
`net.corda.core.contracts.TransactionVerificationException$ConflictingAttachmentsRejection` because I have 2 different attachments for the same contract.

I'm using signature constraints but by looking at the code, HashConstraint would have the same problem. This problem exists with Corda 4.1 and looking at github v4.4, the code is essentially the same.

**Comment by Quiark** [comment]
For this to happen, the reference state type must be different from ordinary inputs and outputs but they must be in the same contract jar.

**Comment by tudor-malene** [comment]
Thank you @Quiark . 
This is clearly a bug in Corda.

**Comment by davidrapacchiale** [comment]
Thanks @Quiark 
We have created https://r3-cev.atlassian.net/browse/CORDA-3461 on our OS jira project where you can track the resolution of this bug.
