### ISSUE TITLE
Dockerform ignores dataSourceProperties.dataSource.url

### ISSUE THREAD

**Issue by FredericHeem** [corda/corda#5761]
The *Dockerform* tasks ignores the *dataSourceProperties.dataSource.url* in the *extraConfig* section, it sets it to *jdbc:h2:file:./persistence/persistence;DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0;LOCK_TIMEOUT=10000* regardless of the value of *dataSourceProperties.dataSource.url* 
*Cordform* does not exhibit this behaviour.

**Comment by davidrapacchiale** [comment]
Closing this issue as it is related to an old version of the software. Either not relevant any longer, or fixed elsewhere. Please do reopen if this is a valid bug on the latest version of Corda OS
