### ISSUE TITLE
Cordform does not create the drivers directory

### ISSUE THREAD

**Issue by FredericHeem** [corda/corda#5762]
Suppose the *deployNode*  extraConfig is configured for mysql:
```
extraConfig = [
                "dataSourceProperties.dataSourceClassName"  : "com.mysql.cj.jdbc.Driver",
                "dataSourceProperties.dataSource.url"       : "jdbc:mysql://localhost/db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true",
                "dataSourceProperties.dataSource.user"      : "developer",
                "dataSourceProperties.dataSource.password"  : "develop",
                "database.transactionIsolationLevel"        : "READ_COMMITTED"

        ]
```

The *deployNode* task failed with the following error:

```
[ERROR] 10:41:53+0000 [main] internal.NodeStartupLogging. - Could not find the database driver class. Please add it to the 'drivers' folder. See: https://docs.corda.net/corda-configuration-file.html: Could not find the database driver class. Please add it to the 'drivers' folder. See: https://docs.corda.net/corda-configuration-file.html [errorCode=1oswgkz, moreInformationAt=https://errors.corda.net/OS/4.3/1oswgkz]
... still waiting. If this is taking longer than usual, check the node logs.
```

The drivers folder is not created at that point, should it be ?

**Comment by szymonsztuka** [comment]
See https://docs.corda.net/generating-a-node.html?highlight=drivers#optional-configuration
``Cordform parameter drivers of the node entry lists ...``,  also I don't think Corda OS works with MySQL/MariaDB databases.

**Comment by FredericHeem** [comment]
Same problem for Oracle. 
No issue with posgresql because its jar is dragged into corda.jar already by default

**Comment by szymonsztuka** [comment]
Try to use `jarDirs` property: https://docs.corda.net/corda-configuration-file.html?highlight=jardirs
But I'm not sure if setting from  Gradle extraConfig will work (due few double and single quotes):
```
extraConfig = [ ...
"jarDirs" = '[ "absolute_path_to_folder_with_jdbc_driver" ]'
  ]
```

**Comment by anthonykeenan** [comment]
For an example see this:

https://github.com/anthonykeenan/obligation-cordapp/blob/anthony-obligation-remark-test/kotlin-source/build.gradle#L93

**Comment by anthonykeenan** [comment]
H2 is the only officially supported database in Open Source. Postgres and Sql Server are available via community contributions. Oracle support is available in our enterprise version here: https://www.r3.com/download-corda-enterprise/
