### ISSUE TITLE
Memory leak in SSH server

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#5842]
See here

https://groups.io/g/corda-dev/topic/memory_leak_via_node_ssh/69495375?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,69495375

It seems `run exit` may not terminate the connection properly.

**Comment by rekalov** [comment]
Right, RPC connection is not closed on SSH disconnect. Every time SSH client connects, a new `RPCClientProxyHandler` is created, which brings a bunch of new executors / threads / thread locals resulting in extra memory and file descriptors consumption.

We need to find a way to close `CordaRPCConnection` on `exit`, or, better, on any ssh disconnect (incl. brute termination).

**Comment by davidrapacchiale** [comment]
We are tracking the issue in https://r3-cev.atlassian.net/browse/CORDA-3520. I'll close this github issue
