### ISSUE TITLE
Update documentation for financial model

### ISSUE THREAD

**Issue by dazraf** [corda/corda#5847]
I was reviewing the use of `CompositeKey` and noted that the docs are stale in some places. 
e.g. 
https://docs.corda.net/financial-model.html

still refers to `CompositeKey` and `AbstractParty`

**Comment by davidrapacchiale** [comment]
Thanks @dazraf.  We have filed a bug https://r3-cev.atlassian.net/browse/CORDA-3544 here to keep track of the progress of this ticket. I'll close this github issue.
