### ISSUE TITLE
Inconsistent node balance with same API call

### ISSUE THREAD

**Issue by adelrustum** [corda/corda#5853]
**Corda CE = 4.3**
**Tokens = 1.1-RC01**

* I have a REST API that queries my Mint node and returns its balance (all the tokens on my Mint node are held by the Mint).
* This API returns different results when ran multiple times consequently (I use Postman; several times within 10 minutes or so and it randomly returns a different balance) . 
* I don't run any code between those calls (i.e. no issue, transfer, or redeem commands).

Below is my code:
```
public Map<String, BigDecimal> getNodeBalance(@NotBlank String myTokenTypeId) {
	// Latest version of my EvolvablableTokenType.
	EvolvableMyTokenType myTokenType = MyTokenUtils.getLatestMyTokenType(proxy, myTokenTypeId);
	// Only tokens held by the Mint.
	QueryCriteria queryCriteria = QueryUtilitiesKt.heldTokenAmountCriteria(
			myTokenType.toPointer(myTokenType.getClass()),
			proxy.nodeInfo().getLegalIdentities().get(0));

	// Based off the code from Corda documentation (API: Vault Query).
	int pageNumber = DEFAULT_PAGE_NUM;
	final int pageSize = 200;
	long totalResults;
	long totalBalance = 0;
	do {
		PageSpecification pageSpec = new PageSpecification(pageNumber, pageSize);
		Vault.Page<FungibleToken> results = proxy.vaultQueryByWithPagingSpec(FungibleToken.class,
				queryCriteria, pageSpec);
		totalResults = results.getTotalStatesAvailable();
		if (totalResults == 0)
			return Collections.singletonMap("Node Balance", BigDecimal.valueOf(0));
		List<StateAndRef<FungibleToken>> pageMyTokens = results.getStates();
		// Is it possible the below line is behaving randomly?
		long pageBalance = pageMyTokens.stream()
				.mapToLong(t -> t.getState().getData().getAmount().getQuantity()).sum();
		totalBalance += pageBalance;
		pageNumber++;
	}
	while ((pageSize * (pageNumber - 1) <= totalResults));

	BigDecimal bigTotalBalance = BigDecimal.valueOf(totalBalance);
	// MyToken has 6 fraction digits; meaning 1000,000 = one MyToken.
	BigDecimal fractions = BigDecimal.valueOf(Math.pow(10, myTokenType.getFractionDigits()));
	BigDecimal nodeBalance = bigTotalBalance.divide(fractions);
	return Collections.singletonMap("Node Balance", nodeBalance);
}
```
I ran the webserver with remote debug and monitored the values of `pageBalance` and `totalBalance`. I'm not using "order by" in my query, but notice how for the first 4 pages the results are identical in the 2 API calls, but the numbers in the 5th page are different; even though the records are the same!!!
I didn't issue, transfer, or redeem any tokens between API calls, in fact I didn't call any code other than pressing the "send" button inside Postman to call the API.
 
```
		Calling API		Calling same API again
Page balance: 	197727787		197727787
Total so far:	197727787		197727787

Page balance:	200000000		200000000
Total so far:	397727787		397727787

Page balance:	200000000		200000000
Total so far:	597727787		597727787

Page balance:	200000000		200000000
Total so far:	797727787		797727787

Page balance:	62727787		65000000
Total so far:	860455574		862727787
```

Btw, the correct balance is the second API call (862727787); I use the below query in my pgAdmin:
```
select sum(amount)
from fungible_token 
-- Holder is Mint node
where holder = 'OU=XXX, O=XXX, L=London, C=GB'
and (transaction_id, output_index) 
in (
select transaction_id, output_index 
	from vault_states 
	-- Only tokens
	where contract_state_class_name = 'com.r3.corda.lib.tokens.contracts.states.FungibleToken' 
	-- Only unconsumed
	and state_status = 0
);
```

Regardless of which returned number is the correct balance; how is it that the same code is returning different results? Looks like `vaultQueryByWithPagingSpec` has a problem.

I created the following repository with an example that has the exact same code that I used to calculate the balance, but sadly I wasn't able to reproduce the error; but I hope that it's still a good starting point for your investigation: https://github.com/adelrustum/tokens-sdk-issue-172

I'm also attaching a video (as a zip file) that shows you the odd behavior in my real code on Google Cloud (unfortunately I cannot share that code, but the example repo has the same code that the API uses). In the video I query the database to show the correct balance, and I keep calling the API; initially it shows the wrong number and then suddenly the returned number changes and shows the correct balance!

[Demo.zip](https://github.com/corda/corda/files/4048491/Demo.zip)

Initially I opened this issue in the Tokens SDK repo (https://github.com/corda/token-sdk/issues/172), but Roger Willis did his own tests and couldn't reproduce it either, and he also suggested opening the issue in Corda repo since it's related to querying the vault with pagination.

Any hints on what could be the cause? I wasn't able to reproduce with the provided example repo or the real code locally (the problem only happens in DEV on GCP - Google Cloud).

**Comment by adelRestom** [comment]
Any hints on what could be the cause? I wasn't able to reproduce with the provided example repo or the real code locally (the problem happens in DEV on GCP - Google Cloud).
We are moving DEV from GCP to AWS in the next couple of weeks and building everything from scratch; I'll keep an eye on this matter once we're in AWS.

**Comment by davidrapacchiale** [comment]
Thanks @adelRestom . I have raised a bug in our OS Jira instance (https://r3-cev.atlassian.net/browse/CORDA-3560)  where you can track its progress. I will close the issue on github.

**Comment by adelrustum** [comment]
David, were you able to reproduce the issue?
I moved on from mixed non-account with accounts, which is warned about in the Account library documentation:
```
Currently, if accounts and non-accounts workflows are mixed on the same node then you need to be careful with state selection. When selecting states for non-accounts workflows, the state selection code will currently pick states which could be assigned to accounts.
```
I was mixing non-accounts (Mint node) with accounts (Wallet node); so now I created a "default" account for the Mint node and moved on.
