### ISSUE TITLE
RPC user able to start a flow they don't have permissions to

### ISSUE THREAD

**Issue by adelrustum** [corda/corda#5861]
**Corda Open Source 4.3**

I connect to my node using the standalone shell:

![01](https://user-images.githubusercontent.com/37046080/72472058-75963380-37a9-11ea-852a-90624ac3bb4e.PNG)

The config file looks like this:

![04](https://user-images.githubusercontent.com/37046080/72472079-7f1f9b80-37a9-11ea-968b-8c0ee19aa6b4.PNG)

My RPC user, which I used to log in the standalone shell, doesn't have the permission to run `CreateEvolvableShokenType` flow:

![05](https://user-images.githubusercontent.com/37046080/72472262-db82bb00-37a9-11ea-849c-d605bfb35ea3.PNG)

Running `flow list`, shows that flow:

![02](https://user-images.githubusercontent.com/37046080/72472282-e50c2300-37a9-11ea-85da-ab15d5052cad.PNG)

And the user is able to start the flow:

![03](https://user-images.githubusercontent.com/37046080/72472296-ea696d80-37a9-11ea-9d02-b759f7509eac.PNG)

**Comment by davidrapacchiale** [comment]
Hi @adelRestom, thanks for reporting this bug. We have opened a bug in OS 
 https://r3-cev.atlassian.net/browse/CORDA-3577 where you can track the resolution progress

**Comment by nikinagy** [comment]
Hi @adelRestom ,

Please remove 'InvokeRpc.startTrackedFlowdynamic' from your permission list, because it behaves like a super permission and gives permission to run all flows on the network.
As for the flow list command, this is just how Corda works. This way you can make sure what are the flows available (but it does not mean that you have permission to run them).

I hope this will help you.

Regards,
Niki

**Comment by adelrustum** [comment]
@nikinagy 

According to [this page](https://docs.corda.net/docs/corda-os/4.4/shell.html#permissions) from the official documentation; the below permissions are required to start flows:

> Starting flows requires InvokeRpc.startTrackedFlowDynamic, InvokeRpc.registeredFlows and InvokeRpc.wellKnownPartyFromX500Name, as well as a permission for the flow being started.

Btw, R3 acknowledged that it's a bug (look at the post before yours); they are presenting a fix in Corda 4.5.

**Comment by nikinagy** [comment]
@adelRestom 

I can assure you that it is working fine without the InvokeRpc.startTrackedFlowDynamic. I tested it myself yesterday, with Corda 4.3, 4.4 and 4.5.

This 'bug' is there in 4.5 as well.

You can see the explanation in the comments section on that JIRA issue @davidrapacchiale linked above.

**Comment by adelrustum** [comment]
Thanx Niki, that's great news!

Can you please confirm that you tried it with the **standalone shell** (not the node's shell), because that's how I discovered the issue.  

If yes, and it worked for you (to run the flows without `InvokeRpc.startTrackedFlowdynamic`); can you ask the team that's in charge of the official documentation to update that paragraph and remove `InvokeRpc.startTrackedFlowdynamic` as a **required permission** to run the flows?

**Comment by nikinagy** [comment]
Yes, I can confirm that I tested it with the standalone shell.

That is a fair point, I will let them know that we should modify the documentation and update it with our findings.

**Comment by adelrustum** [comment]
Perfect! Thanx for your time, I was contacted by 2 other people regarding this issue on R3's Corda Slack channel; I'll try to find them and inform them 🙂
