### ISSUE TITLE
Having non-corda reference.conf files on classpath causes DriverDSLImp failure

### ISSUE THREAD

**Issue by simonmaxen-da** [corda/corda#5881]
**To reproduce:**
With a Corda **4.3** test that uses the DriverDSL add a file to the resources directory called reference.conf that includes a property (say 'akka').

Run the driver test.

**Output:**
ERROR 44:05 net.corda.testing.node.internal.DriverDSLImpl - Driver shutting down because of exception
java.lang.IllegalStateException: Unknown property 'akka': (keyName='akka', typeName='null', path=[akka])

**Comment by davidrapacchiale** [comment]
Hi @simonmaxen-da thanks for reporting this. We have opened a bug into our OS jira project https://r3-cev.atlassian.net/browse/CORDA-3578 where you can track the resolution / progress
