### ISSUE TITLE
demobench unavailable for linux

### ISSUE THREAD

**Issue by akarsh24** [corda/corda#5891]
i started the cord app example and bring up the node after that i run the corda-tools-explorer-4.3.jar file it opened the where i entered the  host-name, port ,username and password  and click the submit button it didn't started by getting the logs like this

when iam setup the node explorer in  Linux OS by  downloading the  corda-tools-explorer-4.3.jar file and run it ,but i am not able to connect to node its failed.

The logs which  am getting below

- Connecting to: localhost:10009
[INFO ] 16:28:00,030 [JavaFX Application Thread] (InternalUtils.kt:207) internal.RPCClient.logElapsedTime - Failed Startup took 88 msec
[INFO ] 16:29:23,557 [JavaFX Application Thread] (ReconnectingCordaRPCOps.kt:195) internal.ReconnectingCordaRPCOps.establishConnectionWithRetry.

How to get the Demobench for linux ,can we do the blockchain explorer  without using the Demobench standalone .

**Comment by davidrapacchiale** [comment]
Hi @akarsh24 we have done few fixes on reconnecting RPC client hence the next version of Corda 4.4 might work better for you. Could you please re-try once the binaries are available? Thanks
