### ISSUE TITLE
Graceful reconnect feature of RPC causes exception to drop connection

### ISSUE THREAD

**Issue by countfloyd** [corda/corda#5908]
I have some RPC client code that calls the RPC call uploadAttachmentWithMetadata. If the attachment already exists, I catch the DuplicateAttachmentException and just return the hash. Here is the Scala code that does that:
```
def addAttachment(name: String, path: Path): Either[String, SecureHash] = {
  cordaConn.rpc.flatMap { rpc =>
    Try {
      val in = new FileInputStream(path.toFile)
      rpc.uploadAttachmentWithMetadata(in, "app", name)
    } match {
      case Success(hash) =>
        Right(hash)
      case Failure(e) if e.isInstanceOf[CordaRuntimeException] &&
        e.asInstanceOf[CordaRuntimeException].getOriginalExceptionClassName == "net.corda.nodeapi.exceptions.DuplicateAttachmentException" =>
          val ce = e.asInstanceOf[CordaRuntimeException]
          Right(SecureHash.parse(ce.getOriginalMessage))
      case Failure(e) => 
        Left(e.getMessage) 
    }
  }
}
```
When NOT using the new graceful reconnect feature, this works fine (as it did in 4.2). However, if I use the graceful reconnect feature when connecting to RPC, the DuplicateAttachmentException is never caught and causes the RPC connection to drop. The log then shows repeated attempts to reconnect but is never successful.
This is how we connect without graceful reconnect:
```
new CordaRPCClient(url).start(user, password)
```
This is how we connect with graceful reconnect:
```
new CordaRPCClient(url).start(user, password, new GracefulReconnect(
  () => {
    log.warn(s"Disconnected from Corda node, it either went down or network connection was lost")
    onDown(new IllegalStateException("Corda server disconnected"))
  },
  () => {
    log.warn(s"Corda node reconnected after disconnection")
    onUp()
  },
  -1
))
```

**Comment by countfloyd** [comment]
This happens in version 4.3. Version 4.2 worked as expected. Attaching corda log.
[corda_log.txt](https://github.com/corda/corda/files/4129963/corda_log.txt)

**Comment by fowlerrr** [comment]
Hi, do you also have a copy of the logs from the RPC client?  Those logs look like RPC server/node logs

**Comment by countfloyd** [comment]
Sure, here you go. Just so you know, I've submitted this bug on the enterprise support portal as well (SUP-1098)
[client_log.txt](https://github.com/corda/corda/files/4140424/client_log.txt)

**Comment by davidrapacchiale** [comment]
Thanks @countfloyd for this.

@fowlerrr , I have raised a bug in our OS Jira instance (https://r3-cev.atlassian.net/browse/CORDA-3572). Please reference that once you have a fix ready.
