### ISSUE TITLE
Add support for programmatic CorDapp deployment and serialization

### ISSUE THREAD

**Issue by ulrikrasmussen** [corda/corda#5921]
A CorDapp currently defines many things via annotations, `META-INF/service` declarations and/or implicit marker interfaces, including:

* Whitelists
* Custom serializers
* Flow endpoints
* Serialization behavior

The logic required to handle all of this is quite complex and hard to debug when something goes wrong, see e.g. #5914.

As a developer, I would prefer to have a more reliable mechanism for deploying CorDapps which didn't rely on reflection to pick up definitions, but instead allowed me to explicitly specify everything via typed interfaces. I wouldn't mind having to write my own serialization and deserialization methods for contract states and flow endpoints, for example.

One possible approach would be to allow a Corda node to be instantiated programmatically via a public API method, thereby allowing node operators to build custom Corda nodes tailored to a set of CorDapps, doing away with the `/cordapps` folder. Since a Corda node has to be rebooted when a CorDapp changes anyway, I don't think it would add many practical complications to the deployment. Since deployments should be automated anyway, adding a build stage should also not be a problem. 
On the other hand, I think this model has several advantages:

* The current model of loading CorDapp JARs from `/cordapps` can still be supported, and can be pulled out as a separate library.
* More type errors can be caught in the build phase instead of causing runtime errors.
* Everything will run in the same classpath. If it builds relative to this classpath, then it will most likely also work at runtime (but proper use of the new Java module system or OSGi would be needed to resolve all classpath issues).
* Since CorDapp objects are explicitly instantiated in code, dependencies between CorDapps can be resolved by hand, for example solving the problems that may arise due to CorDapp services not starting up in the correct order.

**Comment by peterli-r3** [comment]
Hi Ulrikrasmussen

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
