### ISSUE TITLE
Cannot add nodes dynamically using network boostrapper

### ISSUE THREAD

**Issue by karthik137** [corda/corda#5923]
I have created 5 corda nodes using network boostrapper. Then i added node6.conf in the nodes directory. My network was already running. Then  i ran this command ` java -jar corda-tools-network-bootstrapper-4.3.jar --dir=nodes/` .

It gave me this error message

```
#### Error while generating node info file ~/nodes/PartyA/logs ####
It appears there is already a node running with the specified data directory ~/nodes/PartyA
Shut that other node down and try again. It may have process ID 4050
```

My requirement is to add a new node to an existing network. I don't want to stop the existing nodes. 

How does demobench adds a new node to an existing network?. In demobench  we don't have to stop the node. New node is added dynamically.

Is there any solution or workaround for this?

**Comment by peterli-r3** [comment]
Hi Karthik137

The network bootstrapper does not support dynamically adding new nodes to the network. The optional solution is CENM or use the Corda network.
