### ISSUE TITLE
Suggestion: Add (wire)transaction type with implicit output states

### ISSUE THREAD

**Issue by ulrikrasmussen** [corda/corda#5925]
The current transaction model requires all output states to be explicitly serialized and included in the transaction that is sent over the wire. This is required even when the output states can be computed entirely as a (pure) function of the input states and the commands that operate on them.

For applications where the contract states have this property and at the same time can grow to be quite large, the current transaction model can incur an unneeded network overhead. If it was possible to implicitly compute the states, a given contract state would only ever have to be serialized to the vaults of the nodes (as an optimization; it can always be reconstructed from the transaction branch leading to it) and would never appear in the messages.

One possible model could be to add a new transaction type called `ImplicitLedgerTransaction` which wouldn't contain any outputs. One could then generalize `verify()` to be a function from `ImplicitLedgerTransaction` to `List<ContractState>`. `verify()` would simultaneously construct the output states and verify the commands relative to the input states, throwing an exception if verification fails.

The current `LedgerTransaction` model could easily be encoded in terms of `ImplicitLedgerTransaction` by adding a single command explicitly specifying the output states which `verify()` would simply return after running the verification logic.

**Comment by mikehearn** [comment]
Yes, that would make sense. The current model started with tokens where you can't always easily derive the outputs from the inputs (or they'd be equivalent in size) but that's not true for most apps.
