### ISSUE TITLE
deployNodes on macos doesn't manage several JDK installations

### ISSUE THREAD

**Issue by vjuge** [corda/corda#5926]
Hi,

context : 
Tested on a macos laptop, with default jdk1.8 and jdk12 installed.
with Corda 4.3
build task 'deployNodes' with Notary, PartyA & PartyB

issue : 
when starting the nodes, only Notary and PartyB deploys

Problem identified : 
after deployNodes, the generated 'runnodes' script refers to the "/usr/libexec/java_home" script to identify on macos what is the path to the jdk.
but this script could returns several results if there is several jdk installed, for example : 
````
$> /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home

$> /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    12.0.2, x86_64:	"Java SE 12.0.2"	/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
    1.8.0_221, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
````

Solution proposed : 
add a flag "-v 1.8" telling java_home to filter to the only jdk1.8

````
/usr/libexec/java_home -v 1.8
/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home
````

resulting ./build/nodes/runnodes : 
````
#!/usr/bin/env bash

set -eo pipefail

# Allow the script to be run from outside the nodes directory.
basedir=$( dirname "$0" )
cd "$basedir"

if [ -z "$JAVA_HOME" ] && which osascript >/dev/null; then
    # use default version of java installed on mac
    /usr/libexec/java_home -v 1.8 --exec java -jar runnodes.jar "$@"
else
    "${JAVA_HOME:+$JAVA_HOME/bin/}java" -jar runnodes.jar "$@"
fi
````

**Comment by peterli-r3** [comment]
Hi vjuge

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
