### ISSUE TITLE
Add stateMachinesFeed() to AppServiceHub

### ISSUE THREAD

**Issue by remmeier** [corda/corda#5931]
CordaRPC offers a method stateMachinesFeed() to get a feed of state changes, like flow progress updates. Currently no such API exists for Corda internal services, such as classes annotated with `@CordaService` and making use of  `AppServiceHub`. I think it would be worthwhile if there is a "feature parity" between remote and local Corda API.

**Comment by davidrapacchiale** [comment]
Hi @remmeier thanks for this.
Could you please describe a use case for this specific feature request?

**Comment by remmeier** [comment]
I image monitoring/traceability/auditing and error handling. This to let devs and operators get a better picture of what is going on in a node. 

we leaning towards plugging those functionality as "cordapp" resp. CordaService into the node rather than remotely using corda-rpc to minimize the number of components and have it as robust as possibl.

**Comment by remmeier** [comment]
another use case would be to implement an API other than corda-rpc. we struggle a bit with corda-rpc and are in the progress of moving to a REST API. It will be available on github somewhere soon. For that purpose it would be really helpful to have feature parity between local and remote Corda API. I can also do a PR if desired.
