### ISSUE TITLE
Corda exits when loopback connection fails for artemis messaging client

### ISSUE THREAD

**Issue by woutslakhorst** [corda/corda#5951]
Version: OS/4.3

This issues occurs when running Corda inside a docker container and the laptop goes to sleep. When it wakes again, a bunch of timeout messages are logged from activeMQ and the node exits. I think the problem lies within the creation of the BridgeControlListener in https://github.com/corda/corda/blob/1c2c3d3fed24a8f6e2488e474bdff5540cd00e43/node/src/main/kotlin/net/corda/node/internal/Node.kt#L307-L317. The given failoverCallback is `errorAndTerminate` preventing ActiveMQ from trying to reconnect (https://github.com/apache/activemq-artemis/blob/0b8c33bb0f495b43ed2247d720eb1d573067c814/artemis-core-client/src/main/java/org/apache/activemq/artemis/core/client/impl/ClientSessionFactoryImpl.java#L564).

The artemis client seems to be configured with a TTL of 60 seconds.

I understand the rationale behind the choice to exit the node when localhost can't be reached, but after a sleep this is well possible. In a normal development cycle our laptops are taken to meetings and closed several times a day, causing the corda nodes to fail and requiring the developer to restart the docker containers. A different (or no) callback would solve it since activeMQ has a build in reconnect mechanism which would have kicked in if the node didn't exit.

see also: https://github.com/corda/corda/blob/1c2c3d3fed24a8f6e2488e474bdff5540cd00e43/node-api/src/main/kotlin/net/corda/nodeapi/internal/ArtemisMessagingClient.kt#L30-L58

Logs:
```
[WARN ] 2020-02-12T13:59:55,297Z [Thread-23 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@34018757)] core.client. - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive
 data from /192.78.86.2:35884 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
[WARN ] 2020-02-12T13:59:55,334Z [Thread-23 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@34018757)] core.client. - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive
 data from /192.78.86.4:43410 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
[WARN ] 2020-02-12T13:59:56,969Z [Thread-21 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@37635407)] core.client. - AMQ212037: Connection failure has been detected: AMQ119014: Did not receive
 data from /127.0.0.1:48714 within the 60,000ms connection TTL. The connection will now be closed. [code=CONNECTION_TIMEDOUT]
[ERROR] 2020-02-12T13:59:56,991Z [Thread-12] errorAndTerminate. - ArtemisMessagingClient failed. Shutting down.
```

**Comment by davidrapacchiale** [comment]
Hi @woutslakhorst thanks for raising this.
We have attempted to solve this problem before but it conflicts with other requirements for the Flow reliability. Exiting and being restarted from checkpoints works properly, so this is by design.

**Comment by woutslakhorst** [comment]
We currently use Corda for distributing the legal basis for exchanging medical data. Developers use our docker-compose setup to run a local network (including 3 corda containers and 2 other containers). The Corda containers exit but the others remain running which include the main API interfaces.

two questions:
Do you concur that it hinders developer-happiness?
Could it maybe be an option to enable automatic reconnection when running local development?

**Comment by ifwithoutelse** [comment]
This is super inconvenient! There should be some work around.
