### ISSUE TITLE
ByteSequence not on whitelist or annotated @CordaSerializable issue while adding new node using network bootstrapper 4.0 OS

### ISSUE THREAD

**Issue by jayantvc** [corda/corda#5956]
Check below link for more information.

https://stackoverflow.com/questions/59896554/bytesequence-not-on-whitelist-or-annotated-cordaserializable-issue-while-adding

**Comment by davidrapacchiale** [comment]
Hi @jayantvc thanks for raising this. 
This bug was fixed in version 4.1 (you can see the relevant Jira https://r3-cev.atlassian.net/browse/CORDA-2782). Can you please try again with that version or later?
