### ISSUE TITLE
DbTransactionResolver possible speed-up?

### ISSUE THREAD

**Issue by lucaalbinati** [corda/corda#5965]
Looking at the implementation of DbTransactionsResolver.kt, I'm wondering why you fetch the required transactions for each `nextRequest`, one request at a time. As you can see from the line below:

https://github.com/corda/corda/blob/70e8e69a873d684bb1010de3b3f5caabf141d486/node/src/main/kotlin/net/corda/node/services/DbTransactionsResolver.kt#L58

Why don't you do:
`val (existingTxIds, downloadedTxs) = fetchRequiredTransactions(nextRequests))` ?

This would avoid running a flow for each request, and instead would run a flow for every phase of the breadth first traversal across the dependency graph.

**Comment by peterli-r3** [comment]
Hi luca

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
