### ISSUE TITLE
Cannot resolve net.corda:corda-common-logging:4.3

### ISSUE THREAD

**Issue by karthik137** [corda/corda#5973]
I had added  the following dependency to my pom.xml
```
		<dependency>
			<groupId>net.corda</groupId>
			<artifactId>corda-tools-network-bootstrapper</artifactId>
			<version>4.3</version>
		</dependency>
```

Intellij is not able to download the dependency. It is throwing  error:

```
Cannot resolve net.corda:corda-common-logging:4.3

```

Even this is also not working :

```
<!-- https://mvnrepository.com/artifact/net.corda/corda-common-logging -->
<dependency>
    <groupId>net.corda</groupId>
    <artifactId>corda-common-logging</artifactId>
    <version>4.1</version>
</dependency>


```

Any solution?. 

### My Workaround:

Manually added corda-common-logging pom.xml

**Comment by peterli-r3** [comment]
Hi Karthik137

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
