### ISSUE TITLE
Unable to add constants to java enum using CordaSerializationTransformEnumDefault annotation.

### ISSUE THREAD

**Issue by Ajay-V-Nair** [corda/corda#6002]
When trying to add an enum constant in java enum,
while adding new and old properties of CordaSerializationTransformEnumDefault annotation, annotation throws "Cannot find method 'value' " error.

Steps to reproduce the issue:
Add a new constant 'D' to enum, testEnum, with existing constants, 'A', 'B' and 'C' using CordaSerializationTransformEnumDefaults annotation.

@CordaSerializationTransformEnumDefaults("D", "C")
enum testEnum {
    A, B, C, D;
}

![image](https://user-images.githubusercontent.com/37908362/75334895-9eccd800-58ae-11ea-99b6-5c51d1a333e2.png)

Tried this issue with 4.1 and 4.3 release versions.

**Comment by peterli-r3** [comment]
Hi Ajay

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
