### ISSUE TITLE
Documentation » updating certificates

### ISSUE THREAD

**Issue by jufemaiz** [corda/corda#6007]
### A clear description of the issue

```
As an administrator,
When I have a business need to update a root certificate,
Then I want to have a known process to update Node Certificates,
So I can keep my corda stack running.
```

### Any logs or stack traces that you can provide (use a site like https://pastebin.com for larger logs)

N/A

### Steps to reproduce the issue

Issue a new network map root certificate.

### The version/tag/release or commit hash it occurred on

v3.3 (but all documentation I have been able to review is similar).

**Comment by peterli-r3** [comment]
Hi Jufemaiz

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
