### ISSUE TITLE
Specified CordaRPCClient classloader isn't used if reconnect specified on the .start

### ISSUE THREAD

**Issue by bkreiser** [corda/corda#6031]
If you specify a classloader during the construction of a CordaRPCClient along
with using a reconnect policy in .start, the custom classloader isn't used.

For example,

val rpc = CordaRPCClient(hostAndPort, CordaRPCClientConfiguration.DEFAULT, customClassloader)

// This keeps custom classloader
rpc.start(user, password)

// This doesn't keep custom classloader
rpc.start(user, password, reconnectPolicy)

> The problem is in CordaRPCClient.kt
> 
>        return if (gracefulReconnect != null) {
>             CordaRPCConnection.createWithGracefulReconnection(
>                     username,
>                     password,
>                     addresses,
>                     configuration,
>                     gracefulReconnect,
>                     sslConfiguration
>             )
> 
> Should be
> 
>        return if (gracefulReconnect != null) {
>             CordaRPCConnection.createWithGracefulReconnection(
>                     username,
>                     password,
>                     addresses,
>                     configuration,
>                     gracefulReconnect,
>                     sslConfiguration,
>                     classLoader
>             )

**Comment by chrisr3** [comment]
I think this issue has [already been fixed](https://github.com/corda/corda/blob/release/os/4.4/client/rpc/src/main/kotlin/net/corda/client/rpc/CordaRPCClient.kt) for Corda 4.4.

**Comment by bkreiser** [comment]
Ok.  As of the date that I submitted the issue, the master still didn’t
have the fix but I will check again tomorrow

B
