### ISSUE TITLE
A log error when using input in a contract test

### ISSUE THREAD

**Issue by jaro-sagan** [corda/corda#6050]
When using `input` call in a Contract test as is mentioned in the [documentation](https://docs.corda.net/tutorial-test-dsl.html#testing-single-transactions), input call creates a dummy transaction in the ledger (that won’t be verified) which outputs the specified state.

The output state is created but if there is some validation in a contract associated with the state we would like to create and if the verification fails, then an error message is thrown. So for example, when we have following test:

```kotlin
@Test
fun verifyUpdate() {
    ledgerServices.ledger {
        transaction {
            // Create an valid original state.
            val state = validState(ISSUE_VERSION)
            input(SomeContract::class.java.name, state)

            // Create a new proposed state.
            val outputState =
                SomenState(
                    ...
                )
            output(SomeContract::class.java.name, outputState)

            command(signers = VALID_ISSUE_REISSUE_SIGNERS, commandData = SomeContract.Reissue())
            verifies()
        }
    }
}
```

The test will pass but because our contract contains following line `val command = tx.commands.requireSingleCommand<Commands>()` the verification of the state we want to create fails which results in this exception:

```
[ERROR] 09:42:47,951 [Test worker] internal.Verifier. - Error validating transaction 7293EB14E6CCF712C86DBB856E1D49720847D0F934DA0D034E90264941EA7D78. [errorCode=j2o8gn, moreInformationAt=https://errors.corda.net/ENT/4.0.20190926/j2o8gn]
 java.lang.IllegalStateException: Required foo.bar.SomeContract.Commands command
```

When we have more of these tests it creates unnecessary "noise" in test logs. It would be good to not log this exception when we are creating an initial state using `input` call.

**Comment by peterli-r3** [comment]
Hi Jaro

With Corda 5 coming soon, we are closing up the issues prior to Corda v4.5. Thank you for your contribution to Corda!

Please feel free to contact devrel@r3.com if you need any further information
