### ISSUE TITLE
Address in Network Map is wrong

### ISSUE THREAD

**Issue by bert2002** [corda/corda#6064]
Hi,
running Corda 4.3 in testnet and the network map is reporting its local ip address and not the public ip address. It is a VM in the IBM Cloud and the public ip is a floating ip.

In the configuration p2pAddress is set to the local ip address, which I see in the network map as well. 

How can I define the external ip address?

Many thanks,
bert

**Comment by mnesbit** [comment]
You should be able to set p2paddress to whatever external ip and port you require.

**Comment by bert2002** [comment]
Wow. That indeed worked @mnesbit . Thanks a lot :D
