### ISSUE TITLE
Broken configuration handling for fiber instrumentation verification

### ISSUE THREAD

**Issue by remmeier** [corda/corda#6068]
In Fiber.class of Quasar we have:

```
   private static final boolean verifyInstrumentation = SystemProperties.isEmptyOrTrue("co.paralleluniverse.fibers.verifyInstrumentation");
```

In Corda we have:

```
if (configuration.devMode && System.getProperty("co.paralleluniverse.fibers.verifyInstrumentation") == null) {
            System.setProperty("co.paralleluniverse.fibers.verifyInstrumentation", "true")
        }
```

leading to non-dev versions also doing verification

**Comment by rick-r3** [comment]
Not quite true (no pun intended!).   `SystemProperties.isEmptyOrTrue()` returns `false` if the property is not set at all so the instrumentation _should_ default to off.  Are you observing different ?

**Comment by remmeier** [comment]
oh right, sorry.
