### ISSUE TITLE
Revisit corda-rpc & APIs

### ISSUE THREAD

**Issue by remmeier** [corda/corda#6089]
I consider myself a big fan of Corda. But we in our project we could never quite warm up to Corda RPC. This for a number of reasons, both in terms of design/architecture and day-to-day operations. Some of those very subtle that we would never have forseen. But first things first, there are also many good things about it. Having a Java Client API is really useful. Not having to fiddle around with lower layer protocol details and stuff. Also having the possiblity to not just make requests, but also have listeners and everything. So it is rather powerful. We go with our application to production in a week time, corda-rpc included. But more likely than not, we will drop it in favor of an alternative approach in subsequent releases.

So where are the problems? Disclaimer: It is more a summary of things encountered the past 12 months. So maybe one or the other thing is fixed. But to the most degree I think the issues are still there even tough not looking into detail in every area. We are ware of things like https://github.com/corda/openapi-sample. But here the ticket is really all about the main corda rpc API we make heavy use of.

- Mit e.g. REST and gRPC there are two very mature alternative implementations on the market. Those are well established and mature. In contrast, e.g. graceful reconnect was introduced to Corda only in around 4.3. We tried making use of it. But from time to time we ran into issues. This led to abandoning it again. Connection pooling, multi-threading, retries, circuite breaker are not trivial, but already battle proofed and well understood by "the competition". Designing all this from scratch feels like a major undertaking for a project that already has ample of those due to being in the fast moving blockchain space. 
- Given that it is somethign completely custom, it is not "stackoverflow-friendly" and information is scarce. 
- It is limited to Java on the client side. In theory with AMQP of course not. In practice it is.
- It is a mix of request/response model and queuing system. It seems neither 100% one or the other. But usually when working on a concrete use case, we would expect it to be like that and choose one or the other approach best fit to solve it. For example, messages are routed through JMS to the server. So we figured "great, we can send things to Corda, it will queue it, and Corda can take care of it when it is up and running" or "we can start many flows, things will queue up and Corda takes care of when there is capacity". But this does not seem to happen. The async client is blocked when doing a call to start a flow. I think it blocks until till the first checkpoint is hit. So in case of a single node it will fully proccees the flow and then corda-rpc returns on the other side. So in this case it is more request/response. In other areas we would really like to to be request/response. If it does not respond in one, two seconds, it should not bother anymore. A queuing system seems overkill for this purpose.
- Corda internally runs to JMS servers, one for p2p traffic and one for rpc. Would be generally nice for Corda to be "lighter" (with many improvements already the past months).
- The listener functionality is great for "lighter" use case to get notified about things. But for productive work loads where not a single event is allowed to be lost, corda-rpc is in its current form is not yet suitable. Its use of temporary queues prevent it from giving the assurances we would expect from a queue-based system.
- corda-rpc with the ActiveMQ JMS client is rather heavy on the client side. Doubling the footprint of our services. Not end of the world, but one pays a little for that on a day to day basis in terms of memory footprint, startup times, docker image sizes, build speed, developer round trip times, etc.
- Having to have the actual flow implementations on the client side to be able to start them is a further dependency burden for the client. It should not be necessary to expose flow implementation to the clients, but having it clearly separated. Maybe with an interface contract.
- The strict type-safe nature assumes client and servers will see the same set of flow classes. But I think this will not be the case for many to most cordapps implemented in the future. Making self-contained cordapps is important. There have been many discussions in the area. For our purposes we forked the Corda gradle plugins and integrated them with https://github.com/johnrengelman/shadow. The resulting cordapps are dependency free. All third-party classes are shadowed into our own local package. Then minimized and some further logic to keep them reproducible (with signatures included). This way we can be sure the cordapp brings everything along that is necessary and will not break due to other cordapps having the same classes in different versions. So what does this means in therms of corda-rpc? The server will make use of shadowed classes, whereas the client would rather not do that for the sake of usability/simplicity/developer-friendlyness (shadowing is an isolation feature for the server). Such a setup causes everything from warnings to errors, e.g. when returning a shadowed Exception. Over-time the number of own third-party helper libraries we shadow into our Cordapps has grown quite a bit and with that also the problems in the area.

**Comment by joeldudley** [comment]
Hi Remo,

Thanks for documenting these concerns, this is very helpful reference list.

We are looking currently at how we can improve the experience of interacting with Corda. In the first instance, this will probably take the form of GUI tools. But we agree that there are many improvements that could be made on the RPC side as well.

I will keep your points in mind as part of this ongoing work.

Thanks - Joel

**Comment by remmeier** [comment]
sounds promosing. Thank you for your reply. a web UI would be really helpful. Which in turn would imply a REST endpoint. Could be complemented with a Java wrapper for ease of use. Currently we have home grown things for that following the JSON:API spec. The already existing JavaFX  things are nice but a bit problematic when it comes to production rollouts, a web UI is easier to manage, secure and point people to.

**Comment by djc** [comment]
This might be of interest: https://github.com/djc/corda-rpc/. It does not alleviate any of the issues with how the protocol is set up (and I agree with many of those), but it should allow lighter-weight RPC clients.
