### ISSUE TITLE
corda-rpc does not free resources when querying stateMachinesSnapshot

### ISSUE THREAD

**Issue by remmeier** [corda/corda#6101]
I'm using corda-rpc to get state machine snapshots. Our server log is filling up with:

```
14:07:28 [31mWARN [0;39m [ads-1845301305)] [36m[internal.RPCClientProxyHandler][0;39m  A hot observable returned from an RPC was never subscribed to. This wastes server-side resources because it was queueing observations for retrieval. It is being closed now, but please adjust your code to call .notUsed() on the observable to close it explicitly. (Java users: subscribe to it then unsubscribe). If you aren't sure where the leak is coming from, set -Dnet.corda.client.rpc.trackRpcCallSites=true on the JVM command line and you will get a stack trace with this warning. [,,] 
net.corda.client.rpc.internal.RPCClientProxyHandler$CallSite: <Call site of root RPC 'stateMachinesSnapshot'>
	at net.corda.client.rpc.internal.RPCClientProxyHandler.invoke(RPCClientProxyHandler.kt:285)
	at com.sun.proxy.$Proxy156.stateMachinesSnapshot(Unknown Source)
	at net.cardossier.corda.rest.invocation.GetStateMachineSnapshotInvocation.execute(GetStateMachineSnapshotInvocation.java:14)
```

We make use of that method quite frequently. Now that method is not really returning any observable. I suspect this is a bug? Behind the scenes the rpc implementation makes use of :

```
   override fun stateMachinesSnapshot(): List<StateMachineInfo> {
        val (snapshot, updates) = stateMachinesFeed()
        updates.notUsed()
        return snapshot
    }
```

Likely that observable is not really closed, even tough at least a updates.notUsed() is called.  Tested this with current 4.4 pre-release version.

**Comment by rick-r3** [comment]
See the comment on https://r3-cev.atlassian.net/browse/CORDA-3709

You need to close all the `Observables` inside the `DataFeed` inside `StateMachineInfo`.

**Comment by remmeier** [comment]
aha, I guess that may fix it. But in general that brings me a bit back to https://github.com/corda/corda/issues/6089. If I get a list of things, the method itself is named "get snapshot something", barely any developer will even think of closing fields on the result items. I would rather have expected for the complete data structure to be a snapshot.
