### ISSUE TITLE
Logging needs to include timezone

### ISSUE THREAD

**Issue by gendal** [corda/corda#646]
Our logging policy is to log in GMT.   A typical entry in the log looks like this:

`[INFO ] 2017-05-08T11:41:16,170 [main] Main.main - Release: 0.12-SNAPSHOT`

Notice how we don't include a timezone indicator (eg +00:00 or Z) so the reader has no way to know this is GMT and not "local time".

Suggestion: we add a timezone indicator.  

eg if we didn't log milliseconds, it would be:

`2017-05-08T11:41:16Z`

I assume, with milliseconds, it is included at the very end.  But we should check as I'm not 100% sure

**Comment by dhingra** [comment]
@gendal 
Hi Richard,
I am looking forward to contribute to corda.
Could you please assign this issue to me? This will act as an exercise to go over the code-base.

Thanks,
Rohit

**Comment by gendal** [comment]
Hi Rohit - Actually, I think this issue is fixed.

eg here's an entry from the startup of a notary on 1.0:

`[INFO ] 2017-10-26T20:32:39,540Z [main] internal.Node.logStartupInfo - PID: 80783`

But we've been meaning to list some issues that newcomers to the code base can work on and this is a good reminder!  Hey @roger3cev  - is there anything we can point Rohit at?

**Comment by dhingra** [comment]
@roger3cev are there any issues I can work on?
Thanks
R

**Comment by joeldudleyr3** [comment]
@dhingra If you're still interested, reach out on the #design channel of the Corda Slack (slack.corda.net).
