### ISSUE TITLE
In M11 sub-classes of InputStream aren't automatically whitelisted

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#652]
In M11 you cannot pass a subclass of InputStream over RPC if it's not one of the types we have manually whitelisted, although it is safe to do so.

**Comment by chrisr3** [comment]
Is this something else for M11.1?

**Comment by mikehearn** [comment]
Yeah, ideally.

**Comment by chrisr3** [comment]
I think Andras has already fixed this for M12 in commit [de88ad4f4062885e92cc05a4d96e2cd549d3a4d9](https://github.com/corda/corda/commit/de88ad4f4062885e92cc05a4d96e2cd549d3a4d9). However, I don't think that this is suitable for cherry-picking,

**Comment by mikehearn** [comment]
Yeah, Andras' work is more like a rewrite of RPC in the end! Perhaps we can find a quick fix for M11.

**Comment by chrisr3** [comment]
Fixed by [f3e6980c55ee016991a60d602e97a6f040bfefff](https://github.com/corda/corda/commit/f3e6980c55ee016991a60d602e97a6f040bfefff).
