### ISSUE TITLE
Error running shell script to load transactions and get the attached error on Node C

### ISSUE THREAD

**Issue by sjwwebster** [corda/corda#66]
[Very_simple_Shell_Script_to_load_Corda_Transactions.txt](https://github.com/corda/corda/files/652499/Very_simple_Shell_Script_to_load_Corda_Transactions.txt)
[Error_Output_.txt](https://github.com/corda/corda/files/652502/Error_Output_.txt)

**Comment by mikehearn** [comment]
Can you try blowing away your node directories please? This error can occur (for now) when we change things and old data is in the database, as we aren't currently providing backwards compatibility.

**Comment by shamsasari** [comment]
Assuming this has been resolved. If not please raise a new ticket.
