### ISSUE TITLE
SecureHash.preImageResistantHashAs() triple-hashes, should be double

### ISSUE THREAD

**Issue by mvdbos** [corda/corda#6844]
This test incorrectly passes:

```kotlin
    fun testDefaultPreImageResistant() {
        val data = byteArrayOf()
        val piResistant = SecureHash.preImageResistantHashAs("BLAKE_TEST", data)

        // triple hashing
        val expected = service.hash(service.hash(service.hash(data).bytes).bytes)
        assertEquals(expected.toHexString(), piResistant.toHexString())
    }
```
It uses the BLAKE_TEST custom hash algo from core/src/test/kotlin/net/corda/core/crypto/Blake2s256DigestServiceTest.kt.

This is because `SecureHash.preImageResistantHashAs` does this:

```kotlin
val firstHash = digest.preImageResistantDigest(bytes) // returns double-hashed bytes
HASH(algorithm, digest.digest(firstHash)) // hashes one more time. Total three times.
```

Note that digest.preImageResistantDigest() already is defined to do double hashing:

```kotlin
fun preImageResistantDigest(bytes: ByteArray): ByteArray = digest(digest(bytes))
```

I would expect that if I override `digest.preImageResistantDigest` to do single hashing that `SecureHash.preImageResistantHashAs` does not add another hashing round. This would be fine for  Blake2s, which is already resistant to this attack.

Older tests for the the standard SHA2-256 algo pass, because that doesn't use this logic and still uses `sha256Twice`, which indeed hashes twice and not three times: 

```kotlin
fun sha256Twice(bytes: ByteArray) = sha256(sha256(bytes).bytes)
```

The solution seems to be to change the definition of `SecureHash.preImageResistantHashAs` to:

```kotlin
        fun preImageResistantHashAs(algorithm: String, bytes: ByteArray): SecureHash {
            return if (algorithm == SHA2_256) {
                sha256Twice(bytes)
            } else {
                val digest = digestFor(algorithm).get()
                HASH(algorithm, digest.preImageResistantDigest(bytes))
            }
        }
```

**Comment by mvdbos** [comment]
Fixed

**Comment by NooruddinLakhani** [comment]
@mvdbos How?

**Comment by mvdbos** [comment]
@NooruddinLakhani Here: https://github.com/corda/corda/pull/6849/files#diff-17f10e20b9355f2e48f58043bf3489aad5fa7af81592a2852ee794fc0e706a43R225
