### ISSUE TITLE
How can I get corda-tools-ha-utilities-<version>.jar

### ISSUE THREAD

**Issue by natureoo** [corda/corda#6859]
I can't find this corda-tools-ha-utilities-.jar from internet or enterprise version, could anyone told me that how I could get it , version 4.4 to 4.7 is ok to me . thx.

**Comment by sownak** [comment]
I think it is only provided with an enterprise license

**Comment by nargas-ritu** [comment]
Created [CORDA-4194](https://r3-cev.atlassian.net/browse/CORDA-4194) for an internal review

**Comment by nargas-ritu** [comment]
The jar is present in the subsequent patches of 4.7
