### ISSUE TITLE
If local transaction record fails, state becomes unrecoverable, as it will be notarised already at this point

### ISSUE THREAD

**Issue by janisolekss** [corda/corda#6861]
If multiparty flow fails on FinalityFlow local record, even if it is hospitalized, it won't be recoverable, as flow will be checkpointed at notarisation, not on local write in. This causes the case of notary conflict, as retry will restart from last checkpoint.

Easy way to "kill" local record is to have rawUpdate listening and throw exception from the process function (errroHanlder function should not be provided to force Corda go into flow-hospitalization state)

**Comment by lankydan** [comment]
Talked through with Janis about this and don't think this is a problem since the notary will return the original notarisation response if a single transaction is sent multiple times to a notary.
