### ISSUE TITLE
Corda OS 4.7 Notary is demanding notary.serviceLegalName even when registering as single notary

### ISSUE THREAD

**Issue by sownak** [corda/corda#6903]
**Description**
While setting up a single Notary with Corda OS 4.7, the notary registration is failing with the following error

```
[ERROR] 16:19:46+0000 [main] internal.NodeStartupLogging. - Exception during node registration: The notary service legal name must be provided via the 'notary.serviceLegalName' configuration parameter
[ERROR] 16:19:46+0000 [main] internal.NodeStartupLogging. - Exception during node startup: The notary service legal name must be provided via the 'notary.serviceLegalName' configuration parameter

```
Even when there is no HA setup and we are following instructions as provided in https://docs.corda.net/docs/corda-os/4.7/corda-configuration-fields.html#notary

**Logs**
--- Corda Open Source 4.7 (75618ca) -------------------------------------------------------------

Logs can be found in : /base/corda/logs

*******************************************************************
* *
* Registering as a new participant with a Corda network *
* *
*******************************************************************

[ERROR] 16:19:46+0000 [main] internal.NodeStartupLogging. - Exception during node registration: The notary service legal name must be provided via the 'notary.serviceLegalName' configuration parameter
[ERROR] 16:19:46+0000 [main] internal.NodeStartupLogging. - Exception during node startup: The notary service legal name must be provided via the 'notary.serviceLegalName' configuration parameter

**Steps to reproduce**
1. Define a node conf file for Corda 4.7 Notary i.e. use `notary : {  validating : false }`
2. Run node registration with networkmap/doorman service using ` java $JAVA_OPTIONS -jar ${CORDA_HOME}/corda.jar initial-registration --network-root-truststore-password ${DEFAULT_TRUSTSTORE_PASSWORD} --network-root-truststore ${BASE_DIR}/certificates/network-map-truststore.jks --base-directory=${BASE_DIR}
`
3. Registration fails

**Comment by fbenantar** [comment]
Hi,

have you been able to manage this issue ?

I am facing the same issue since this morning.

Cheers

**Comment by sownak** [comment]
@fbenantar yes, I was able to hack this by using the `serviceLegalName` for notary which must be different from the legalName

**Comment by sachingokhale** [comment]
Ticket raised for internal review - CORDA-4184
