### ISSUE TITLE
NumberFormatException in NodeStartup when debugging

### ISSUE THREAD

**Issue by adnjerem** [corda/corda#6905]
https://github.com/corda/corda/blob/241170ffa4f63616daeefb5dbb0dcd8d2c3ff21c/node-api/src/main/kotlin/net/corda/nodeapi/internal/JVMAgentUtilities.kt#L18

Kotlin `Short` being signed, the conversion is not correct: `toShort` throws a `NumberFormatException` for any valid port above 32767.

This can happen in `NodeStartup` during interactive debugging sessions, where in some cases (e.g. default configuration in IntelliJ) the port number is random:

https://github.com/corda/corda/blob/d4ff6d6b734b8e196e405437d37a859575d794e6/node/src/main/kotlin/net/corda/node/internal/NodeStartup.kt#L280

**Comment by sachingokhale** [comment]
Ticket for internal review - CORDA-4182

**Comment by rick-r3** [comment]
We would welcome a PR to fix this, if anyone feels inclined.
