### ISSUE TITLE
When shutting down, log the reason why

### ISSUE THREAD

**Issue by gendal** [corda/corda#691]
Determination of why nodes in DemoBench spontaneously shut down is hampered by insufficient logging.  We see the following in the log:

`[INFO ] 2017-05-15T22:39:54,470 [Thread-3] BasicInfo.printBasicNodeInfo - Shutting down ...`

But the _reason_ why we're shutting down isn't provided.

**Comment by gendal** [comment]
Point being...  we should explain why we're shutting down, even if it's in response to a terminal "bye" command, and do so at a high enough log level that it gets recorded in "regular" traces

**Comment by chrisr3** [comment]
The message "Shutting down" is printed by `Node.stop()`, which is called from the following places:
- a JVM shutdown hook that the node registers, and
- the CRaSH shell's "terminator" thread.

And the shutdown hook is triggered by (say) calling Java's `System.exit()`, Kotlin's `exitProcess()` or by the JVM receiving an external `TERM` signal. For reference, both locations where the node calls `System.exit()` directly are logged already. And the node only seems to call `exitProcess()` if it fails to start correctly.

We could add some extra logging to the CRaSH shell terminator, but this _should_ only be triggered if someone types "bye".

**Comment by gendal** [comment]
Thanks Chris.  But it would be interesting to know whether System.exit() was called or the JVM received an external TERM signal, no?

**Comment by chrisr3** [comment]
The DemoBench logfile that Adam Furgal posted contains this line;
> 2017-05-12T09:49:47,735 [INFO ] R3Pty - Terminal has exited (value=0)

which tells me that either the node exited normally, or it invoked `System.exit(0)` or `exitProcess(0)`. The exit value would not have been 0 if the node had received a `TERM` signal.

**Comment by chrisr3** [comment]
I've added a logging line to the CRaSH shell:
> [INFO ] 2017-05-16T09:12:20,815 [Command line shell terminator] shell.InteractiveShell.invoke - Command shell has exited
[INFO ] 2017-05-16T09:12:20,819 [Command line shell terminator] BasicInfo.printBasicNodeInfo - Shutting down ...

However, the thread name here is clearly "Command line shell terminator" whereas in the above example it is "Thread-3".

**Comment by chrisr3** [comment]
The CRaSH shell contains an extra logging line for when the user types "bye". And SIGTERM is specific to UNIX-like platforms; there is no such equivalent on Windows.
