### ISSUE TITLE
Wrong certificate signing URL results in `Vast Global MegaCorp, Ltd` being used

### ISSUE THREAD

**Issue by gary-rowe** [corda/corda#715]
When running up a Corda node it is possible to declare the TestNet certificate signing URL in dev mode. This results in `myLegalName` being ignored and `Vast Global MegaCorp, Ltd` in the certificates, but the actual `myLegalName` being used during network map registration. The resulting error is:

```
(ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$3@5dfb078-345144532)] messaging.ArtemisMessagingServer.hostVerificationFail$node_main - Peer has wrong CN - expected Vast Global MegaCorp, Ltd but got The Actual Legal Name. This is either a fatal misconfiguration by the remote peer or an SSL man-in-the-middle attack!
```

As a side note, it might be worth enclosing the above node names within single quotes e.g. `'Vast Global MegaCorp, Ltd'` to assist with identifying whitespace within legal names.

**Comment by patrickkuo** [comment]
Which version of corda are you running?

`certificateSigningService` is only used when the node start with `--initial-registration`flag, it shouldn't cause the node to pickup the wrong name. The keystore is created at the node's first startup, you will need to delete the keystore if you decide to change the legal name.

**Comment by gary-rowe** [comment]
I'm running Corda M11.1 running a clean dev mode startup, but accidentally including the M10.1 TestNet cert signing URL in `node.conf`. After chatting to @mikehearn about it we decided to log it as an issue to ensure better handling was made (and of course the correct `legalName` was used).

**Comment by joeldudleyr3** [comment]
Fixed.

**Comment by gary-rowe** [comment]
👍 Thanks Joel
