### ISSUE TITLE
Cannot type capitals into DemoBench terminal on Windows

### ISSUE THREAD

**Issue by Clintonio** [corda/corda#719]
Description: Capslock works, shift doesn't when trying to write capitals into the CRaSH terminal.

Repro steps: Start a node in demo bench M11.1 version then attempt to use Shift + A to type the letter A, this will fail. 

Cause: Likely this: https://github.com/corda/corda/pull/460 @chrisr3 recommends conditionally disabling the ZeroFilter on Windows.

**Comment by chrisr3** [comment]
I cannot reproduce this on my Win10 laptop because of the HiDPI bug. My terminal remains blank and my console fills with repeats of this message:
> NGExternalNode: failed to create a texture

**Comment by chrisr3** [comment]
The JetBrains JDK contains a partial fix for the HiDPI problem on Windows, in so far as it allows JediTerm to displayon _one_ of my monitors. Unfortunately, this allows me to determine that the `ZeroFilter` is _not_ the reason why CRaSH cannot display capital letters.

**Comment by mikehearn** [comment]
This works now, I can type capital letters into the terminal just fine. However on my Windows 10 on MacBook VM, the problem with Swing having tiny fonts has come back. I thought we'd fixed that?
