### ISSUE TITLE
Locations on map look strange

### ISSUE THREAD

**Issue by ediphy-cmurphy** [corda/corda#748]
When I create new nodes they appear on odd places on the network explorer map (Liverpool showing up as somewhere in Belgium etc). When I quit the explorer window and re-open they appear in the correct place.

**Comment by chrisr3** [comment]
I can reproduce this using DemoBench from M11.1:
- Create a Notary node, and then open its explorer.
- Open the explorer's network view; the Notary should be correctly shown in Rome.
- Create the "Bank of Breakfast Tea" in Liverpool
- Check the Notary's network view again. The Bank will appear in the wrong place.

@kasiastreich has pointed out that the Bank will move back to Liverpool once you click the map's "zoom-in" button.

**Comment by chrisr3** [comment]
Fixed by #794.
