### ISSUE TITLE
Error running gradlew samples:trader-demo:runBuyer

### ISSUE THREAD

**Issue by SKolodynski** [corda/corda#750]
I am trying to run the Trader Demo.
When I run 
./gradlew samples:trader-demo:runBuyer 
(with the NotaryService, BankOfCorda, BankA and BankB nodes running without errors)
I get the error "Exception in thread "main" java.lang.Exception: Unable to locate CN=BankOfCorda,O=R3,OU=Corda QA Department,L=New York,C=US in Network Map Service"

Indeed, the Node Explorer shows that BankOfCorda has OU=corda, rather than OU=Corda QA Department
I am on Ubuntu 17.04, using Java HotSpot 1.8.0_131, corda cloned on 2017-05-24.

**Comment by kasiastreich** [comment]
Solved by: https://github.com/corda/corda/pull/752
