### ISSUE TITLE
Explorer transactions view shows irrelevant transactions

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#786]
Transactions that are part of a chain of custody appear in the transactions view in the Explorer. This issue is not for discussion of privacy (we have plenty of efforts around fixing the underlying privacy issues blockchains inherently have), but rather just not showing irrelevant data in the UI.

**Comment by abbasdgr8** [comment]
Hello @mikehearn @joeldudleyr3 

I would like to fix this issue. Should I just proceed by doing the fix and raising a PR?

**Comment by mikehearn** [comment]
Hi Abbas, I don't work for R3 anymore. Perhaps Joel can comment.

**Comment by abbasdgr8** [comment]
Hi @joeldudleyr3, awaiting your response.

**Comment by nargas-ritu** [comment]
Internal ticket  [CORDA-4253](https://r3-cev.atlassian.net/browse/CORDA-4253)
