### ISSUE TITLE
BFT Notary creates unused table NODE_NOTARY_COMMIT_LOG

### ISSUE THREAD

**Issue by chrisr3** [corda/corda#813]
Checking the DB schema in H2 after running the BFT case in `notary-demo`, and I noticed that the table `NODE_NOTARY_COMMIT_LOG` had been created but not used. The BFT notary actually uses a table called `BFT_SMART_NOTARY_COMMITTED_STATE`.

Digging deeper, the function `Node.makeUniquenessProvider()` creates either `RaftUniquenessProvider` or `PersistentUniquenessProvider`, depending on whether or not the notary is a Raft-type. It does not consider the case of a BFT notary, which does not use the uniqueness provider that is created.

Is `BFT_SMART_NOTARY_COMMITTED_STATE` part of the BFT notary's uniqueness provider implementation? In which case maybe this should be created by `Node.makeUniquenessProvider()` too?

**Comment by adagys** [comment]
I'm planning to remove the `Node.makeUniquenessProvider()` as part of my refactoring in #883
