### ISSUE TITLE
Issue with Attachment/Simm/Dist notary demos in IntelliJ on master

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#88]
Trying to run the nodes for both the attachment, simm and dist notary demos using the run configs on master causes the following msg to appear:

`Listening for transport dt_socket at address: 5005`
`Listening for transport dt_socket at address: 5006`
`Listening for transport dt_socket at address: 5007`
`Listening for transport dt_socket at address: 5008`
`Process finished with exit code 0`

The following steps then fail.

**Comment by josecoll** [comment]
Fix on its way - will get Shams to review.

**Comment by shamsasari** [comment]
This has been resolved in #92.
