### ISSUE TITLE
Build Failure with  checkout -b release-M12.1 - Need Help.

### ISSUE THREAD

**Issue by aswinkumarrhex** [corda/corda#888]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'corda-project'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download dokka-gradle-plugin.jar (org.jetbrains.dokka:dokka-gradle-plugin:0.9.14)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/dokka/dokka-gradle-plugin/0.9.14/dokka-gradle-plugin-0.9.14.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/dokka/dokka-gradle-plugin/0.9.14/dokka-gradle-plugin-0.9.14.jar'.
            > Connect to akamai.bintray.com:443 [akamai.bintray.com/184.50.120.11] failed: Connection timed out (Connection timed out)

Been working on this release and today morning i am unable to compile/build this .

**Comment by Clintonio** [comment]
Hi @aswinkumarrhex 

The best place to get help is on our [Slack](https://cordaledger.slack.com), this is for reporting bugs that we will look at.

As for your issue; it looks like a connection issue to Bintray and should be resolved, unless you have a firewall or proxy issue. If it still continues head over to our Slack and you will get a reply much sooner.

Thanks,
Clint
