### ISSUE TITLE
Exception cause gets lost when logging in flows

### ISSUE THREAD

**Issue by adagys** [corda/corda#953]
In our custom exceptions we tend to override `toString()` to provide the error message, but the loggers output the `message` field instead.

When we catch a `t: Throwable`, `t.toString()` evalutes to e.g. "Missing signatures for [notary] on transaction AD830F for net.i2p.crypto.eddsa.EdDSAPublicKey@2982eb7a"

But `logger.warn("Terminated by unexpected exception", t)` outputs:
```
[WARN ] 14:12:45,883 [Mock network] flow.[5dfc0621-9e0d-498b-a6c2-77fb58e26308].run - Terminated by unexpected exception
net.corda.core.transactions.SignedTransaction$SignaturesMissingException: null
	at net.corda.core.transactions.SignedTransaction.verifySignatures(SignedTransaction.kt:81) ~[main/:?]
	at net.corda.flows.ResolveTransactionsFlow.call(ResolveTransactionsFlow.kt:123) ~[main/:?]
```

**Comment by shamsasari** [comment]
We shouldn't really override toString() to provide the error message. I think the solution here is to update those exceptions which print "null" to use the message field, such as `TransactionResolutionException`.

**Comment by adagys** [comment]
Yes we should override the message instead

**Comment by adagys** [comment]
Fixed
