### ISSUE TITLE
Corda - IRSDemo not running

### ISSUE THREAD

**Issue by aswinkumarrhex** [corda/corda#969]
Hello All,
I have been able to successfully start my nodes from corda-templates but I am not sure I am making progress in the right direction.

1) Downloaded the code from Git -- Success
2) Did a  `./gradlew install` successfully and build is ready.
3) navigated to the IRS Demo and deployed the nodes using `./gradlew samples:irs-demo:deployNodes` then...
4) Ran a `./gradlew samples:irs-demo:installDist`at this point 

Logs can be found in                    : /opt/Workspace/corda/samples/irs-demo/build/nodes/NotaryService/logs
Database connection url is              : jdbc:h2:tcp://URL:38179/node
Database connection url is              : jdbc:h2:tcp://URL:34177/node
Database connection url is              : jdbc:h2:tcp://URL:41352/node

> Listening on address                    : localhost:10002

> RPC service listening on address        : localhost:10003

Providing network services              : corda.notary.validating, corda.interest_rates
Loaded plugins                          : net.corda.irs.plugin.IRSPlugin
Node for "R3" started up and registered in 37.85 sec

corda_admin@block:/opt/Workspace/corda/samples/irs-demo/build$

> Listening on address                    : 127.0.0.1:10005

RPC service listening on address        : localhost:10006
Loaded plugins                          : net.corda.irs.plugin.IRSPlugin
Node for "Bank A" started up and registered in 50.39 sec
Listening on address                    : 127.0.0.1:10008
RPC service listening on address        : localhost:10009
Loaded plugins                          : net.corda.irs.plugin.IRSPlugin
Node for "Bank B" started up and registered in 65.29 sec

this is the stack i have. I am unable to proceed on to view the 
http://URL:10007/web/irsdemo

not sure where or what i am missing. 

But the webPort of bank A, bank B and Notary @ http://URL:10004, @ http://URL:10007, @ http://URL:10010 doesn't run. Probably I am missing something here.

Intent : once i get a grasp of this demo i need to push my custom app(M.E.A.N Stack Development)into the corda fabric and view the using 
http://URL:10007/web/mycustomdemo

spent a solid 2 weeks and am stuck at displaying the UI components of the demo.

kindly drop in some bullet points so i can babystep to accomplish what i intent 

thank you all !!!

**Comment by ajithathayaharan** [comment]
I am having similar issue. When I deployed my Cordapp in Amazon instance, my webports configured to listen @ 10007 and 10010 are not working. If you had any luck with this, please let me know.

**Comment by joeldudleyr3** [comment]
In case like these, the first thing to check is that the various nodes' machines can ping each other using standard tools. That determines whether it's a networking error or a Corda error.

The next step is to check the node logs for errors, ideally uploading them with this issue.

We aren't able to replicate this issue on Corda 3, so we're closing it for now, but please re-open it and post the logs if you are able to replicate.
