### ISSUE TITLE
Docs not upated for new build location

### ISSUE THREAD

**Issue by wawrzek** [corda/corda#98]
Corda documentation (e.g. https://docs.corda.net/setting-up-a-corda-network.html ) indicates that build JAR(s) will appear in **<PROJECT_ROOT>/build/libs**, but after M6 it's **<PROJECT_ROOT>node/capsule/build/libs**.

**Comment by wawrzek** [comment]
That's suggested patch on docs.

[fix-jar-location-docs.patch.txt](https://github.com/corda/corda/files/682698/fix-jar-location-docs.patch.txt)

**Comment by mikehearn** [comment]
Is this still valid? The doc page in question no longer gives a path to the node jar at all.

**Comment by wawrzek** [comment]
@mikehearn you might be right. The whole 'Certificate signing request' functionality is part of Corda node. I would say this ticket is ready to be close.
